Add/stripe payment request button
Automattic/newspack-blocks pull request #1035
Opened 2022-02-02 15:52 UTC by adekbadek

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Adds support for [Stripe's payment request button](https://stripe.com/docs/stripe-js/elements/payment-request-button) in the streamlined Donate block.

~One major design decision here is that the submit button in the Donate block (not only streamlined) will have the primary color as the background color.~ _Not anymore, see comments_

---

Here's how it looks like:

Google Pay on an Android phone:

<img width="499" alt="image" src="https://user-images.githubusercontent.com/7383192/152181652-9ec0b9dc-f695-49ad-af0a-4dbd8be45aa1.png">

Apple Pay on an iPhone:

<img width="680" alt="image" src="https://user-images.githubusercontent.com/7383192/152182090-926b0a60-5539-4f29-a970-4f42c7a1d7f3.png">

On a desktop computer, with a saved payment method (Chrome browser):

<img width="707" alt="image" src="https://user-images.githubusercontent.com/7383192/152184818-06f07c5f-31bc-42c9-8dc0-9e26cd234b93.png">

On a desktop computer, without any payment methods available:

<img width="710" alt="image" src="https://user-images.githubusercontent.com/7383192/152182465-e78c4901-ac69-4f79-ac12-0076391ca333.png">

In WP editor:

<img width="654" alt="image" src="https://user-images.githubusercontent.com/7383192/152182485-fcc6bcad-8396-4516-b73a-36a9624ae287.png">

### How to test the changes in this Pull Request:

1. Use `add/stripe-location-code` branch of `newspack-plugin` (https://github.com/Automattic/newspack-plugin/pull/1483)
2. Configure Stripe as the Reader Revenue platform*
3. The code here is not payment-proxy-specific, so testing just one of the available ones is enough – the simplest is probably to add a card to Chrome browser. Make a donation and verify it did go through in Stripe (if Stripe test instance is used, the card won't be really charged).
4. For a good measure, also make sure the card flow is working (use `4242 4242 4242 4242` as the card)   

\* Setting `NEWSPACK_AMP_PLUS_ENABLED` env. variable to `true` is a prerequisite

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2022-02-02 15:56 UTC, thomasguillot commented
> It just made sense to me to have the CTA in the more prominent color, but maybe using the secondary color here was intentional? cc @thomasguillot

I don't know 🙂  but @laurelfulford should know.

2022-02-14 21:05 UTC, laurelfulford commented
> It just made sense to me to have the CTA in the more prominent color, but maybe using the secondary color here was intentional?

@adekbadek To be honest, I think this choice was a bit arbitrary :) the theme does use the secondary button by default for the buttons, and that's picked up by the donate block, but it's not being explicitly set on that block for that block. 

The secondary wouldn't always be less prominent -- though in the theme defaults it _definitely_ is, so I get where you're coming from here! @yogeshbeniwal's suggestion of having some kind of control to override the button's colour might be the best middle ground: it lets you make sure the colour is very prominent, and lets you get outside of your existing palette if you'd like -- it also makes sure we don't accidentally change how something looks on a live site if it's already set up the way someone likes it.

2022-02-15 15:07 UTC, adekbadek commented
I've reverted the button color change in 793a7b2da2b85ca407f063134ed748c8c2500883 (it's out of scope of this PR anyway). The button color should be customisable, but that can now be done via setting theme colors or custom CSS, so there's no need for this change. The button color will be as in other button on the site, and as @laurelfulford points out, it only really makes sense for the default theme, and the theme colors are probably always changed from the defaults.

2022-02-15 21:57 UTC, miguelpeixe requested changes
The flow is working with the regular card (`4242 4242 4242 4242`) and with GPay on a desktop Chrome.

I was not able to complete the flow with Apple or Android. While on an iPhone I got the Apple Pay flow started but immediately terminated without any messages. On an Android I got the following error after confirming the payment prompt: 

<img width="358" alt="image" src="https://user-images.githubusercontent.com/820752/154156219-d3cacfcf-3ff0-46fb-9789-56c080a05481.png">

Maybe these errors are related to the test environment?

2022-02-15 21:57 UTC, miguelpeixe commented on src/blocks/donate/edit.js
> +			<>
This fragment is superfluous since there's only one child element.

2022-02-15 21:57 UTC, miguelpeixe commented on src/blocks/donate/streamlined/utils.js
> +export const validateFormData = values => {
Non-blocking: it would be helpful to have inline docs for these utils functions.

2022-02-16 10:15 UTC, adekbadek commented on src/blocks/donate/edit.js
> +			<>
Done in dbc75df9d0f769155b928b651df006668aadd8eb

2022-02-16 10:15 UTC, adekbadek commented on src/blocks/donate/streamlined/utils.js
> +export const validateFormData = values => {
Done in 4cffbdab62f50f56b6150242a256d824928a5a5c

2022-02-16 10:41 UTC, adekbadek commented
@miguelpeixe – 

> I was not able to complete the flow with Apple or Android. 

I've updated the Plugin PR to error when customer could not be created – you should now see a more meaningful Stripe error after failure.

2022-02-16 13:52 UTC, miguelpeixe approved these changes
Thank you for the revisions!

2022-02-17 14:02 UTC, miguelpeixe approved these changes
👌 All payment methods are working as expected!

2022-02-17 14:24 UTC, merged