fix: disambiguate users and guest authors in Author List exclusions
Automattic/newspack-blocks pull request #1154
Opened 2022-05-31 22:03 UTC by dkoo

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

#1143 fixed a bug in the Author Profile block when authors and guest authors had the same ID. This PR fixes a similar bug in the exclusions attribute of the Author List block. However, it also requires https://github.com/Automattic/newspack-plugin/pull/1679 to be released to the `newspack-components` NPM package, so consider this a draft PR until that release is deployed.

Closes #1150.

### How to test the changes in this Pull Request:

1. In a local environment, checkout https://github.com/Automattic/newspack-plugin/pull/1679 and this PR.
2. Confirm that #1150 is not replicable: only the exact user or guest author you select should be checked in the block controls, and only that user or guest author should be excluded in the editor preview and on the front-end.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2022-06-30 08:06 UTC, adekbadek requested changes
This does not resolve issue #1150 for me, it still can be reproduced.

2022-06-30 16:20 UTC, dkoo commented
@adekbadek I remember now why this was blocked—it requires https://github.com/Automattic/newspack-plugin/pull/1679, which was recently released into the Newspack Components NPM package as v2.1.0. That package is updated in #1188, so once that's merged the fix here should start working. I'll update the status here to "On hold" until #1188 is merged.

2022-06-30 16:20 UTC, dkoo commented on src/blocks/author-list/edit.js
> +								console.log( suggestions );
Whoops! 7c3374e

2022-07-20 19:57 UTC, dkoo commented
`newspack-components` package has been updated and released; re-opening this PR.

2022-08-16 08:50 UTC, adekbadek approved these changes

2022-08-16 15:23 UTC, merged