feat: support new sponsor options to show authors and categories
Automattic/newspack-blocks pull request #1156
Opened 2022-06-03 17:23 UTC by dkoo

### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2022-06-10 13:17 UTC, adekbadek requested changes

2022-06-10 13:17 UTC, adekbadek commented on src/blocks/homepage-articles/templates/article.php
> +			<?php if ( ! empty( $sponsors ) || ( $attributes['showCategory'] && $category ) ) : ?>
If `showCategory` is `false` for block, but a post has a sponsor, the categories will be displayed.

2022-06-27 18:59 UTC, laurelfulford commented on src/blocks/homepage-articles/templates/article.php
> +			<?php if ( ! empty( $sponsors ) || ( $attributes['showCategory'] && $category ) ) : ?>
I ran into something similar: the categories are always displayed with the sponsor flag, even when the sponsor's settings is to only show the 'flag' and not the categories.

2022-06-27 23:43 UTC, laurelfulford commented
Hi @dkoo! I took a pass at updating the styles in the blocks.

Unlike the theme, there are changes in this PR that also affect the sponsors when the authors and categories are not visible: 

* I wrapped the sponsors in a `span` with the CSS class `.entry-sponsors` to help avoid the sponsors and authors from running together -- otherwise, the sponsor logos, sponsor bylines, author avatars and author bylines were all inside of the same parent element, and it was tricky to avoid them running together.
* I made it so the sponsor logo and byline sit side-by-side. Originally they always stacked, but this seemed weird when the author is also visible; the logo and sponsor will still stack if there's not enough room.
* If authors are also showing, a second CSS class (`plus-author`) is added to the `entry-sponsors` container to allow adding a bit of space underneath the sponsors, and to allow making the sponsors text a bit smaller, to match how they're handled in single posts. 

Overall, the sponsor flag and category should sit side by side when both are visible, and should wrap over two lines if there's not a lot of space (like when the image is floated left or right). 

The Sponsors should appear above the post author when both are visible. The sponsor text should be slightly smaller when both are visible as well. 

I've attached some screenshots of different block options, including the different text alignments, image alignments, and text sizes for the Homepage Posts block, and a couple of the Post Carousel block.

<details>
<summary><strong>Homepage Posts</strong></summary>

Default text alignment:

![image](https://user-images.githubusercontent.com/177561/176044250-9492c447-7c6b-48ff-9cd9-240afdb3f8ed.png)

Text align centre:

![image](https://user-images.githubusercontent.com/177561/176044332-2a0d0933-0039-49a7-a6e7-87ca7938f181.png)

Text align right: 

![image](https://user-images.githubusercontent.com/177561/176044283-dd347033-0368-4f9e-a2d9-28ba5fe95ed2.png)

The Sponsor text should remain the same size for font scales 4+ (like the rest of the post meta), but it should shrink with the smaller sizes along with the other post meta. For sizes 2 and 3, it should be smaller than 4 but the same size; it should go down even smaller for size 1:

![image](https://user-images.githubusercontent.com/177561/176045312-60f02890-82ae-4948-98db-5295b1e4c40f.png)

If the sponsor flag + category wrap over two lines, they should be nicely spaced out: 

![image](https://user-images.githubusercontent.com/177561/176054594-7feb7243-6c08-4a0b-9803-78db296b1dc6.png)

</details>

<details>
<summary><strong>Post Carousel</strong></summary>

![image](https://user-images.githubusercontent.com/177561/176052653-a44a1ac3-aabd-4489-9e59-550d7539d9b3.png)

![image](https://user-images.githubusercontent.com/177561/176052669-cf6642bf-c7fc-4b63-8e56-af4b6be5835a.png)

</details>

2022-06-29 22:09 UTC, dkoo commented
@laurelfulford thanks again for undertaking such a big set of changes! I ran into just a few extremely nitpicky/edge case things here:

With text at right alignment, the final image has a bit of margin which makes it look not aligned with the right edge of the column:
<img width="779" alt="Screen Shot 2022-06-29 at 4 01 48 PM" src="https://user-images.githubusercontent.com/2230142/176553153-4d927fab-44d9-4229-8bd1-d2bea3769470.png">

With the featured image thumbnails set to float on either side, the text alignment options do not affect the sponsor logos, even though they do affect the author avatars. It's somewhat hard to tell from the screenshots, but it's not because of the margins mentioned above—removing all margins in dev tools makes the logos appear flush-left.
<img width="788" alt="Screen Shot 2022-06-29 at 4 03 56 PM" src="https://user-images.githubusercontent.com/2230142/176553458-6a6e1061-903c-44a5-a815-6dd4306b26a7.png">

In the same screenshot above, you might notice there's a bit of right margin on the sponsor flag which makes it look misaligned with the column's right edge. This might be onerous to fix, it's not very noticeable, and it's likely pretty edge casey, so I'm okay with leaving it for now.

> this PR is currently failing some CircleCI tests, though I'm not sure why -- for the JS and TS tests, it's throwing newspack-scripts: not found and for the scss, it's returning stylelint: not found -- does this PR just need to be rebased, or is there something else happening?

Rebasing seems to have fixed the CI errors—thanks for highlighting!

2022-06-29 22:10 UTC, dkoo commented on src/blocks/homepage-articles/templates/article.php
> +			<?php if ( ! empty( $sponsors ) || ( $attributes['showCategory'] && $category ) ) : ?>
Whoops, good catch. b49888d should fix this.

2022-07-04 07:54 UTC, adekbadek approved these changes
Just one line to remove and we're good here.

2022-07-04 07:54 UTC, adekbadek commented on src/blocks/homepage-articles/edit.js
> +		console.log( post );
✂️
(I've added a rule for logging in the latest version of `newspack-scripts`)

2022-07-08 21:09 UTC, dkoo commented on src/blocks/homepage-articles/edit.js
> +		console.log( post );
Fixed in 9107c50, thanks for catching!

2022-07-08 21:25 UTC, dkoo commented
@laurelfulford I'm going to say this is all non-blocking now, because I think this is edge-casey enough that almost no site would use this combo of settings. But noting just for the record...

The alignment of sponsor logos looks great in column view now, on the front-end!
<img width="260" alt="Screen Shot 2022-07-08 at 3 21 26 PM" src="https://user-images.githubusercontent.com/2230142/178072128-deed683f-4f13-4d36-968d-94c29b728514.png">

However, there's still a bit of extra space in the editor:
<img width="817" alt="Screen Shot 2022-07-08 at 3 20 21 PM" src="https://user-images.githubusercontent.com/2230142/178072157-86965cc6-9bfb-4d9b-bf36-7c1217f28b05.png">

Same deal with the floated images + text alignment. Looks great on the front-end now:
<img width="1200" alt="Screen Shot 2022-07-08 at 3 23 38 PM" src="https://user-images.githubusercontent.com/2230142/178072325-7b24be8f-085e-4077-9ae5-81718dbbb817.png">

But still looks off in the editor:
<img width="819" alt="Screen Shot 2022-07-08 at 3 23 29 PM" src="https://user-images.githubusercontent.com/2230142/178072344-ff3a029f-5b95-4529-aacc-c64e1bed1da9.png">

I'd say since this only affects a specific combination of settings in the editor only, it's okay to leave for now, unless it's obvious to you what needs to be fixed. WDYT?

2022-07-08 23:50 UTC, laurelfulford commented
Thanks @dkoo! 🤦‍♀️ It looks like this was a mix of editor block styles coming from the theme (removed [here](https://github.com/Automattic/newspack-theme/pull/1833/commits/3a39e51b4c592265719524ad72234ae14f349355)), and some missing alignment styles in the blocks -- I was able to recreate some weirdness with the right alignment in the logos and category + sponsors flag on the front-end too. 

In [5b5c00e](https://github.com/Automattic/newspack-blocks/pull/1156/commits/5b5c00e5d8d27a4006cb67301f153ac5235a6e98) I added and updated the editor styles I removed from the theme, and added a right text alignment that seems to have fixed things. If you could give it one more peek, I'd appreciate it -- I think if there's anything else still kicking around, it should be safe to address in a separate PR unless it's really catastrophic 😅

2022-07-11 15:47 UTC, dkoo commented
@laurelfulford The latest changes fixed all the issues I was seeing in the editor. 🥳 I updated with `master` and fixed a couple of conflicts. @adekbadek since I opened the PR initially, do you want to do one last check before we merge, or are we good to go?

2022-07-12 07:21 UTC, adekbadek approved these changes
👌

2022-07-14 14:57 UTC, merged