Donate Block – amounts and frequencies customisation
Automattic/newspack-blocks pull request #1191
Opened 2022-07-01 10:32 UTC by adekbadek

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Allows for customisation of donation amounts and frequencies. 

Closes https://github.com/Automattic/newspack-blocks/issues/741 

### How to test the changes in this Pull Request:

_Testing instructions in https://github.com/Automattic/newspack-plugin/pull/1753_

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2022-07-01 14:52 UTC, thomasguillot commented
I've pushed a few changes in https://github.com/Automattic/newspack-blocks/pull/1191/commits/f80e6775b70f3fa7f8784169486a0d59cd929d0c

Instead of having the input directly in the editor, is there any way we could use conditional `PanelBody` for this?

![eg-donations-sidebar](https://user-images.githubusercontent.com/177929/176918258-1c11e8e6-c6e3-4873-b276-cdd29e7bff89.png)

2022-07-01 15:01 UTC, adekbadek commented
That's a tradeoff between a cleaner UI and discoverability. Panels are not great for discoverability and users might never know these amounts are customisable in manual mode. On the other hand, these are overrides, not meant to be frequently used. I think putting these in the panels is fine if the "main" panel clearly communicates where the amounts can be customised, if manual mode is selected. WDYT?

2022-07-01 20:03 UTC, dkoo requested changes
This is a big refactor and makes a lot of improvements! I also love seeing new TS examples in action that will be valuable for future reference.

I ran into a few odditites while testing—more details below.

2022-07-01 20:05 UTC, dkoo commented on src/blocks/donate/editor.scss
> +				display: flex;
Currently, the input of the last-highlighted tier will remain visible if you click outside of the block. If the block isn't currently selected in the editor, it should probably hide all of these inputs.

2022-07-04 08:54 UTC, adekbadek commented on src/blocks/donate/view.scss
>  			text-align: left;
This also happened with Minimal style. Fixed in 89afdd6af4fa1e59905ecc9b3f0513e9cd4b5dbe

2022-07-04 08:55 UTC, adekbadek commented on src/blocks/donate/view.scss
>  			border-right-width: 1px;
Good catch! Fixed in 3d847d006871cc820975c595f77c799e0f13dc39

2022-07-04 08:55 UTC, adekbadek commented on src/blocks/donate/edit.tsx
> +							setAttributes( { defaultFrequency } )
The syntax is correct here – it's not object destructuring (`( { var1: _var1 } )`), but a TS type annotation (`( var: VarType )`). 

But you're right that there was a regression here. When the default frequency was updated, the tab in the form was selected. I've added this functionality in be368dd31aef91d59998a7197d41e3da82c4ef8d.

2022-07-04 08:55 UTC, adekbadek commented on src/blocks/donate/editor.scss
> +				display: flex;
This UI has been changed as per [earlier discussion](https://github.com/Automattic/newspack-blocks/pull/1191#issuecomment-1172430028) on this PR.

2022-07-04 08:55 UTC, adekbadek commented
@thomasguillot @dkoo – alternative proposition for the amounts overriding UI:

<img width="266" alt="image" src="https://user-images.githubusercontent.com/7383192/177119897-9a2d7db2-b530-4f20-8e96-81b223d57b1f.png">

2022-07-05 07:27 UTC, adekbadek commented
> Alternatively, we could move the inputs into 2 rows/columns (but I still think it's a bit cramped with a lack of hierarchy)

I like this idea, done in 44053c76266d9d8212701cd4caa93c5a96ce294f. I think it's more intuitive, with the settings in one place, than dividing donation frequencies into panels.

2022-07-05 16:51 UTC, dkoo commented on src/blocks/donate/edit.tsx
> +							setAttributes( { defaultFrequency } )
Thanks for explaining the TS syntax! The regression is still reproducible for me, though. To replicate:

1. On `master`, add a Donate block to a post and leave the default frequency as-is (defaults to "monthly"). Save the post.
2. Switch to this branch and the corresponding branch in Newspack Plugin.
3. Refresh the editor. Observe that the block's default frequency is now "One Time" in the editor, even though it still shows the "Monthly" tab by default on the front-end.

2022-07-05 17:58 UTC, dkoo requested changes
Thanks for the changes! Looks like the only remaining issue is the [default frequency regression](https://github.com/Automattic/newspack-blocks/pull/1191#discussion_r914004942).

2022-07-07 07:57 UTC, adekbadek commented on src/blocks/donate/edit.tsx
> +							setAttributes( { defaultFrequency } )
Ah, I misunderstood what you've meant by "always gets reset". I thought it's about the block in the editor switching to the frequency when the default frequency attribute is updated – which was _also_ a regression.

Fixed in 5ed9720fef1fe8ccb9d8c5c0727063a6393df5d7

2022-07-08 22:19 UTC, dkoo commented on src/blocks/donate/edit.tsx
> +							setAttributes( { defaultFrequency } )
Ah, I see what you mean. I can confirm that both regressions appear fixed now:

* When I update the default frequency in block attributes, the editor preview selects that frequency
* When migrating blocks from `master` that had the default `monthly` frequency set, they're migrated correctly with the same frequency option selected in the editor.

2022-07-08 22:19 UTC, dkoo approved these changes
Looking good now!

2022-07-11 07:24 UTC, merged