feat: handle minimum donation option in Donate block
Automattic/newspack-blocks pull request #1239
Opened 2022-08-15 18:33 UTC by dkoo

### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Handles the new "minimum donation" setting from https://github.com/Automattic/newspack-plugin/pull/1895 in the Donate block front-end and editor.

Closes #1211 and https://github.com/Automattic/newspack-plugin/issues/1886.

### How to test the changes in this Pull Request:

See testing instructions in https://github.com/Automattic/newspack-plugin/pull/1895.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2022-08-16 08:34 UTC, adekbadek requested changes

2022-08-16 08:34 UTC, adekbadek commented on src/blocks/donate/streamlined/index.ts
> +				utils.validateFormData( formValues, settings?.minimumDonation || 5 )
WDYT about passing all settings to validation, so in the future it could rely on more signals without refactoring?

2022-08-16 08:34 UTC, adekbadek commented on src/blocks/donate/edit.tsx
> +						: attributes.minimumDonation
Same as in the [other review](https://github.com/Automattic/newspack-plugin/pull/1895#discussion_r946477783), this will not allow some valid values.

2022-08-16 17:19 UTC, dkoo commented on src/blocks/donate/edit.tsx
> +						: attributes.minimumDonation
Added warnings instead of coercing the values in 269c573.

269c573 also fixes a bug where the Minimum Donation field was only shown if the "Tiered" options was checked.

2022-08-16 17:20 UTC, dkoo commented on src/blocks/donate/streamlined/index.ts
> +				utils.validateFormData( formValues, settings?.minimumDonation || 5 )
Good idea—refactored in 269c573.

2022-08-17 08:12 UTC, adekbadek approved these changes
Pre-approving, since only a CSS tweak is needed.

2022-08-17 08:12 UTC, adekbadek commented on src/blocks/donate/edit.tsx
> +							<TextControl
This element would use some top-margin. If the last frequency is disabled, the elements are too close: 

<img width="263" alt="image" src="https://user-images.githubusercontent.com/7383192/185068415-82c7e5eb-9164-45cf-a569-f782261024d5.png">

2022-08-17 17:01 UTC, dkoo commented on src/blocks/donate/edit.tsx
> +							<TextControl
Added some top margin in c010de8:

<img width="262" alt="Screen Shot 2022-08-17 at 11 01 11 AM" src="https://user-images.githubusercontent.com/2230142/185199465-adfdfcc4-6d5b-432e-9de9-7ffaf7b16a60.png">

2022-08-18 15:03 UTC, merged