feat: handle reCAPTCHA settings and methods move to RAS
Automattic/newspack-blocks pull request #1244
Opened 2022-08-17 00:47 UTC by dkoo

### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2022-08-18 21:12 UTC, miguelpeixe requested changes

2022-08-18 21:12 UTC, miguelpeixe commented on src/blocks/donate/class-wp-rest-newspack-donate-controller.php
> +		$captcha_token = $request->get_param( 'captchaToken' );
If reCaptcha is enabled, it should fail if this param is empty

2022-08-19 22:52 UTC, dkoo commented on src/blocks/donate/class-wp-rest-newspack-donate-controller.php
> +		$captcha_token = $request->get_param( 'captchaToken' );
Updated in b50df46

2022-08-22 18:28 UTC, miguelpeixe requested changes

2022-08-22 22:18 UTC, dkoo commented on src/blocks/donate/class-wp-rest-newspack-donate-controller.php
> +						'error' => wp_strip_all_tags( $captcha_result->get_error_message() ),
Good point—updated in e9d2537 (and also added global namespaces to WP functions and classes).

2022-08-23 21:11 UTC, miguelpeixe approved these changes
🙌

2022-08-23 21:13 UTC, merged