fix(donate): default value not below minimum donation
Automattic/newspack-blocks pull request #1248
Opened 2022-08-19 17:43 UTC by miguelpeixe

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR sets the default value rendered on the block to never be below the configured minimum. It would be unintuitive for the donor not to be able to donate with the proposed value on the form.

Although the settings can be saved with a lower value, the displayed warning should be enough to let the user know that it may not behave as expected.

### How to test the changes in this Pull Request:

1. On the master branch, configure Reader Revenue Donations settings with a minimum donation to 5 and tiers below that value
2. Visit the page and confirm these values are rendered and you are unable to donate with the default values
3. Check out this branch and confirm the values are never rendered below 5 even though you are still able to store it that way and prompted with the warning

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2022-08-19 23:15 UTC, dkoo requested changes
This is a good enhancement! We should also apply the same check to the "tiered" inputs and their labels.

2022-08-22 14:24 UTC, miguelpeixe commented
Done in adcc7311d55ec197e4dd024bff1f35910dee5aef

2022-08-22 22:33 UTC, dkoo requested changes
The same `max` comparison also needs to be applied on lines 443 and 451 (input values and labels for the tiered suggested amounts).

2022-08-23 13:51 UTC, miguelpeixe commented
Whoops! Sorry about the back and forth! Should be fixed by a4a3e6ba30373c9233027dee77392e9f8572abe0

2022-08-25 16:58 UTC, dkoo approved these changes
Works well with both tiered and untiered options, now!

2022-08-25 17:22 UTC, merged