Feat/donate block tiers layout
Automattic/newspack-blocks pull request #1311
Opened 2022-11-17 11:18 UTC by adekbadek

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Adds an alternative, "tiers-based" layout to the Donate block: 

<img width="811" alt="image" src="https://user-images.githubusercontent.com/7383192/202211905-53f18f58-ea99-491f-a292-2fa6515e2cbf.png">

_Above in the "Alternate" block style version_

It's called "Tiers-based" layout (vs. the default "Frequency-based" layout), but I'm not sure about the naming here. Suggestions are welcome.

<img width="287" alt="image" src="https://user-images.githubusercontent.com/7383192/202214354-37128929-17a7-40fc-b374-ec418eeb0f9c.png">

Closes https://github.com/Automattic/newspack-product/issues/53

### How to test the changes in this Pull Request:

1. Set Stripe as the Reader Revenue platform
1. On `master`, create a page with three Donate blocks, set each to different style
2. Switch to this branch, ensure these all render as expected
3. Switch all to "Tiers-first" in the sidebar "Layout" panel
4. Visit the front-end, make a few donations using the new block layout, observe amounts and frequencies translating to Stripe 

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2022-11-17 17:47 UTC, dkoo commented
Haven't reviewed yet, but for this:

> It's called "Tiers-based" layout (vs. the default "Frequency-based" layout), but I'm not sure about the naming here. Suggestions are welcome.

I'd suggest just "Frequency" and "Tiers".

2022-11-22 14:17 UTC, thomasguillot commented
This is cool!

I'm very pleased with this. Just a few questions/suggestions:

* Can we style the 3 buttons differently? Ideally the "best value" box should have a filled button but the other 2 boxes should  have outlined buttons. So we have 1 primary CTA and 2 secondary CTAs.
* Can we make the "best value" label background/text colours customisable?
* Same with the "best value" black border, could we customise this? (thickness + colour inc. gradient)

2022-11-24 11:14 UTC, adekbadek commented
> Can we style the 3 buttons differently? Ideally the "best value" box should have a filled button but the other 2 boxes should have outlined buttons. So we have 1 primary CTA and 2 secondary CTAs.

Done in 49a99ef4162f850110fe5140e3c12e644ffea5f2 : 

<img width="861" alt="image" src="https://user-images.githubusercontent.com/7383192/203770612-f22ae257-0028-4134-be69-9519966fadbc.png">

> Can we make the "best value" label background/text colours customisable?
> Same with the "best value" black border, could we customise this? (thickness + colour inc. gradient)

Please submit a separate issue for this, this PR is pretty large as it is.

2022-12-05 22:53 UTC, dkoo requested changes
This is a big new feature—thanks for implementing! It's mostly clean, and I confirmed that existing Donate blocks continue to behave nicely with the new features as well.

I did run into some issues, some questions, and some non-blocking nitpicks.

2022-12-05 22:53 UTC, dkoo commented on src/blocks/donate/tiers-based/slider.ts
> +	const initialOptionIndex = Math.round( options.length / 2 ) - 1;
Non-blocking: Is this a good opportunity to use the existing "Default tab" attribute to let publishers choose which tier is shown first in the mobile slider view? Right now it always shows the middle option, but what if the annual option is the preferred one?

2022-12-05 22:53 UTC, dkoo commented on src/blocks/donate/tiers-based/view.ts
> +			backButton.style.display = 'none';
Good call—maybe we should also hide the tier details upon success? Current success message looks like this:

<img width="1220" alt="Screen Shot 2022-12-05 at 3 45 50 PM" src="https://user-images.githubusercontent.com/2230142/205759384-fcb9d55b-0a6e-41eb-9071-dd09cbaf2856.png">

2022-12-05 22:53 UTC, dkoo commented on src/blocks/donate/frontend/class-newspack-blocks-donate-renderer-tiers-based.php
> +					<div class="wpbnbd__tiers__tier-tile">
We should show the description somewhere in the full tile view.

2022-12-05 22:53 UTC, dkoo commented on src/blocks/donate/tiers-based/view.ts
> +			backButton.style.display = 'none';
A bug related to this: looks like if you have multiple instances of the Donate block on the page, if you submit a donation via one of the forms, the back button will be hidden in all block instances.

2022-12-06 11:38 UTC, adekbadek commented on src/blocks/donate/edit/TierBasedLayout.tsx
> +									<span>{ amount }</span>
This logic applies only to the "Other" tier, where the reader can choose the donation amount. There is no such option in the new tiers-based layout. 

> We should probably update both the editor preview 

Fixed for the frequency-based layout in 5f8c579bdf4e597b2b630ab6b1706169e456ed9d

> and the tiers layout in this instance.

Not sure about this. Currently the minimum donation value is forced only for the user-input amount. The other amounts just trigger a warning, which I think is fine. Coercing all amounts to the minimum would be separate change, unrelated to this PR.

2022-12-06 13:09 UTC, adekbadek commented on src/blocks/donate/frontend/class-newspack-blocks-donate-renderer-tiers-based.php
> +					<button class="wpbnbd__tiers__back-button">← <span><?php echo esc_html( __( 'Back', 'newspack-blocks' ) ); ?></span></button>
Can't reproduce that, on which browser does that appear?

2022-12-06 16:24 UTC, adekbadek commented on src/blocks/donate/tiers-based/view.ts
> +			backButton.style.display = 'none';
Huh, good catch! Fixed in de2ae2babc319e43cc35a1293a011f320e361335

2022-12-06 16:24 UTC, adekbadek commented on src/blocks/donate/edit/index.tsx
> +	const isTierBasedLayoutEnabled =
Hm, I don't remember why I'd added this condition. Enabled WC integration in 8ddd30125253a71b21797e3d8df56ecbc370e297

2022-12-06 17:01 UTC, adekbadek commented on src/blocks/donate/frontend/class-newspack-blocks-donate-renderer-tiers-based.php
> +					<div class="wpbnbd__tiers__tier-tile">
Hm, I'm not sure that's required – at this point the reader has already made the decision based on the descriptions. I'll defer to @thomasguillot on that – the question is about including the tier description in this view:

<img width="824" alt="image" src="https://user-images.githubusercontent.com/7383192/205975512-779e1813-e6df-4c4f-b3f3-208b97147696.png">

2022-12-07 09:51 UTC, thomasguillot commented on src/blocks/donate/frontend/class-newspack-blocks-donate-renderer-tiers-based.php
> +					<div class="wpbnbd__tiers__tier-tile">
I agree with @adekbadek, the reader has already chosen a "plan" based on the description so there's no need to repeat it here.

2022-12-09 19:47 UTC, dkoo commented on src/blocks/donate/edit/TierBasedLayout.tsx
> +									<span>{ amount }</span>
Ah, this is perfect for the value displayed in the block editor preview and the front-end, but I don't think we should force the value in the text input field when manually configuring the block. I think we should allow the value to remain with the warning as before for the config UI. Otherwise, for example, if your minimum is `6` and you go to enter `50` into the input, the UI won't let you.

2022-12-09 19:50 UTC, dkoo commented on src/blocks/donate/frontend/class-newspack-blocks-donate-renderer-tiers-based.php
> +					<div class="wpbnbd__tiers__tier-tile">
Sounds good, thanks for weighing in!

2022-12-09 19:55 UTC, dkoo commented on src/blocks/donate/consts.ts
> +	{ label: __( 'Frequency-first', 'newspack-blocks' ), key: 'frequency' },
Thanks for the update!

2022-12-09 19:56 UTC, dkoo commented on src/blocks/donate/block.json
> +					"description": "Small tier description",
👍

2022-12-09 20:00 UTC, dkoo commented on src/blocks/donate/edit/index.tsx
> +										{ availableFrequencies.map( ( frequency: DonationFrequencySlug ) => {
This fixes the issue of disappearing options. Noting here that "one-time" frequency is disabled for Tiers-based blocks even if enabled in default settings, as one-time donations don't make much sense in the tiers-based context.

2022-12-09 21:44 UTC, dkoo commented on src/blocks/donate/frontend/class-newspack-blocks-donate-renderer-tiers-based.php
> +					<button class="wpbnbd__tiers__back-button">← <span><?php echo esc_html( __( 'Back', 'newspack-blocks' ) ); ?></span></button>
Actually, something is still going on here. My site is AMP Plus, if that makes a difference. Now, I'm not seeing the error messages as before, but I did notice that the JS console is throwing some AMP validation errors:

<img width="529" alt="Screen Shot 2022-12-09 at 2 40 21 PM" src="https://user-images.githubusercontent.com/2230142/206800652-ea5bf214-a784-4c65-b675-0370c481b052.png">

2022-12-09 21:57 UTC, dkoo requested changes
Seeing some new behavior now which needs mitigation.

1. For some reason, on the front-end the block form loads without a selected state. Confirmed that this happens for both new and pre-existing block instances, and both manually-configured and default settings. The block looks like this on initial page load, and doesn't show any tier info until I click on the Monthly or Annual tabs:

<img width="1235" alt="Screen Shot 2022-12-09 at 2 46 11 PM" src="https://user-images.githubusercontent.com/2230142/206801230-fb80f097-c6cf-4878-8dd8-daa22ed11e32.png">

2. When I submit the form, the JS doesn't seem to capture the submit event. On AMP or AMP Plus, the page simply reloads with my form inputs appended to the URL (as in default HTML form submit behavior), and on non-AMP, submitting the form does nothing.

3. If the default **Reader Revenue > Donation** settings are untiered, then "Tiers" still appears as a layout option for Donate blocks, but is unselectable.

2022-12-09 21:58 UTC, dkoo commented on src/blocks/donate/edit/index.tsx
> +	const isTierBasedLayoutEnabled =
I'll retest this once we figure out the form submission issues.

2022-12-09 21:58 UTC, dkoo commented on src/blocks/donate/tiers-based/view.ts
> +			backButton.style.display = 'none';
Thanks! I'm not able to test due to the form submission issues, so leaving unresolved for now.

2022-12-12 22:34 UTC, dkoo commented on src/blocks/donate/tiers-based/view.ts
> +			backButton.style.display = 'none';
The bug affecting back buttons in multiple block instances looks fixed, now—thanks! I still see the tier details after successfully completing a donation. Is this intended? If so, feel free to resolve/close.

<img width="807" alt="Screen Shot 2022-12-12 at 3 31 07 PM" src="https://user-images.githubusercontent.com/2230142/207169692-17ee6774-9d02-4079-99b0-5f3afa3500be.png">

2022-12-12 22:38 UTC, dkoo commented on src/blocks/donate/frontend/class-newspack-blocks-donate-renderer-tiers-based.php
> +					<button class="wpbnbd__tiers__back-button">← <span><?php echo esc_html( __( 'Back', 'newspack-blocks' ) ); ?></span></button>
No longer seeing the validation errors or the error messages. 👍

2022-12-12 22:38 UTC, dkoo commented on src/blocks/donate/edit/index.tsx
> +	const isTierBasedLayoutEnabled =
Working well with WooCommerce checkout 👍

2022-12-12 22:41 UTC, dkoo requested changes
@adekbadek thank you for all of the updates and improvements on this PR. Getting really close now. There are still a couple of minor unresolved threads above, and I found another minor bug which I hadn't noticed before.

On the Stripe-enabled block, if you submit a tiered form by filling out all required fields and hitting "enter" (on the keyboard), the form display goes back to the initial view with all tiers, and the success message isn't visible.

2022-12-14 14:59 UTC, adekbadek commented on src/blocks/donate/tiers-based/view.ts
> +			backButton.style.display = 'none';
That's expected, unless @thomasguillot has a different idea – the payment form disappears after payment, should the tier description disappear, too?

2022-12-14 15:26 UTC, adekbadek commented on src/blocks/donate/edit/TierBasedLayout.tsx
> +									<span>{ amount }</span>
Oh, thanks for catching that! Fixed in 9ac0bc4b42b66d81f855dc82467a6fc5d3fe4678

2022-12-14 19:34 UTC, dkoo commented on src/blocks/donate/edit/TierBasedLayout.tsx
> +									<span>{ amount }</span>
:chefskiss:

2022-12-14 19:35 UTC, dkoo approved these changes
Preapproving since the last remaining thread may not be an issue at all. Feel free to merge after @thomasguillot weighs in on the desired behavior.

2022-12-15 09:42 UTC, thomasguillot commented on src/blocks/donate/tiers-based/view.ts
> +			backButton.style.display = 'none';
I've just realised that I didn't design the success/error messages 🤦‍♂️

I quite like having the tier description here. It gives the user a "summary" of what they purchased.

Here's what I would suggest:

![payment success](https://user-images.githubusercontent.com/177929/207826176-a3f77b19-d39d-47e6-8a17-6ec499af03dc.png)
![payment error](https://user-images.githubusercontent.com/177929/207826181-71776dfc-1041-41db-8493-fca824d41f6d.png)

2022-12-15 10:21 UTC, adekbadek commented on src/blocks/donate/tiers-based/view.ts
> +			backButton.style.display = 'none';
Feels a bit weird that you start you start with the description box and payment UI below it, but then the payment success/error is above the description box. 
Could this be tackled in a separate PR? As it is now, the payment UI with the success/error is just like in the regular streamlined donate block, which is IMO a good starting point.

2022-12-15 10:24 UTC, thomasguillot commented on src/blocks/donate/tiers-based/view.ts
> +			backButton.style.display = 'none';
> Could this be tackled in a separate PR? 

Yes, sure

> Feels a bit weird that you start you start with the description box and payment UI below it, but then the payment success/error is above the description box.

No worries, we can just remove the description box then.

2022-12-15 10:26 UTC, thomasguillot commented on src/blocks/donate/tiers-based/view.ts
> +			backButton.style.display = 'none';
![payment success](https://user-images.githubusercontent.com/177929/207835628-05b05794-5404-443e-a799-515534f77527.png)
![payment error](https://user-images.githubusercontent.com/177929/207835638-00c5ec46-4e74-4527-999a-0f544e685035.png)

2022-12-15 12:10 UTC, adekbadek commented on src/blocks/donate/tiers-based/view.ts
> +			backButton.style.display = 'none';
@dkoo – the post-payment state will be tackled in a separate PR, so this PR is ready for review again.

2022-12-15 12:11 UTC, merged

2022-12-15 12:30 UTC, adekbadek commented on src/blocks/donate/tiers-based/view.ts
> +			backButton.style.display = 'none';
Created issue https://github.com/Automattic/newspack-blocks/issues/1334

2022-12-15 19:20 UTC, dkoo commented on src/blocks/donate/tiers-based/view.ts
> +			backButton.style.display = 'none';
Thanks for the follow-up issue and resolution!