fix: make author block font sizing more specific
Automattic/newspack-blocks pull request #1343
Opened 2023-01-10 20:27 UTC by laurelfulford

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Styles added for the Author Profile block are overriding custom font sizing on paragraph blocks in the editor and on the front-end.

When I originally noticed this I just assumed it was a block editor issue - I wish I had investigated sooner! 

@dkoo and @adekbadek - I'm adding you both as reviews specifically because it looks like [you co-authored the original PR](https://github.com/Automattic/newspack-blocks/pull/947) where this was added. I don't think I've broken anything, but the change to the editor styles -- specifically correcting the containing CSS class so they're getting picked up -- makes me a little nervous, I just want to make sure the other styles there are still working as expected!

See 1203536997639429-as-1203571822380539

### How to test the changes in this Pull Request:

1. Set up a page with few paragraph block with different sizing (both using the theme options and some manually entered values), and at least one Author Profile block. In the Author Profile, make sure the author's job title and employer is displayed.
2. Note that the paragraph blocks with custom font sizes are not previewing correctly.
3. Apply the PR and run `npm run build`.
4. Confirm that the paragraphs are now picking up the correct font sizes. 
5. Confirm that the author profile block is picking up the correct scaling - the Employer should be a bit smaller than the rest of the text, and the text should scale up and down on the front-end and in the editor when you change the Type Scale. 

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2023-01-11 09:53 UTC, adekbadek requested changes

2023-01-11 09:53 UTC, adekbadek commented on src/blocks/author-profile/editor.scss
> +
Instead of these two rules, I'd rather go for an `!important` in the `view.scss` file, to keep the font size setting in on place.

2023-01-11 09:53 UTC, adekbadek commented on src/blocks/author-profile/view.scss
> +	& &__employment {
Is the additional `&` necessary? With an `!important` in this rule (as suggested in the other comment), it's fine with just `&__employment` specificity.

2023-01-11 17:21 UTC, laurelfulford commented on src/blocks/author-profile/editor.scss
> +
That makes sense! I was so fixed on trying to get rid of the first `!important`, I didn't think to circle back after realizing I needed it in the editor styles here. Fixed in [817f2e3](https://github.com/Automattic/newspack-blocks/pull/1343/commits/817f2e3d8898fdd1f03b3a86cf4f5bc2c1c44fff)!

2023-01-11 17:21 UTC, laurelfulford commented on src/blocks/author-profile/view.scss
> +	& &__employment {
Thanks Adam! Should be fixed in [817f2e3](https://github.com/Automattic/newspack-blocks/pull/1343/commits/817f2e3d8898fdd1f03b3a86cf4f5bc2c1c44fff)!

2023-01-12 11:39 UTC, adekbadek approved these changes

2023-01-12 16:32 UTC, laurelfulford commented
Thanks @adekbadek!

2023-01-12 16:32 UTC, merged