feat: product purchase button block
Automattic/newspack-blocks pull request #1421
Opened 2023-04-05 19:22 UTC by miguelpeixe

### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

WIP

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2023-04-10 20:30 UTC, dkoo requested changes
Looking good so far! Some questions:

1. Just to confirm, this PR does not implement any behavior to ungate content if the block is used to purchase the product from the content gate, correct?
2. I wasn't able to see the NYP input field on a product with Name Your Price enabled. Am I missing a setting? Here's my product:

<img width="887" alt="Screen Shot 2023-04-10 at 2 14 09 PM" src="https://user-images.githubusercontent.com/2230142/230990074-9eaed5e0-4882-48ce-bc86-6292c5bd5f0f.png">

And here's what I see on the front-end:

<img width="639" alt="Screen Shot 2023-04-10 at 2 13 55 PM" src="https://user-images.githubusercontent.com/2230142/230990140-84671b5a-11f1-406d-9c65-afa4ac3842a7.png">

3. About the billing fields selection:

> While testing you'll notice that any custom selection of billing fields in the "Reader Revenue" wizard will not apply to custom products used in the block. That's because this custom selection applies only to "Donate" products.

Maybe not in this PR, but I wonder if there's a simplish UI tweak we can make to the field selection UI to enable the field selection for more products? Something like:

**Products affected**

_Apply the billing field selections to the following products:_

- [x] Newspack Donation products
- [ ] Product 1
- [ ] Product 2
- [ ] Product 3

etc.

4. Are the available style options inspired by/taken from the core Button block? If so, we're missing a couple of options: Width Settings (in Settings) and Border Radius (in Styles)

2023-04-11 16:07 UTC, miguelpeixe commented
Thank you for the review, @dkoo!

> Just to confirm, this PR does not implement any behavior to ungate content if the block is used to purchase the product from the content gate, correct?

It implements the same logic applied to the Donate Block or Reader Registration Block:

https://github.com/Automattic/newspack-blocks/blob/fd0b12b9855553fefad63b947e3469a35b14d306/src/modal-checkout/modal.js#L78-L88

The RAS update above triggers the reload in the core plugin [here](https://github.com/Automattic/newspack-plugin/blob/996b2c8ee25f2a5b4f50e0afdb1806482c420726/includes/plugins/class-wc-memberships.php#L442-L465).

What is still missing and should be tackled in a separate PR is a "purchase" event. This way we don't rely on user authentication to refresh the page. A "purchase" detection should be more accurate and ensure that the content "unlocks" for logged-in readers that purchase a membership.

> I wasn't able to see the NYP input field on a product with Name Your Price enabled. Am I missing a setting? Here's my product

Is the NYP custom field not visible? Here's an example:

<img width="292" alt="Captura de Tela 2023-04-11 às 12 53 52" src="https://user-images.githubusercontent.com/820752/231219550-401f0e47-a4e6-4145-90ab-c85c63bbd1a1.png">

Since the block is meant to be just a button, it's not for the reader to name the price.

> Maybe not in this PR, but I wonder if there's a simplish UI tweak we can make to the field selection UI to enable the field selection for more products? Something like:

I was thinking, also for a separate PR, there could be another setting panel that determines the fields for that checkout only. Something like this:

<img width="375" alt="image" src="https://user-images.githubusercontent.com/820752/231221457-08a836ad-3c07-4dfd-adc4-692bcb7d3f99.png">

The tricky aspect, which is the reason why I'd like to tackle it separately, is that it requires separate handling of the selected fields in order to validate the block requirements.

> Are the available style options inspired by/taken from the core Button block? If so, we're missing a couple of options: Width Settings (in Settings) and Border Radius (in Styles)

Yes but not entirely! I didn't notice the border-radius setting was not being applied only by the block json configuration. After some investigation, I discovered I had to enforce it through fd0b12b9855553fefad63b947e3469a35b14d306.

I intentionally left the width settings out because it's more related to the button block relationship with its parent "Buttons" block. The "none", "center", and "full" alignment settings feel more relevant to the block.

2023-04-11 16:41 UTC, miguelpeixe commented on src/blocks/checkout-button/edit.js
> +function ProductControl( props ) {
I originally started working with blocks' [`AutocompleteTokenField`](https://github.com/Automattic/newspack-blocks/blob/3fded2955dbc99ce0560cf4e3ec3882f9c212e46/src/components/autocomplete-tokenfield.js#L20), switched to the plugins' `AutocompleteWithSuggestions` but realized that the logic behind fetching and selecting the data, which is most of the code behind this, would have to be inside the `ProductControl` component.

For that reason and to avoid stacking too many component layers, I decided to go with the more abstract option provided by WP core.

Added a spinner in 3fded2955dbc99ce0560cf4e3ec3882f9c212e46

2023-04-13 17:33 UTC, dkoo requested changes
@miguelpeixe thanks for clarifying the NYP behavior—so it's for the _publisher_ to customize the price for a specific instance of the product checkout, rather than for the reader to name the price of their own membership, right? In that case, the field in the block attributes makes sense and it's working as described. 

However, I'm a bit worried about the default state being $0.00. What if the default state inherited the suggested price from the product, if set? I believe if that value is not set in teh product, there should always be a "subscription price" value we can fall back to as well:

<img width="927" alt="Screen Shot 2023-04-13 at 11 31 07 AM" src="https://user-images.githubusercontent.com/2230142/231838865-3f218a1f-12be-4fc4-a0b4-835bd349c560.png">

That way if someone adds a button pointing to a NYP product and forgets the set the value (like I did) they're not accidentally giving away memberships for free.

Beyond that:

- The new border radius style works well now, thanks!
- Purchasing via the button does remove the gate for me now—maybe my browser was serving cached front-end JS in a previous test.
- I like your proposal for tying the field selection to a specific button. Agree that it should happen in a separate PR.

2023-04-13 18:05 UTC, miguelpeixe commented
> However, I'm a bit worried about the default state being $0.00.

I was not able to reproduce that, the default value for me is the product value. Can you share a screenshot of your block settings panel?

2023-04-13 18:21 UTC, miguelpeixe commented
While testing I noticed a different issue. I was not able to clear the custom price because empty values were being replaced by the product value. Changed the strategy to show the product value as a placeholder. [Empty values should be ignored](https://github.com/Automattic/newspack-blocks/blob/c68bd6d1c7ac802322aed1072c43da547ccb5856/includes/class-modal-checkout.php#L97).

2023-04-17 21:49 UTC, miguelpeixe commented
I was finally able to reproduce the issue with NYP! For some reason my product had its original price preserved even though I changed it to NYP.

Since NYP has a different combination of arguments d1bd6cd92103c5cc7fa8aa77829d736c7479d1d3 implements a more isolated space for it to be configured. The backend was also improved so it protects the defined minimum and maximum thresholds. If left empty, the value to be used is the suggested one:

<img width="288" alt="image" src="https://user-images.githubusercontent.com/820752/232618212-ba97e199-329f-4b38-ab43-0443dafa25e4.png">

2023-04-17 22:10 UTC, miguelpeixe commented
Since NYP allows the product to have a min/max but not necessarily a suggested price, 0366989a90c07e23cea96392a708b6eef03295ed tweaks so it always goes through min/max sanitization regardless of the suggestion.

2023-04-17 22:24 UTC, dkoo approved these changes
After the latest changes, I'm seeing the NYP products using Suggested Price or Minimum/Maximum Price as fallbacks if you don't fill in the field. 👍 Now the only case I get a $0.00 price is if I use a NYP product without a Suggested, Min, or Max price, but I'm not sure what we could do to avoid that given that NYP allows such a product to be created. Maybe setting a failsafe constant of $5 if we can't determine a price from the product settings? It's probably an extreme edge case, so approving.

2023-04-17 22:33 UTC, miguelpeixe commented
Thank you for the review, @dkoo!

When no value is set, the price is set to 0.00, which is to be expected. Having a fallback number in those cases can lead to bad practices: “I’ll just leave everything empty because $5 is the number I wanted anyway”

2023-04-17 22:33 UTC, merged