feat: Add custom taxonomies support (WIP)
Automattic/newspack-blocks pull request #1454
Opened 2023-05-19 22:24 UTC by leogermani

### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2023-05-29 20:52 UTC, miguelpeixe requested changes
Works great! Just some small fixes below.

I noticed you're preventing non-post/page taxonomies in the mix, but the block supports post type selection. I wonder if it should return all public taxonomies and inside the editor decide which options to render based on the selected post types for the block.

2023-05-29 20:52 UTC, miguelpeixe commented on includes/class-newspack-blocks.php
> +			get_taxonomies( [ 'public' => true ] )
Can't the args passed to `get_taxonomies()` include the `_builtin` and `show_in_rest` options? You can also [return objects by setting the second parameter as `true`](https://developer.wordpress.org/reference/functions/get_taxonomies/#parameters) so you don't have to `get_taxonomy()` inside the array map.

2023-05-29 20:52 UTC, miguelpeixe commented on includes/class-newspack-blocks.php
> +		 * @param $custom_taxonomies array Array of custom taxonomies where each taxonomy is an array with slug and label keys.
```suggestion
		 * @param array $custom_taxonomies Array of custom taxonomies where each taxonomy is an array with slug and label keys.
```

Small typo

2023-05-30 14:54 UTC, leogermani commented on includes/class-newspack-blocks.php
> +			get_taxonomies( [ 'public' => true ] )
Thanks, fixed in https://github.com/Automattic/newspack-blocks/pull/1454/commits/ffe1780a5651f457b7f3036f38fca3e174e1639e

2023-05-30 14:55 UTC, leogermani commented
> I wonder if it should return all public taxonomies and inside the editor decide which options to render based on the selected post types for the block

I think this could be a nice improvement, but for now this will cover most of the cases I believe.

2023-06-02 14:06 UTC, miguelpeixe approved these changes
Thank you for the revision! It's working beautifully 🙌

2023-06-02 14:12 UTC, merged