feat: add option for a button after checkout
Automattic/newspack-blocks pull request #1521
Opened 2023-08-30 21:23 UTC by leogermani

### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

![image](https://github.com/Automattic/newspack-blocks/assets/971483/d91ce97a-af7f-47eb-bd8c-5738da373ba7)

Closes # .

### How to test the changes in this Pull Request:

1. Add a checout button to a page
2. Select the option to go to the Referrer after purchase and add a button label
3. Add a link to this page in the site menu
4. Visit an article
5. Go to the page via the menu link
6. Click the button and buy the product
7. Confirm the button shows up in the thank you message and link back to the article you were seeing
8. Edit the button and choose to go to a custom URL
9. repeat the purchase and confirm the button now take you to that URL
10. Edit the button again and choose not to show the button
11. purchase again and confirm there is no button in the thank you message
12.
13.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2023-09-26 10:47 UTC, adekbadek requested changes
When the custom URL field is never set, the button will not be displayed. To reproduce:

1. Insert the checkout button on a page, choose "Go to referrer page" option
2. Observe that the button is not rendered after checkout
3. Back in the editor, choose "Go to a custom URL" option and fill in a URL. Save and edit again, choosing "Go to referrer page". Save again.
4. Observe the button is rendered after checkout

2023-09-26 10:47 UTC, adekbadek commented on src/blocks/checkout-button/edit.js
> +					{ label: __( 'Go to the referrer page', 'newspack-blocks' ), value: 'referrer' },
Suggestion: "previous page" might be more understandable for non-technical people.

2023-09-26 13:39 UTC, miguelpeixe commented
Do you think we should render the button linked to the current page when the URL is not filled?

2023-09-26 15:18 UTC, adekbadek commented
I think that without the URL set, the button should just close the modal. But the issue I'm describing is about something else: according to the testing instructions, if the URL is not filled and "Go to referrer page" is set, the button should be rendered and link to the referrer. And it's not, under conditions described in my review.

2023-09-29 13:37 UTC, miguelpeixe commented on src/blocks/checkout-button/edit.js
> +					{ label: __( 'Go to the referrer page', 'newspack-blocks' ), value: 'referrer' },
Updated in 4325f94b4f83c785cc64bd00c164b8338eae766f

2023-09-29 13:39 UTC, miguelpeixe commented
Ah, sorry for the confusion. I was able to reproduce the issue.

4c514ae272b2f8fe437d9d0b591bec8d9836081d changes the block save to render the URL input if the `afterSuccessBehavior` is set, fixing the issue. I'm not rendering the inputs at all times because it causes a markup mismatch for existing blocks, requiring "attempt block recovery".

2023-10-02 10:15 UTC, adekbadek approved these changes
Left a wording suggestion.

2023-10-02 10:15 UTC, adekbadek commented on src/blocks/checkout-button/edit.js
> +				label={ __( 'Redirect after success', 'newspack-blocks' ) }
Suggestion: this wording makes me think that there will be an automatic page redirection after the purchase is completed. Shouldn't this label inform the user about the post-checkout _button_ instead?

2023-10-03 14:34 UTC, miguelpeixe commented on src/blocks/checkout-button/edit.js
> +				label={ __( 'Redirect after success', 'newspack-blocks' ) }
Updated in 518e0c32d3b971b4ad144560a2f457a71423f4d6

2023-10-03 14:36 UTC, merged