Modal checkout – post-checkout newsletter signup
Automattic/newspack-blocks pull request #1561
Opened 2023-10-18 11:13 UTC by adekbadek

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Adds post-checkout newsletter signup options:

<img width="618" alt="image" src="https://github.com/Automattic/newspack-blocks/assets/7383192/18f0534c-d275-4b27-a2ba-6cfa6a4306c0">

<img width="617" alt="image" src="https://github.com/Automattic/newspack-blocks/assets/7383192/de21738b-f3f4-476a-8965-cbf19219a77b">

### How to test the changes in this Pull Request:

1. Ensure that the Newsletters provider is configured and some lists are active in Engagement wizard -> Newsletters
1. With "Newspack" set as the Reader Revenue platform, make a donation using the checkout modal
2. Observe that after the checkout is successful, the chosen newsletter lists are presented
3. Select some of them and click "Continue", observe a success message
4. Verify that the email used has been added to the list(s)
5. Set a `NEWSPACK_DISABLE_POST_CHECKOUT_NEWSLETTER_SIGNUP` environment variable to `true` and observe that now the signup lists are not displayed after the checkout 

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2023-10-18 18:14 UTC, miguelpeixe requested changes

2023-10-18 18:14 UTC, miguelpeixe commented on src/modal-checkout/modal.js
> +		} );
This change breaks the CSS for the variation selection modal:

| Before | After |
| --- | --- |
| <img width="653" alt="image" src="https://github.com/Automattic/newspack-blocks/assets/820752/da9bc301-a44b-4553-8f7b-00532c6e6384"> |  <img width="662" alt="image" src="https://github.com/Automattic/newspack-blocks/assets/820752/43704b4c-f18f-4b6d-b366-9543e072df2f"> |

2023-10-19 11:53 UTC, adekbadek commented on src/modal-checkout/modal.js
> +		} );
Thanks for catching that! Fixed in aa52d8f

2023-10-19 11:56 UTC, adekbadek commented on includes/class-modal-checkout.php
> +	}
Done in e19098fa4ff383bcaa7e63091885349440706b58

2023-10-19 16:11 UTC, miguelpeixe requested changes
Thank you for the changes!

It needs rebasing and switch the source of the lists from `Newspack_Newsletters_Subscription::get_lists()` to `Newspack\Reader_Activation::get_registration_newsletter_lists()`. Note that the new source includes a `checked` property that should be used for setting the initial checkbox state.

2023-10-19 20:32 UTC, miguelpeixe requested changes
After donating and selecting the lists to subscribe to, I'm redirected to a blank page and the subscription is not processed:

https://github.com/Automattic/newspack-blocks/assets/820752/1dcc43ea-21ab-4d80-8fda-f76652e5d82a

This is due to the `thankyou.php` template bailing on the `$is_valid` check because the `$order` is not passed on the subscription form submission.

2023-10-20 13:04 UTC, adekbadek commented
Whoops, good catch! Fixed in 22dc58fa4afb1a79bcd2a0501d30fa3ad393a06f

2023-10-20 13:27 UTC, miguelpeixe approved these changes
Thank you for revising! 🎉

2023-10-20 14:39 UTC, merged