feat: add button-after-success feature to Donate block
Automattic/newspack-blocks pull request #1571
Opened 2023-10-24 10:56 UTC by adekbadek

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Implements https://github.com/Automattic/newspack-blocks/pull/1521/ for the Donate block. 

### How to test the changes in this Pull Request:

1. Switch `newspack-plugin` to `feat/donate-post-checkout-button` 
2. Add a Donate block to a page, configure it to display a button in the "After Purchase" sidebar settings panel
3. Complete a transaction, observe the button is displayed (as in https://github.com/Automattic/newspack-blocks/pull/1521/)

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2023-10-26 10:44 UTC, dkoo requested changes
Almost there, but I ran into an instance where the after-checkout modal is blank after clicking "Continue":

<img width="818" alt="Screenshot 2023-10-26 at 4 41 35 AM" src="https://github.com/Automattic/newspack-blocks/assets/2230142/7c8f2672-fb1c-49d9-9fe2-7e41e6ce7cd5">

To replicate, create a Checkout Button block pointing to a simple non-subscription product, complete the purchase, and then deselect all newsletter options before clicking "Continue". The final screen will be blank as above if not opting into any newsletter option.

2023-10-26 10:44 UTC, dkoo commented on includes/class-modal-checkout.php
> +		$url          = ! empty( $_REQUEST['after_success_url'] ) ? sanitize_text_field( urldecode( wp_unslash( $_REQUEST['after_success_url'] ) ) ) : ''; // phpcs:ignore WordPress.Security.ValidatedSaniti
Nit: should this be `esc_url`?

```suggestion
		$url          = ! empty( $_REQUEST['after_success_url'] ) ? esc_url( urldecode( wp_unslash( $_REQUEST['after_success_url'] ) ) ) : ''; // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized
```

2023-10-26 14:21 UTC, adekbadek commented on includes/class-modal-checkout.php
> +		$url          = ! empty( $_REQUEST['after_success_url'] ) ? sanitize_text_field( urldecode( wp_unslash( $_REQUEST['after_success_url'] ) ) ) : ''; // phpcs:ignore WordPress.Security.ValidatedSaniti
Actually escaping is done in the output code a few lines below, so that's redundant. Changed in a19bd5a265c41e1aa17e801e0bace8e228281a86

2023-10-26 14:24 UTC, adekbadek commented
> The final screen will be blank as above if not opting into any newsletter option.

Thanks for catching that! Ideally the newsletter signup form should be validated (`required` field), but there's no pure HTML solution for this, so this will need a bit of JS. In the interest of time I'll tackle that in a separate PR.

2023-10-27 11:03 UTC, dkoo commented
> Ideally the newsletter signup form should be validated (required field)

I don't agree, if I'm understanding you correctly. Readers should be able to continue without selecting any newsletter options, right?

2023-10-27 11:11 UTC, dkoo requested changes
If no lists are selected, we now show a simple error message:

<img width="747" alt="Screenshot 2023-10-27 at 5 10 22 AM" src="https://github.com/Automattic/newspack-blocks/assets/2230142/7cdca9e9-f05d-487e-8ba9-b36a5745775a">

Instead, I think we should show the usual success message. We cannot require readers to opt into newsletters in this scenario, and must provide a way for them to proceed without opt-in.

2023-10-30 09:51 UTC, adekbadek commented
Done in d94d8ebd33db9bbdc2ae578207ffe39fe904a5d4. If no lists were selected "Signup successfull!" heading will be omitted.

2023-10-30 19:31 UTC, dkoo approved these changes
This works for me, for now! Thanks for the latest updates.

2023-10-30 19:44 UTC, merged