feat(modal-checkout): support shipping
Automattic/newspack-blocks pull request #1581
Opened 2023-11-03 23:07 UTC by dkoo

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Adds support for shipping info during the modal checkout flow, to bring our modal checkout to closer parity with the default Woo checkout flow.

### How to test the changes in this Pull Request:

1. Check out this branch.
2. In WP admin > WooCommerce > Settings > Shipping, add at least one shipping zone and one shipping method to the zone (preferably one that costs some amount of money).
3. In Reader Revenue > Donations enable all of the billing fields.
4. Publish at least one product that is NOT virtual. Ensure that it has some available inventory.
5. Create a Checkout Button block pointing to your non-virtual product.
6. As a new reader, purchase the product using the Checkout Button. Confirm that the modal now shows an order summary that shows the total cost of the purchase including shipping fees, and a toggle to ship to a different address.

<img width="619" alt="Screenshot 2023-11-03 at 9 27 39 AM" src="https://github.com/Automattic/newspack-blocks/assets/2230142/44fb8561-ab3e-450c-81d7-0cf4b8946ac0">

7. Complete the purchase without touching the toggle. In WP admin > Users, find the customer's WP user account and confirm that the shipping address fields are automatically filled to match the billing address fields.
8. In another new session, purchase the same product again. This time toggle ON the "ship to a different address?" option and fill in a different address in the fields that are unhidden. Make sure you fill in the optional order notes.
9. On the payment modal screen, confirm that the separate shipping address is shown underneath the billing address, and that you can go back to edit them (unfortunately the "ship to a different address?" option doesn't seem to be saved if you go back to edit, but the address fields themselves are, so this doesn't seem like a blocker to me).
10. Also go to the order for this last purchase and confirm that the "Customer provided note" field shows the text you entered into the order notes field during checkout.
11. Complete the transaction. In WP admin > Users, find the customer's WP user account and confirm that the shipping address fields are filled in and match the address you inputted in the second purchase.
12. Check out https://github.com/Automattic/newspack-plugin/pull/2733.
13. Navigate to or log into My Account. Confirm that there's an "Addresses" menu item and that clicking on it allows you to see/edit the billing and shipping address info you've entered previously.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2023-11-07 15:13 UTC, leogermani requested changes
I'm getting a "First name is a required field" error when trying to make the purchase. The checkout works fine for donation products...

![Captura de tela de 2023-11-07 12-03-07](https://github.com/Automattic/newspack-blocks/assets/971483/8cc363f7-59bc-47da-bbb8-205ada4abae2)

I also see this table summary at the top. Not sure if that's expected or if this might be related to some other option in my site (I remember seeing this when playing with taxes settings)

![Captura de tela de 2023-11-07 12-07-15](https://github.com/Automattic/newspack-blocks/assets/971483/09f12c80-6cbc-4141-a209-d6ba4246e810)

2023-11-14 00:32 UTC, dkoo commented
> I'm getting a "First name is a required field" error when trying to make the purchase. The checkout works fine for donation products...

@leogermani what billing fields do you have enabled for your site in Reader Revenue > Donations?

2023-11-14 00:34 UTC, leogermani commented
> > I'm getting a "First name is a required field" error when trying to make the purchase. The checkout works fine for donation products...
> 
> @leogermani what billing fields do you have enabled for your site in Reader Revenue > Donations?

All of them

2023-11-20 23:10 UTC, dkoo commented
> I'm getting a "First name is a required field" error when trying to make the purchase. The checkout works fine for donation products...

I'm not able to replicate this—does it keep happening if you try in a fresh session? If so, could you provide steps to replicate?

> I also see this table summary at the top. Not sure if that's expected or if this might be related to some other option in my site (I remember seeing this when playing with taxes settings)

Yes, this is intentional because shipping usually involves some kind of shipping fee (configurable for each shipping method/zone). The summary will show the subtotal + any applicable shipping fees. I think it's worth showing the summary even if the site offers free shipping, so that the customer knows exactly what the order total will be.

<img width="535" alt="Screenshot 2023-11-20 at 4 07 58 PM" src="https://github.com/Automattic/newspack-blocks/assets/2230142/c29c5f6c-767d-47b7-b963-ef84e73d5a35">

2023-11-20 23:11 UTC, dkoo commented
Note: rebased to reflect the new project-level scope.

2023-11-22 21:06 UTC, dkoo commented
@leogermani dda1ef0 fixes the "required fields" validation to only require shipping fields if the "ship to a different address" option is enabled.

2023-11-24 14:30 UTC, leogermani requested changes
When I click the checkout button, I'm now always taken to the second step of the checkout modal, as if I had already entered my billing and shipping info (like when I'm logged in), but it's all empty. I can click Edit and then start from scratch. Then it works.

I think this is why I'm seeing this warning:

```
foreach() argument must be of type array|object, bool given in /newspack-repos/newspack-blocks/src/modal-checkout/templates/checkout-form.php on line 140
```

There's also a Warning of `$type` being undefined. I left a comment in the code.


> Confirm that there's an "Addresses" menu item

There is not. And there's a "Billing" item with a button that takes me to Stripe. Doesn't look right.

![image](https://github.com/Automattic/newspack-blocks/assets/971483/0541d5d5-99f9-43e0-a2c8-b58fea3d8ca0)

2023-11-24 14:30 UTC, leogermani commented on includes/class-modal-checkout.php
> +		$checkout_fields = [ 'billing' => $checkout->get_checkout_fields( $type ) ];
`$type` is undefined here

2023-12-01 20:31 UTC, dkoo commented on includes/class-modal-checkout.php
> +		$checkout_fields = [ 'billing' => $checkout->get_checkout_fields( $type ) ];
Fixed in b4e7f28, but I'm thinking we should hold on this until Miguel finishes the refactor to a single template for the checkout modal since that might cause a lot of this changeset to be revisited.

2023-12-09 01:59 UTC, dkoo commented
Closing this in favor of #1626.

2023-12-09 01:59 UTC, closed without merging