feat(modal-checkout): update "place order" text to "donate now"
Automattic/newspack-blocks pull request #1591
Opened 2023-11-09 15:50 UTC by adekbadek

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Updates the "Place order" text in modal checkout to "Donate now".

⚠️  This is an alpha-hotfix, merging to `alpha`.

### How to test the changes in this Pull Request:

1. Test with a one-time and recurring donation via modal checkout – the CTA on the second step should always say "Donate now"
2. Use the regular checkout, confirm the corresponding button says "Place order" for regular items and "Sign up now" for subscription items

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2023-11-09 20:21 UTC, miguelpeixe requested changes

2023-11-09 20:21 UTC, miguelpeixe commented on includes/class-modal-checkout.php
> +		return __( 'Donate now', 'newspack-blocks' );
The modal checkout is also used for other products, especially membership subscriptions. This change should only impact donation carts.

2023-11-09 23:48 UTC, dkoo commented on includes/class-modal-checkout.php
> +		return __( 'Donate now', 'newspack-blocks' );
Jumping in this is an urgent request. 00daac9 adds the condition so that the "Donate Now" text is only displayed for donation transactions.

2023-11-10 11:23 UTC, adekbadek commented on includes/class-modal-checkout.php
> +		return __( 'Donate now', 'newspack-blocks' );
Thanks Derrick!

2023-11-10 16:26 UTC, merged