feat: redesign modal checkout
Automattic/newspack-blocks pull request #1602
Opened 2023-11-22 19:24 UTC by miguelpeixe

### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2023-11-22 22:57 UTC, dkoo commented
@miguelpeixe let's base redesign work from the [`epic/ras-acc` branch](https://github.com/Automattic/newspack-blocks/tree/epic/ras-acc) so we can control the release.

2023-12-18 23:23 UTC, dkoo commented
Getting started with testing and reviewing this (finally! sorry for the delay). But I have an answer to one of your questions!

 > Linter is accusing a CSS kebab-case issue even though the line has /* stylelint-disable-line */. Not sure how to deal with this.

I ran into this same issue on #1626. The fix is to put both CSS selectors on the same line, like [this](https://github.com/Automattic/newspack-blocks/pull/1626/files#diff-93359786372d1c41af813037af697f33c6a6da8d4a48622a3c18d8e6f26f1cd7).

```css
#checkout_continue, #place_order { /* stylelint-disable-line */
```

2023-12-19 00:28 UTC, dkoo requested changes
I went through all testing steps and everything is mostly working! 🙌 

Before I do a more thorough code review I ran into a couple of minor things so far:

- When checking the "I’d like to cover the 3.6% transaction fee" option, the transaction total is updated at the top of the modal, but not in the Transaction Details summary's total (the order amount is correct once placed, though).
- If taxes are not enabled and no coupons are applied, when purchasing a shippable product with either multiple available shipping methods and/or only paid shipping methods, the Transaction Details summary is not shown. This results in a strange modal state where the totals don't match up (this _should_ be fixed by #1626, though, so maybe there's nothing needed for this PR):

<img width="643" alt="Screenshot 2023-12-18 at 5 28 32 PM" src="https://github.com/Automattic/newspack-blocks/assets/2230142/90403914-8035-4dde-9b0a-c7deefc53be3">


More testing and a line-by-line code review to come!

2023-12-19 13:29 UTC, miguelpeixe commented
Thank you for taking this review, @dkoo!

> When checking the "I’d like to cover the 3.6% transaction fee" option, the transaction total is updated at the top of the modal, but not in the Transaction Details summary's total (the order amount is correct once placed, though).

Fixed in the https://github.com/Automattic/newspack-plugin/pull/2805 (https://github.com/Automattic/newspack-plugin/pull/2805/commits/6ff7dd04fba6ab130fba0bdf443bd03bf31e4219).

> If taxes are not enabled and no coupons are applied, when purchasing a shippable product with either multiple available shipping methods and/or only paid shipping methods, the Transaction Details summary is not shown.

I didn't find the mentioned PR tweak the rules for when to render the order review table, so I added in e00793fe9f5b991c7b8014e2b2724e72f0d69a2b

> I ran into this same issue on https://github.com/Automattic/newspack-blocks/pull/1626. The fix is to put both CSS selectors on the same line, like [this](https://github.com/Automattic/newspack-blocks/pull/1626/files#diff-93359786372d1c41af813037af697f33c6a6da8d4a48622a3c18d8e6f26f1cd7).

😌 updated in fc748a28f2c435d38546d6e2c161ef112b20bf48

2023-12-19 14:21 UTC, miguelpeixe commented
Update regarding the cover fee issue: https://github.com/Automattic/newspack-plugin/pull/2805#issuecomment-1862850079

2023-12-19 19:42 UTC, dkoo commented
> The mentioned PR doesn't seem to tweak the rules for when to render the order review table, so I added in https://github.com/Automattic/newspack-blocks/commit/e00793fe9f5b991c7b8014e2b2724e72f0d69a2b

It does: https://github.com/Automattic/newspack-blocks/pull/1626/files#diff-74a92f16c32d2a94751337aaff7d24de10881675f81809bae9d09e79cc47e10eR645

But it uses `$cart->needs_shipping_address()` instead of just `$cart->needs_shipping()`, so maybe it would need to be tweaked.

2023-12-19 19:48 UTC, miguelpeixe commented
Ah, I missed that. I think my brain was looking for a one-liner 😅 . I'll revert my change and allow your PR to handle those requirements.

2023-12-20 00:04 UTC, dkoo approved these changes
Looking good! Issues and solutions in separate PRs noted. I think this is a fantastic foundation for the redesigned modal checkout experience, and it lays the foundation for a lot of great work to come!

Tested with one-time donations, recurring donations, non-donation purchases (one-time and subscriptions), variable subscriptions, and shippable products. Couldn't break it.

2023-12-20 17:35 UTC, miguelpeixe commented on includes/class-modal-checkout.php
> +						<?php echo apply_filters( 'woocommerce_cart_item_subtotal', $cart->get_product_subtotal( $_product, $cart_item['quantity'] ), $cart_item, $cart_item_key ); // phpcs:ignore WordPress.Security.Es
> Maybe a simple way to deal with this is to add a class for the donation checkout container, and add display: none to .subscription-details class name?

Good idea! I believe we should tackle this separately in the plugin's Donation class. I want to avoid adding donation-specific logic here as much as we can for better maintainability.

There's more to this line that I'd like to discuss. It's currently not providing the total order value, only the product item price. I think we should change that so it can account for additional values (coupon, fees (https://github.com/Automattic/newspack-plugin/pull/2820) and taxes)

2023-12-20 17:40 UTC, merged

2023-12-20 18:20 UTC, dkoo commented on includes/class-modal-checkout.php
> +						<?php echo apply_filters( 'woocommerce_cart_item_subtotal', $cart->get_product_subtotal( $_product, $cart_item['quantity'] ), $cart_item, $cart_item_key ); // phpcs:ignore WordPress.Security.Es
Very cool—love the idea of using cart fees to handle the transaction fees separately!