Feat/support subscriptions gifting
Automattic/newspack-blocks pull request #1603
Opened 2023-11-22 22:31 UTC by dkoo

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR adds basic support for the [WooCommerce Subscriptions Gifting extension](https://github.com/woocommerce/woocommerce-subscriptions-gifting) to our modal checkout flow. This is a prerequisite for the redesign work currently underway for certain RAS reader flows.

As part of that project, we're moving towards consolidating our two-screen custom modal template into a single screen that contains all WooCommerce checkout elements on one page, using JS to control interaction states and visibility of elements during the checkout flow. Because of this plan, this PR only ensures that WooCommerce Subscriptions Gifting fields are able to appear in the checkout flow and function as expected. It does not implement new designs or element placement within the modal according to the new designs, which will come in a future PR. It does, however, implement the new default copy ("this donation is a gift" or "this transaction is a gift" for non-donations) as this isn't dependent on the redesign.

Because our theme and checkout modal are not designed to accommodate the WooCommerce Subscriptions Gifting fields, this PR also forces the fields to appear only during checkout, not in the cart as the extension normally behaves. Because the extension doesn't provide any filters to control where the fields appear, the PR does it in a kind of hacky way by adding a blank template that overwrites the plugin's template where we don't want them to appear.

### How to test the changes in this Pull Request:

1. Install and activate the [WooCommerce Subscriptions Gifting extension](https://github.com/woocommerce/woocommerce-subscriptions-gifting)
2. On `epic/ras-acc`, visit the Shop page (usually at the `/shop` permalink) and add a subscription product to the cart. Observe that the Gifting fields appear here unstyled when you add an item to the cart:

<img width="810" alt="Screenshot 2023-11-22 at 3 24 20 PM" src="https://github.com/Automattic/newspack-blocks/assets/2230142/12aca158-6da5-4fc5-8dfd-164da3441ef5">

4. On the same branch, also start a new recurring transaction from the Donate or Checkout Button block. Observe the Gifting fields appearing in an unlikely spot in the modal checkout template. Also observe that if you fill out the fields and complete the transaction, the gifting options are not added to the transaction (rendering the plugin useless for transactions made via modal checkout).

<img width="660" alt="Screenshot 2023-11-22 at 3 27 01 PM" src="https://github.com/Automattic/newspack-blocks/assets/2230142/045e0bc5-8fc6-47d3-9dd1-cc1396f3b613">

5. Check out this branch and repeat steps 2 and 3. This time confirm that the Gifting fields do not appear in the Cart view or the first screen of the modal. 
6. Confirm that the Gifting fields do appear on the second screen of the modal, under the Billing Details section.

<img width="607" alt="Screenshot 2023-11-22 at 3 16 07 PM" src="https://github.com/Automattic/newspack-blocks/assets/2230142/a148e14d-e18c-4869-86a2-dff82d14047d">

7. Check the box and fill in an email address, then complete the transaction. Confirm that the gifting options are applied (the subscription is listed in the Subscriptions admin page as "purchased by [buyer] for [recipient]", and a notification email is sent to the recipient).

<img width="516" alt="Screenshot 2023-11-22 at 3 30 01 PM" src="https://github.com/Automattic/newspack-blocks/assets/2230142/8273d2b1-23bb-4998-9f61-a3f9d06a61d5">
<img width="629" alt="Screenshot 2023-11-22 at 3 30 38 PM" src="https://github.com/Automattic/newspack-blocks/assets/2230142/4ff2a6e7-7e69-4f04-b469-04801e4f9eee">

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2023-11-23 09:31 UTC, adekbadek requested changes
On the frontend side it worked as expected, but the resulting subscription is not marked as being gifted in the admin:

<img width="523" alt="image" src="https://github.com/Automattic/newspack-blocks/assets/7383192/ac191025-d39f-4ca2-955e-aa1d7ec993b9">

2023-11-23 09:31 UTC, adekbadek commented on includes/class-modal-checkout.php
> +					self::is_modal_checkout() &&
Nit: the whole if statement could be moved below the `if ( ! self::is_modal_checkout() )` statement below, so this condition would not be necessary, and it would be clear that any modifications to the templates are only done in the context of the modal checkout.

2023-11-23 09:31 UTC, adekbadek commented on includes/class-modal-checkout.php
> +			$located = NEWSPACK_BLOCKS__PLUGIN_DIR . 'src/modal-checkout/templates/html-add-recipient.php';
As @miguelpeixe pointed out in  https://github.com/Automattic/newspack-blocks/pull/1601#discussion_r1402090229, you don't need the template file – (empty) markup can be returned from  this function.

2023-11-23 13:12 UTC, adekbadek commented on includes/class-modal-checkout.php
> +			$located = NEWSPACK_BLOCKS__PLUGIN_DIR . 'src/modal-checkout/templates/html-add-recipient.php';
Oops, scratch that. Just noticed that this solution causes a PHP Notice to be logged: 

```
PHP Notice:  Function wc_get_template was called incorrectly.
```

Nevermind, and I'll redo my change.

2023-12-01 02:54 UTC, dkoo commented
> On the frontend side it worked as expected, but the resulting subscription is not marked as being gifted in the admin:

Hmm, after buying a lot of gift subscriptions, I'm seeing inconsistent results. I think there's some kind of race condition happening here. This PR may be better to hold and revisit once we have the single-screen modal checkout template.

2023-12-01 02:55 UTC, dkoo commented on includes/class-modal-checkout.php
> +			$located = NEWSPACK_BLOCKS__PLUGIN_DIR . 'src/modal-checkout/templates/html-add-recipient.php';
30b20bc prefixes the name of the empty template with `empty-` to make its purpose a bit clearer.

2024-01-04 19:55 UTC, dkoo commented
@adekbadek @miguelpeixe this has been fixed and the testing instructions updated. Please test and review again!

2024-01-05 14:06 UTC, adekbadek approved these changes
Works as described!

2024-01-05 16:31 UTC, merged