feat: improve performance of modal checkout
Automattic/newspack-blocks pull request #1607
Opened 2023-11-27 15:03 UTC by adekbadek

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Improves the performance of the modal checkout by skipping unnecessary markup. 

It also fixes a PHP Notice caused by changes in #1601. 

### How to test the changes in this Pull Request:

1. On `master`, start a new session (or clear the cookies)
2. Trigger the modal checkout, copy the URL of the modal's iframe and visit it directly*
3. Observe the issues (deactivate Perfmatters if active, because it will make it more difficult to inspect):
    1. [Complianz](https://wordpress.org/plugins/complianz-gdpr/) cookie banner is displayed in the iframe
    2. reCaptcha badge, too
    3. Newspack Ads' JS is loaded (if configured) 
    4. Newspack print styles are loaded
    5. GA is loaded 
    6. If Jetpack "WooCommerce Analytics" module is active**, a whole bunch of React and Redux JS is loaded
    7. WP mediaelement scripts and styles are loaded
    8. PHP Notice is logged, notifying that "Function wc_get_template was called incorrectly"
4. Switch to this branch, and to https://github.com/Automattic/newspack-plugin/pull/2768 and https://github.com/Automattic/newspack-theme/pull/2207 on Plugin and Theme repos
5. Observe errors gone 💨
6. Complete a transaction using the modal checkout, verify that it works as before

\* `copy(document.querySelector('iframe[name="newspack_modal_checkout"]').contentWindow.location.href)` in the JS console
\** `/wp-admin/admin.php?page=jetpack_modules`

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2023-11-28 15:37 UTC, miguelpeixe requested changes
Works well! Should be ok to merge after feedback on the reCAPTCHA badge visibility and the https://github.com/Automattic/newspack-plugin/pull/2768 and https://github.com/Automattic/newspack-theme/pull/2207 are approved.

2023-11-28 15:37 UTC, miguelpeixe commented on src/modal-checkout/checkout.scss
> +}
According to [reCAPTCHA's FAQ](https://developers.google.com/recaptcha/docs/faq#id-like-to-hide-the-recaptcha-badge.-what-is-allowed), the badge visibility should be managed through `visibility: hidden;` and only if the form includes the following:

```
This site is protected by reCAPTCHA and the Google
    <a href="https://policies.google.com/privacy">Privacy Policy</a> and
    <a href="https://policies.google.com/terms">Terms of Service</a> apply.
```

The modal redesign is taking that into account and we should have a good placement for the required text soon. What do you think of leaving this change to the redesign?

More on this in the comments of 1205234045751551-as-1205933702651188

2023-11-29 10:08 UTC, adekbadek commented on src/modal-checkout/checkout.scss
> +}
Ok! If that's covered in future work, it does not have to be included here.

2023-11-29 14:42 UTC, miguelpeixe approved these changes

2023-11-30 07:32 UTC, merged