feat(modal-checkout): redesign variation selection
Automattic/newspack-blocks pull request #1643
Opened 2024-01-15 15:53 UTC by miguelpeixe

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

1205234045751551-as-1206185519218321

Redesign the modal checkout's variation selection according to 1205234045751551-as-1206122717080146.

The styles should still be updated to integrate with https://github.com/Automattic/newspack-plugin/pull/2810

<img width="654" alt="image" src="https://github.com/Automattic/newspack-blocks/assets/820752/83efcc25-348a-4c48-92a7-a9df2a5a119f">

<img width="624" alt="image" src="https://github.com/Automattic/newspack-blocks/assets/820752/9744b929-609e-4cc0-bd4d-e43c92bdecb1">

### How to test the changes in this Pull Request:

1. Checkout this branch and https://github.com/Automattic/newspack-plugin/tree/epic/ras-acc
2. Create 2 variable subscription products in Woo, one with 4 variations, other with 2, as represented in the images above
3. Draft a page and add a Checkout Button block each of the created products
4. Make sure "Allow the reader to select the variation before checkout." in the block setting is toggled on, so the variation selection becomes available
5. Visit the page, click the button for the 4 variations, and confirm it renders in 3 columns as above
6. Click "Purchase" on any variation and confirm the modal checkout renders for the selected variation
7. Exit the modal checkout, click the button for the 2 variations, and confirm it renders in 2 columns as above
8. Click "Purchase" and confirm the modal checkout renders as expected

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2024-01-16 00:37 UTC, dkoo approved these changes
Works well and looks great! Just one very minor edge case. Not sure if we can do much about this in a way that looks good, but if the price string is fairly long, it can easily exceed the width of the container in the three-column layout.

<img width="687" alt="Screenshot 2024-01-15 at 5 32 44 PM" src="https://github.com/Automattic/newspack-blocks/assets/2230142/789c6556-fdfa-4b8c-85e2-04acc6fc3aae">

I'll consider this non-blocking as I think it's pretty unlikely to happen in live sites. The costliest product I've seen is about $2,500.00.

2024-01-16 13:47 UTC, miguelpeixe commented
Good catch! It slipped me that @kevinzweerink requested to cut off the `.00` cents when the price is over 3 digits. Updated in 3c0981ad2b24be15b730e74c9db2917f4b2d5479.

2024-01-16 21:08 UTC, dkoo requested changes
> Good catch! It slipped me that @kevinzweerink requested to cut off the .00 cents when the price is 3+ digits. Updated in https://github.com/Automattic/newspack-blocks/commit/3c0981ad2b24be15b730e74c9db2917f4b2d5479.

Small nit with this change below.

2024-01-16 21:42 UTC, miguelpeixe commented on includes/class-modal-checkout.php
> +		return $price_string;
Good call on using the decimal separator!

I'd rather keep treating this as a string since it's no longer a number at this point. Converting back to a number means re-applying the string logic from Woo for the separators and potentially other things, which is more than we should be doing here IMO.

2024-01-16 21:55 UTC, miguelpeixe commented on includes/class-modal-checkout.php
> +		return $price_string;
Updated in 062284090c543f70134ddbdee9831a27448f0470

2024-01-19 23:20 UTC, dkoo approved these changes
Works now! Thanks for the update.

<img width="640" alt="Screenshot 2024-01-19 at 4 20 17 PM" src="https://github.com/Automattic/newspack-blocks/assets/2230142/c797f244-6cfe-4166-ab0a-334307ec4365">

2024-01-19 23:38 UTC, merged