Fix/optional nyp stripe gateway
Automattic/newspack-blocks pull request #1645
Opened 2024-01-19 21:00 UTC by dkoo

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Makes Stripe Gateway and Name Your Price extensions optional.

### How to test the changes in this Pull Request:

See https://github.com/Automattic/newspack-plugin/pull/2866 for testing instructions.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2024-01-25 20:59 UTC, miguelpeixe requested changes
The fallback is working great! I have a few comments inline.

Non-blocking, but I miss having a greyed-out style here:

<img width="280" alt="image" src="https://github.com/Automattic/newspack-blocks/assets/820752/a7ba73ba-faa2-45d7-bf35-455b4ce88939">

Even with the message, I still want to click the button.

2024-01-25 20:59 UTC, miguelpeixe commented on src/blocks/donate/frontend/class-newspack-blocks-donate-renderer-base.php
> +		$is_manual = Newspack_Blocks::can_use_name_your_price() && $attributes['manual'];
This line is throwing `Warning: Undefined array key "manual"` because it's not an attribute that has a default value. It can be undefined.

2024-01-25 20:59 UTC, miguelpeixe commented on src/blocks/donate/frontend/class-newspack-blocks-donate-renderer-base.php
> +		if ( $is_manual ?? false ) {
```suggestion
		if ( $is_manual ) {
```

The `?? false` is superfluous if we're not checking if `manual` is set in the associative array.

2024-01-26 18:34 UTC, dkoo commented on src/blocks/donate/frontend/class-newspack-blocks-donate-renderer-base.php
> +		$is_manual = Newspack_Blocks::can_use_name_your_price() && $attributes['manual'];
Fixed in a985f00

2024-01-29 20:30 UTC, chickenn00dle reviewed
Nice work @dkoo!

Tested and everything works as expected. I left a few comments in the code, mostly nitpicks that can be ignored, but one question regarding translations that should be answered before moving forward with this.

2024-01-29 20:30 UTC, chickenn00dle commented on src/blocks/donate/edit/FrequencyBasedLayout.tsx
> +												getFrequencyLabel( frequencySlug ) }
I wonder if this might cause an issue for languages where the amount should not precede the per month/year text? Might be a better idea to have the `getFrequencyLabel` method accept the amount and return a translated string which includes the amount in it?

2024-01-29 20:30 UTC, chickenn00dle commented on src/blocks/donate/frontend/class-newspack-blocks-donate-renderer-base.php
> +	public static function get_frequency_label( $frequency_slug, $hide_once_label = false ) {
Same comment as above re including amount in the translations here

2024-01-29 20:30 UTC, chickenn00dle commented on src/blocks/donate/frontend/class-newspack-blocks-donate-renderer-base.php
> +		$is_manual = Newspack_Blocks::can_use_name_your_price() && ! empty( $attributes['manual'] );
nitpick: same comment re creating variable only used in one place

2024-01-29 20:30 UTC, chickenn00dle commented on includes/class-modal-checkout.php
> +		$is_product_nyp = \Newspack_Blocks::can_use_name_your_price() ? \WC_Name_Your_Price_Helpers::is_nyp( $product_id ) : false;
nitpick: is it necessary to create a variable here considering this is only used in one place?

2024-01-30 00:39 UTC, dkoo commented on src/blocks/donate/edit/FrequencyBasedLayout.tsx
> +												getFrequencyLabel( frequencySlug ) }
That's a good point, although I had some trouble conceptualizing how we'd translate such a string when it has to include HTML tags for styling, too. 3701068 is my best attempt—how's it look?

2024-01-30 00:40 UTC, dkoo commented on src/blocks/donate/frontend/class-newspack-blocks-donate-renderer-base.php
> +		$is_manual = Newspack_Blocks::can_use_name_your_price() && ! empty( $attributes['manual'] );
Nope, not necessary—updated in 42e145b.

2024-01-30 00:40 UTC, dkoo commented on includes/class-modal-checkout.php
> +		$is_product_nyp = \Newspack_Blocks::can_use_name_your_price() ? \WC_Name_Your_Price_Helpers::is_nyp( $product_id ) : false;
Nope, not necessary—updated in 42e145b.

2024-01-30 00:45 UTC, dkoo commented on src/blocks/donate/frontend/class-newspack-blocks-donate-renderer-base.php
> +	public static function get_frequency_label( $frequency_slug, $hide_once_label = false ) {
See https://github.com/Automattic/newspack-blocks/pull/1645#discussion_r1470424015

2024-01-30 15:57 UTC, chickenn00dle commented on src/blocks/donate/frontend/class-newspack-blocks-donate-renderer-base.php
> +			'<h3 class="wpbnbd__tiers__amount__number">' . $currency_symbol . $amount . '</h3>',
I think this pattern for translating is fine, but I think we will still run into issues with languages where currencies and amounts might need to be swapped. Can we use something like the [wc_price](https://github.com/woocommerce/woocommerce/blob/5d7f6acbcb387f1d51d51305bf949d07fa3c4b08/includes/wc-formatting-functions.php#L561) helper function for this?

2024-01-30 15:57 UTC, chickenn00dle commented on src/blocks/donate/frontend/class-newspack-blocks-donate-renderer-base.php
> +			'<h3 class="wpbnbd__tiers__amount__number">' . $currency_symbol . $amount . '</h3>',
Alternatively, I'm not sure how tied we are to the specific wording here, but WC Subscriptions has done alot of the heavy lifting for formatting price strings, which can get super tricky. Can we rely on something like [wcs_price_string](https://github.com/Automattic/woocommerce-subscriptions-core/blob/81d809a476e87c260492d4cc0413818d85e123cc/includes/wcs-formatting-functions.php#L33)?

2024-01-30 15:57 UTC, chickenn00dle commented on src/blocks/donate/edit/FrequencyBasedLayout.tsx
> +													__html: getFrequencyLabel(
I wonder if we can have this string passed from the backend via `newspack_blocks_data` since the logic for creating the string already lives there? Then we can remove the duplicate logic from the frontend.

2024-01-30 15:58 UTC, chickenn00dle commented on src/blocks/donate/edit/FrequencyBasedLayout.tsx
> +												getFrequencyLabel( frequencySlug ) }
Thanks @dkoo! I left some additional review comments for this 👍

2024-01-30 16:30 UTC, dkoo commented on src/blocks/donate/edit/FrequencyBasedLayout.tsx
> +												getFrequencyLabel( frequencySlug ) }
Great suggestions here! Thank you for the guidance on this part—admittedly our work around making sure things are translatable has been lacking. 😅

2024-01-31 23:57 UTC, dkoo commented on src/blocks/donate/edit/FrequencyBasedLayout.tsx
> +													__html: getFrequencyLabel(
Done in 5f9479a. Because the block needs to be able to dynamically render values from attributes, this may look a little janky with the string replacement, but I'm open to better suggestions.

2024-01-31 23:57 UTC, dkoo commented on src/blocks/donate/frontend/class-newspack-blocks-donate-renderer-base.php
> +			'<h3 class="wpbnbd__tiers__amount__number">' . $currency_symbol . $amount . '</h3>',
5f9479a implements `wcs_price_string` with a fallback to `wc_price` if not available (if that's not available, the site has bigger problems).

2024-02-02 15:34 UTC, chickenn00dle commented on src/blocks/donate/edit/FrequencyBasedLayout.tsx
> +													__html: getFrequencyLabel(
Ah. I see what you mean. It definitely does seem a bit overly complex. I'm not sure of a cleaner way to handle this with the existing design for the donate block. My suggestion would be to remove the `per X`/`once` from the amount strings altogether as this is implied based on the category tab selection at the top (one-time/monthly/annually). But I think this might be outside of the scope of this PR.

I think what we have here is fine, although there is an edge case where the publisher has an empty value set, for example while editing an amount. The block shows `NaN`:

![Screenshot 2024-02-02 at 10 24 48](https://github.com/Automattic/newspack-blocks/assets/17905991/8bba9615-e715-4829-b766-2253c1fa1bde)

2024-02-02 15:37 UTC, chickenn00dle requested changes
Sorry for the delay on getting back to this one @dkoo. Almost there. Just one final issue commented here: https://github.com/Automattic/newspack-blocks/pull/1645#discussion_r1476211787

2024-02-05 23:54 UTC, dkoo commented on src/blocks/donate/edit/FrequencyBasedLayout.tsx
> +													__html: getFrequencyLabel(
5b8470c forces the value to be `0` in this case. Maybe still not ideal, but better than `$NaN`?

2024-02-06 16:51 UTC, chickenn00dle commented on src/blocks/donate/edit/FrequencyBasedLayout.tsx
> +													__html: getFrequencyLabel(
Yeah. I think it makes sense to set this to 0 when the input is empty. One other issue I noticed just now while retesting this is if the input is empty, we need to make sure the below $X validation still functions and prevents us from saving.

Here it is with an input value less than 5 for me:
![Screenshot 2024-02-06 at 11 37 44](https://github.com/Automattic/newspack-blocks/assets/17905991/f5ba8c10-6aaf-45b3-aaa6-5b5e8568adda)

And while the input is empty:
![Screenshot 2024-02-06 at 11 37 51](https://github.com/Automattic/newspack-blocks/assets/17905991/bde69227-5d93-47e7-9889-a17814442c33)

I think instead of forcing how the null value is rendered in the preview, we can force null values to be stored as 0 somewhere around here: https://github.com/Automattic/newspack-blocks/blob/5b8470cd35fdc1d24113ebb60ebeb220dbbc622c/src/blocks/donate/edit/index.tsx#L109

2024-02-06 17:05 UTC, chickenn00dle commented on src/blocks/donate/edit/FrequencyBasedLayout.tsx
> +													__html: getFrequencyLabel(
I also want to note while I was retesting this, I did some more thinking about the complexity of generating the translation string with dynamic pricing and HTML elements, and realized we can probably reduce the complexity by removing the `span` wrappers from the currency symbol and price, and instead placing them only around the frequency string.

We can achieve the same style results via CSS this way by setting the `.wpbnbd__tiers__amount__value` text to have the bolded and enlarged size and set the frequency span to have the unbolded smaller size.

This is how it is rendered right now:
```
<span class="wpbnbd__tiers__amount__value">
    <span class="woocommerce-Price-amount amount">
        <bdi>
            <span class="woocommerce-Price-currencySymbol">$</span>5
        </bdi>
    </span>
    once
</span>
```

We can probably achieve the same result with this:
```
<span class="wpbnbd__tiers__amount__value">
    $5
    <span class="some-class-for-frequency-label">
        once
    </span>
</span>
```

I'm okay if we tackle this another time though since this PR has become quite involved.

2024-02-06 17:46 UTC, dkoo commented on src/blocks/donate/edit/FrequencyBasedLayout.tsx
> +													__html: getFrequencyLabel(
> I also want to note while I was retesting this, I did some more thinking about the complexity of generating the translation string with dynamic pricing and HTML elements, and realized we can probably reduce the complexity by removing the `span` wrappers from the currency symbol and price, and instead placing them only around the frequency string.

That's a good call, but yes, let's leave for another PR.

> I think instead of forcing how the null value is rendered in the preview, we can force null values to be stored as 0 somewhere around here: 

At first I tried forcing empty input values to be stored as `0`, but this results in the input itself showing `0` when you delete the values in the input, which is potentially confusing to the user. Agree that we should still validate against the minimum donation value, though.

2024-02-06 18:19 UTC, dkoo commented on src/blocks/donate/edit/FrequencyBasedLayout.tsx
> +													__html: getFrequencyLabel(
> Agree that we should still validate against the minimum donation value, though.

Implemented in 9f041db

2024-02-06 18:59 UTC, chickenn00dle approved these changes
Nice! thanks for dealing with all the back and forth on this one!

2024-02-06 20:09 UTC, merged