Feat/update checkout block UI
Automattic/newspack-blocks pull request #1649
Opened 2024-01-23 18:44 UTC by chickenn00dle

### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2024-01-25 19:47 UTC, chickenn00dle commented on includes/class-modal-checkout.php
> +					<div class="newspack-ui__spinner">
I couldn't find a place for a loading state in the main newspack ui changes, so moved the logic for this in https://github.com/Automattic/newspack-plugin/pull/2878. So that will need to be checked out to ensure the spinner correctly functions while testing.

2024-01-25 21:51 UTC, chickenn00dle commented on src/modal-checkout/modal.js
> -						modalContent.style.height = contentRect.top + contentRect.bottom + 'px';
I was running into a strange bug where the iframe body was not the same height as the iframe document itself which was causing some issues with scrollbars. I got around this by getting the height of the iframe via `offsetHeight` instead which seems to have addressed the problem. Not sure if anyone has seen this issue before or if this is the best approach.

2024-01-25 21:52 UTC, chickenn00dle commented on src/modal-checkout/modal.js
> +						modalContent.style.height = iframeHeight + 48 + 'px';
Just noting that to get the iframe to load without a scollbar and to get the modal to load the iframe with the correct height, I had to account for the padding of the modal content here.

2024-01-25 22:24 UTC, miguelpeixe commented on src/modal-checkout/modal.js
> -						modalContent.style.height = contentRect.top + contentRect.bottom + 'px';
This is happening because the `__content` is applying a padding that, in the case of the modal checkout, is expected to live inside the iframe body ([here](https://github.com/Automattic/newspack-blocks/pull/1649/files#diff-93359786372d1c41af813037af697f33c6a6da8d4a48622a3c18d8e6f26f1cd7L2)), so the `top` and `bottom` values it picks up is not including the padding generated by parent element.

I'm not sure which strategy is best, but I remember having issues with the `offsetHeight` providing a consistent value across different stages of checkout/iframe changes.

2024-01-26 02:45 UTC, laurelfulford requested changes
Thanks for digging into this, @raz! 🙂 I think it's on the right track overall! I left some comments/feedback -- please let me know if you have any questions at all about what I wrote!

2024-01-26 02:45 UTC, laurelfulford commented on src/modal-checkout/modal.js
> -						modalContent.style.height = contentRect.top + contentRect.bottom + 'px';
I've suggested that we add the `newspack-ui__modal__content` CSS class to the `<body>` tag inside of the iframe further up in the review. This ends up adding more padding inside of the iframe, but I think it could help with this: we could use CSS to get rid of the problem spacing around the iframe, so the padding's all handled inside. 

Something like this in Newspack UI could work if we can all iframes should act like this: 

```
.newspack-ui__modal__content iframe {
	width: calc( 100% + var( --newspack-ui-spacer-8, 48px ) );
	max-width: unset;
	height: calc( 100% + var( --newspack-ui-spacer-8, 48px ) );
	border: none;
	margin: calc( -1 * var( --newspack-ui-spacer-5, 24px ) );
}
```

... or if it's specific to the modal checkout, we can add it to the `iframe[name="newspack_modal_checkout_iframe"]` selector in the blocks instead. 

I did a rough test with the original JS and it seems to work! Let me know what you think 🙂

2024-01-26 02:45 UTC, laurelfulford commented on src/modal-checkout/templates/thankyou.php
> +				<?php // TODO: How should we handle sharing icons across plugins? ?>
Ooooh, good point! 🤔 

I think at least these SVGs are just decorative; we might be able to use only CSS for them -- something like: 

```
.newspack-ui__icon:after {
    background-color: currentcolor;
    content: '';
    display: block;
    height: 24px;
    mask-size: 24px;
    width: 24px;
}

.newspack-ui__icon--success::after {
	mask: url('../path/to/svg/asset.svg') 0 0 no-repeat;
}
```

We'd still need to duplicate must-have SVGs (like the close icon), so this might not be an ideal replacement!

2024-01-26 02:45 UTC, laurelfulford commented on includes/class-modal-checkout.php
> +		}
This is a nice approach to swapping the classes!

2024-01-26 02:45 UTC, laurelfulford commented on src/modal-checkout/modal.js
> +				variationModals.forEach( variationModal => {
The variations modal isn't quite marked up like the modal checkout ([variations](https://github.com/Automattic/newspack-blocks/pull/1649/files#diff-74a92f16c32d2a94751337aaff7d24de10881675f81809bae9d09e79cc47e10eL350) vs. [modal checkout](https://github.com/Automattic/newspack-blocks/pull/1649/files#diff-74a92f16c32d2a94751337aaff7d24de10881675f81809bae9d09e79cc47e10eR298-R299)), so changing the JS for it causes the Checkout Button to stop opening if it's for a variable product.

(To recreate, you need to have a variable product in Woo, and set up the Checkout Button block to use it, and check "Allow the reader to select the variation before checkout" -- here's [a little more about the block](https://help.newspack.com/publishing-and-appearance/blocks/checkout-button-block/) and [that specific feature](https://help.newspack.com/publishing-and-appearance/blocks/checkout-button-block/#customize-product-variations)!).

When I roll back to the epic/ras-acc branch the button still works. I think it should ultimately all be updated (with the same markup for the modal container and overlay), but that can be done separately 🙂 (if you like, I'm happy to take a swing at it!).

2024-01-26 17:40 UTC, chickenn00dle commented on src/modal-checkout/modal.js
> -						modalContent.style.height = contentRect.top + contentRect.bottom + 'px';
Nice! Thanks for the clarity and suggestions y'all 🙌 

I was able to apply these styles and revert the iframe resizing logic in https://github.com/Automattic/newspack-blocks/pull/1649/commits/c8b032947bf6f540c64a67d7eaf8bf32ac89c320

2024-01-26 17:41 UTC, chickenn00dle commented on includes/class-modal-checkout.php
> +		<body class="newspack-ui" id="newspack_modal_checkout">
Ah. Makes sense! I've added the modal specific class in https://github.com/Automattic/newspack-blocks/pull/1649/commits/c8b032947bf6f540c64a67d7eaf8bf32ac89c320

2024-01-26 17:42 UTC, chickenn00dle commented on src/modal-checkout/templates/thankyou.php
> +				<?php // TODO: How should we handle sharing icons across plugins? ?>
Gotcha! I'm gonna leave this one as is for now and maybe we can tackle this in a follow-up PR?

2024-01-26 17:56 UTC, chickenn00dle commented on src/modal-checkout/modal.scss
> +.newspack-ui {
I decided to keep the iframe specific styles here rather than in the main newspack ui library. My thought is we should let each iframe dictate how it should be styled rather than enforce styles top down. That said, I don't feel too strongly about this, and am happy to move this over to the newspack ui library anyway.

2024-01-30 10:53 UTC, adekbadek commented
@chickenn00dle – 

> As a consequence this breaks the styling of the modal checkout form a bit, but I will work on that in a follow up PR so this one doesn't get too big.

Can you please add a list of these breakages to PR description? I've seen this one when testing, not sure if it's expected:

<img width="691" alt="image" src="https://github.com/Automattic/newspack-blocks/assets/7383192/60d6215a-dbfa-4f90-9717-47e8fe760558">

2024-01-30 10:54 UTC, adekbadek commented on includes/class-modal-checkout.php
> +	 * Get the relevant class prefix (newspack-blocks or newspack-ui)depending on whether Newpack plugin is active.
```suggestion
	 * Get the relevant class prefix (newspack-blocks or newspack-ui) depending on whether Newpack plugin is active.
```

2024-01-30 10:58 UTC, adekbadek reviewed
LGTM, but I'll defer to @laurelfulford as the primary reviewer.

2024-01-30 10:58 UTC, adekbadek commented on src/modal-checkout/modal.js
> +const CLASSNAME_BASE = newspackBlocksModal.has_newspack_ui ? 'newspack-ui' : 'newspack-blocks';
To avoid duplication, I'd suggest passing the value of `Modal_Checkout::get_class_prefix()` directly.

2024-01-30 16:40 UTC, chickenn00dle commented on includes/class-modal-checkout.php
> +		add_filter( 'newspack_reader_activation_should_render_auth', '__return_false' );
Noting that I've added this with the latest merge of master into epic/ras-acc since we have another task to integrate the auth flow into checkout.

2024-01-30 16:43 UTC, chickenn00dle commented on includes/class-modal-checkout.php
> +	 * Get the relevant class prefix (newspack-blocks or newspack-ui)depending on whether Newpack plugin is active.
Good catch! Fixed in https://github.com/Automattic/newspack-blocks/pull/1649/commits/6fa14705166d8070e6f3139fe2f6cb6ce61c7c37

2024-01-30 16:44 UTC, chickenn00dle commented on src/modal-checkout/modal.js
> +const CLASSNAME_BASE = newspackBlocksModal.has_newspack_ui ? 'newspack-ui' : 'newspack-blocks';
Good call! Updated in https://github.com/Automattic/newspack-blocks/pull/1649/commits/e188f8ff43b1bc5855c511963dabee8cbe65c7f8

2024-01-30 16:50 UTC, chickenn00dle commented
> Can you please add a list of these breakages to PR description? I've seen this one when testing, not sure if it's expected

Sure thing @adekbadek! 

It is expected. This is the checkout form which this PR only changes the modal wrapper for. I've updated the description to show the parts of the checkout flow which are expected not to be fully styled as of this PR.

2024-01-31 02:04 UTC, laurelfulford commented on src/modal-checkout/templates/thankyou.php
> +				<?php // TODO: How should we handle sharing icons across plugins? ?>
That makes sense to me! 👍

2024-01-31 03:28 UTC, laurelfulford requested changes
Apologies for taking a bit to get back to this, @chickenn00dle! I added some comments, but I may have missed where some of this is being addressed elsewhere! If that's the case, please disregard -- ditto if any of this would be better to handle in separate PRs 🙂 

Just let me know if you have any questions at all!

2024-01-31 03:28 UTC, laurelfulford commented on src/modal-checkout/modal.js
> -						modalContent.style.height = contentRect.top + contentRect.bottom + 'px';
This looks good overall! 

I did notice the spinner's no longer displaying -- it's using the Newspack UI classes but spinner styles don't exist there. 

Similar to [this comment](https://github.com/Automattic/newspack-blocks/pull/1649/files#r1467956484), this could be something that just lives in the checkout modal, I think the CSS classes just need to be updated in the markup to not switch to the `newspack-ui__` classes, and the CSS itself might need a bit of a massage so the structure still works with how the modal might be structured with the `newspack-ui` classes 🙂 

![image](https://github.com/Automattic/newspack-blocks/assets/177561/ca54938e-a77d-4ba1-8eda-0e9534368c63)

2024-01-31 15:25 UTC, chickenn00dle commented on includes/class-modal-checkout.php
> +		add_filter( 'newspack_reader_activation_should_render_auth', '__return_false' );
> It looks like our Sign Up / Sign In button styles are included in the auth.css file this enqueues -- not sure if just deleting the other files would be better, or maybe something else?

Ah! Good catch. I should note that I am only temporarily bypassing the auth flow for this and the other modal checkout ui update PR. But will be incorporating auth into modal checkout with 0/1206274567818686/1205668937699524. Not sure if it's okay to allow these buttons to appear broken in epic/ras-acc for a short time only?

2024-01-31 15:27 UTC, chickenn00dle commented on src/modal-checkout/modal.js
> +				variationModals.forEach( variationModal => {
For now, I've gone ahead and added the existing variation styles to newspack-ui in https://github.com/Automattic/newspack-plugin/pull/2878, but if they need to be updated, then it'd be great if you could take a crack at it!

2024-01-31 15:27 UTC, chickenn00dle commented on src/modal-checkout/modal.js
> -						modalContent.style.height = contentRect.top + contentRect.bottom + 'px';
> I did notice the spinner's no longer displaying -- it's using the Newspack UI classes but spinner styles don't exist there.

I've actually moved the styles for the spinner over to newspack-ui in Automattic/newspack-plugin#2878. Sorry if it wasn't clear, but you'll need to check that branch out in the main Newspack plugin before testing this to see the spinner in action!

2024-01-31 15:29 UTC, chickenn00dle commented
Thanks for having another look @laurelfulford!

I've commented on your feedback. I'm happy to move styles for things into this PR but wanted to make sure you were aware of all of my updates before making any changes.

2024-02-01 01:06 UTC, laurelfulford commented on includes/class-modal-checkout.php
> +		add_filter( 'newspack_reader_activation_should_render_auth', '__return_false' );
Ah gotcha! 

> Not sure if it's okay to allow these buttons to appear broken in epic/ras-acc for a short time only?

I think that's probably fine -- it looks like some other stuff will be in flux as well!

2024-02-01 01:06 UTC, laurelfulford commented on src/modal-checkout/modal.js
> +				variationModals.forEach( variationModal => {
Oh nice -- thanks @chickenn00dle! 🙌

2024-02-01 01:19 UTC, laurelfulford commented on src/modal-checkout/modal.js
> -						modalContent.style.height = contentRect.top + contentRect.bottom + 'px';
Ah thanks! I'm afraid I haven't been following things as closely as I should this week. When I have that branch checked out too, the spinner is there! 🙂

2024-02-01 01:20 UTC, laurelfulford approved these changes
Thanks for all the exhaustive back and forth on this, @chickenn00dle! I think stuff is looking good overall -- thank you for helping me get up to speed where the other pieces are! 

I think this piece is good to go, and probably will probably make things easier for the other PRs to have it merged 😅

2024-02-01 09:23 UTC, adekbadek commented
Note: https://github.com/Automattic/newspack-blocks/pull/1653 updates the styling of the checkout modal to fix the issues introduced in this PR.

2024-02-01 15:25 UTC, merged