feat(modal-checkout): update modal checkout checkout form with newspack ui
Automattic/newspack-blocks pull request #1653
Opened 2024-01-26 21:53 UTC by chickenn00dle

### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2024-01-30 22:49 UTC, chickenn00dle commented
Hey @laurelfulford, I hope it's okay if I ping you for this one as well since you are the most familiar with how the newspack ui styles should look and are already looking at https://github.com/Automattic/newspack-blocks/pull/1649. 

Let me know if you've got too much on your plate though!

2024-01-31 21:32 UTC, dkoo requested changes
@chickenn00dle looking mostly good, as far as I can tell! Noting the broken "Sign In" buttons, but I see your `TODO` comment about this. Other than that, I saw some minor styling issues mainly in the payment gateway section.

Some of the font sizing seems off. In this screenshot, the text that starts "Pay with your credit card via Stripe" and the privacy notice below ("Your personal data will be used to process your order...") look pretty minuscule. Also, the checkbox labels look unnaturally large.

<img width="684" alt="Screenshot 2024-01-31 at 2 21 16 PM" src="https://github.com/Automattic/newspack-blocks/assets/2230142/5dce6a4e-988f-46b6-8d38-2e84d0a208b4">


Refer to this screenshot from the design mocks for relative type scale. Also note that the design mock includes both a bold and non-bold element for the "cover fees" checkbox. Currently our settings only allow for a single text string, so it might be hard to emulate this right now, but let's make sure the styles support the separate lines.

<img width="578" alt="Screenshot 2024-01-31 at 11 52 53 AM" src="https://github.com/Automattic/newspack-blocks/assets/2230142/1ae398ef-6644-471e-9d21-2864cf2a5779">

2024-02-01 18:52 UTC, chickenn00dle commented on includes/class-modal-checkout.php
> +		$newspack_ui_html = preg_replace( '/class=".*?"/', "class='{$classname}__button {$classname}__button--primary {$classname}__button--wide'", $html );
Good call! I've updated this in https://github.com/Automattic/newspack-blocks/pull/1653/commits/9f7ad1c898d747e7def0b390b738d4510b9793e3

2024-02-01 18:58 UTC, chickenn00dle commented
Thanks for the review @dkoo!

> Some of the font sizing seems off. In this screenshot, the text that starts "Pay with your credit card via Stripe" and the privacy notice below ("Your personal data will be used to process your order...") look pretty minuscule. Also, the checkbox labels look unnaturally large.

Good catch. I've updated the text sizes in the newspack ui overrides over in https://github.com/Automattic/newspack-plugin/pull/2878 so they should be closer to the figma:

![Screenshot 2024-02-01 at 13 51 54](https://github.com/Automattic/newspack-blocks/assets/17905991/3567411c-eb96-41c6-80a9-9c6d9f7878c7)

> Also note that the design mock includes both a bold and non-bold element for the "cover fees" checkbox. Currently our settings only allow for a single text string, so it might be hard to emulate this right now, but let's make sure the styles support the separate lines.

Yeah. I noticed that too. I'm a bit hesitant to add styling for this until we adjust our settings to allow for multiple strings of text here. Ultimately, I think it will be pretty simple once we do though. Happy to go ahead and add the styles now though!

2024-02-03 01:34 UTC, dkoo approved these changes
This is looking better to me, now! Thanks for the changes.
<img width="662" alt="Screenshot 2024-02-02 at 6 34 43 PM" src="https://github.com/Automattic/newspack-blocks/assets/2230142/617e5555-4a0e-4232-9052-6a695d8c949b">

2024-02-05 17:24 UTC, merged