fix(modal-checkout): treat express checkouts as modal checkouts
Automattic/newspack-blocks pull request #1654
Opened 2024-01-26 23:52 UTC by dkoo

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes some issues with checkout when using express checkout methods (also called "payment requests" in Stripe terminology) in modal checkout. Our `is_modal_checkout` method isn't recognizing express checkout requests as being triggered by modal checkout, so there can be mismatches in the data we're providing via modal checkout and what WooCommerce would expect, thinking the checkout requests is happening via a standard checkout flow. This could affect any behavior we customize for the modal checkout, including:

- Required billing fields (e.g. if you partially set up Google Pay but don't add an address, and your site is set to not collect address fields during modal checkout, Woo might still throw errors about missing required address fields).
- Behavior we enforce to allow guest checkout and account registration during checkout

### How to test the changes in this Pull Request:

1. There are some prerequisites for testing these features. Set up your local site with Newspack + Stripe Gateway for reader revenue. In the Stripe Gateway settings, make sure express checkout methods are enabled, and in your [connected Stripe account dashboard](https://dashboard.stripe.com/test/settings/payment_method_domains), make sure to whitelist your test site's domain.
2. To set up Apple Pay, you'll need to log into an Apple ID account on your dev machine and connect a real credit card with a valid billing address to your Apple Wallet. When completing transactions on a site where Stripe is set to test mode, the card won't be charged.
3. To set up Google Pay, you'll need to connect a real credit card + billing address to your Google account at https://pay.google.com/. You'll also need to log in with this Google account in your Chrome browser and enable account syncing and autofilling of both payment methods and credit cards in browser settings. After doing all this you may also have to clear all browser data and wait several minutes in order for these things to take effect.
4. Test Apple Pay: on `release`, visit your site in Safari and make a donation. You should be able to see the "Buy with Apple Pay" button and use it to complete the transaction.

<img width="651" alt="Screenshot 2024-01-26 at 4 12 40 PM" src="https://github.com/Automattic/newspack-blocks/assets/2230142/6f558a48-fc2b-4ecf-82ac-1685979155d3">

6. Still on `release`, open a new session and attempt to complete another transaction with Apple Pay. This time you should see an error stating "An account is already registered with your email address. Please log in" even though modal checkout should allow the unauthenticated checkout to occur.
7. Check out this branch and repeat step 6. Confirm that it completes this time, and that the order/subscription is tied to the same reader account in WP admin.
8. Try to test with Google Pay in Chrome, too, but this is a bit more challenging to make appear. The logic/behavior should be the same as Apple Pay.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2024-01-29 08:12 UTC, adekbadek requested changes
This change breaks the checkout for non-Newspack products. `modal_checkout` is set [under conditions](https://github.com/Automattic/newspack-blocks/blob/5f9350a1beed41c7f0b9701d2b38b5256c4312b3/includes/class-modal-checkout.php#L166) different than defined in this change. The result is that when using the payment request with a non-Newspack product, the customer is redirected to our "Transaction Successful" screen which [assumes it's rendered in a modal](https://github.com/Automattic/newspack-blocks/blob/5f9350a1beed41c7f0b9701d2b38b5256c4312b3/includes/class-modal-checkout.php#L761-L762). The "Continue browsing" button won't do anything, trapping the user on this screen for eternity.

2024-01-29 16:28 UTC, dkoo commented
> This change breaks the checkout for non-Newspack products. `modal_checkout` is set [under conditions](https://github.com/Automattic/newspack-blocks/blob/5f9350a1beed41c7f0b9701d2b38b5256c4312b3/includes/class-modal-checkout.php#L166) different than defined in this change. The result is that when using the payment request with a non-Newspack product, the customer is redirected to our "Transaction Successful" screen which [assumes it's rendered in a modal](https://github.com/Automattic/newspack-blocks/blob/5f9350a1beed41c7f0b9701d2b38b5256c4312b3/includes/class-modal-checkout.php#L761-L762). The "Continue browsing" button won't do anything, trapping the user on this screen for eternity. 

Noooo! Great points. I was overly optimistic about this change, but it looks like we'll have to figure out a way to pass the `modal_checkout` param to the `payment_request` request so we can see the source of the payment. :\

2024-01-30 01:07 UTC, dkoo commented
@adekbadek 712858a adds the check we were missing. We can still fetch the referrer URL from the express checkout request, so that lets us see if the request was triggered in a modal checkout.

2024-01-31 15:30 UTC, adekbadek approved these changes

2024-01-31 16:57 UTC, merged