fix: remove unnecessary payment request hooks
Automattic/newspack-blocks pull request #1661
Opened 2024-02-03 01:28 UTC by dkoo

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Companion to https://github.com/Automattic/newspack-plugin/pull/2904.

### How to test the changes in this Pull Request:

Follow instructions in https://github.com/Automattic/newspack-plugin/pull/2904.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2024-02-06 00:54 UTC, dkoo commented
Note: Rebased against `epic/ras-acc` as gift subscription functionality has been fixed in the epic, not in `trunk`.

2024-02-06 16:27 UTC, chickenn00dle requested changes

2024-02-06 16:27 UTC, chickenn00dle commented on includes/class-modal-checkout.php
> -	public static function amend_cart_item_data( $cart_item_data ) {
I'm getting the following error when testing with https://github.com/Automattic/newspack-blocks/pull/1661, https://github.com/Automattic/newspack-plugin/pull/2904, and https://github.com/Automattic/newspack-theme/pull/2240 checked out:

```
[06-Feb-2024 16:14:03 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method Newspack_Blocks\Modal_Checkout::amend_cart_item_data() in /newspack-repos/newspack-blocks/includes/class-modal-checkout.php:155
Stack trace:
#0 /var/www/html/wp-includes/class-wp-hook.php(324): Newspack_Blocks\Modal_Checkout::process_checkout_request()
#1 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#2 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action()
#3 /var/www/html/wp-settings.php(665): do_action()
#4 /var/www/html/wp-config.php(115): require_once('...')
#5 /var/www/html/wp-load.php(50): require_once('...')
#6 /var/www/html/wp-blog-header.php(13): require_once('...')
#7 /var/www/html/index.php(17): require('...')
#8 {main}
  thrown in /newspack-repos/newspack-blocks/includes/class-modal-checkout.php on line 155
```

Seems this method is still needed here: https://github.com/Automattic/newspack-blocks/blob/9af158260a287b45328e43abead1ae5d29628b87/includes/class-modal-checkout.php#L155

2024-02-06 17:25 UTC, dkoo commented on includes/class-modal-checkout.php
> -	public static function amend_cart_item_data( $cart_item_data ) {
Ugh, thanks. Trying to multitask too much 🤦

2024-02-06 18:03 UTC, dkoo commented on includes/class-modal-checkout.php
> -	public static function amend_cart_item_data( $cart_item_data ) {
Fixed in 12da73a

2024-02-08 18:32 UTC, chickenn00dle approved these changes
Nice! Thanks for the quick update. This lgtm 👍

2024-02-08 18:33 UTC, merged