fix(hpp): filter invalid autocomplete tokens
Automattic/newspack-blocks pull request #1671
Opened 2024-02-14 19:46 UTC by chickenn00dle

### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes `0/1206331646877116/1204088636207233/f`.

This fixes an issue where the homepage posts block was allowing invalid categories, authors, and tags to be saved, which resulted in an error in the block editor.

This fixes this by filtering out any invalid tokens for the autocomplete component.

### How to test the changes in this Pull Request:

1. Add the homepage posts block to any post/page
2. In block settings, input any invalid category name then press enter
3. Save the post/page
4. Reload the page
5. On `trunk` you should see the block render an error
![Screenshot 2024-02-14 at 14 45 17](https://github.com/Automattic/newspack-blocks/assets/17905991/fb580c39-ac34-4a2c-a4e7-91a3d1a747a9)
6. On this branch, you should not!

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2024-02-15 14:42 UTC, adekbadek requested changes
And invalid value should not be added to the block attributes in the first place. With this fix in place, the block still does not render any posts because it still tries to filter by an invalid category. 

<img width="707" alt="image" src="https://github.com/Automattic/newspack-blocks/assets/7383192/248530e6-6d04-4f7c-a48f-156d322a0f13">

2024-02-19 17:58 UTC, chickenn00dle commented
> And invalid value should not be added to the block attributes in the first place

Hmm. This is what this PR is doing. Attributes look to be saved via this `AutocompleteTokenField` component's [onChange prop](https://github.com/Automattic/newspack-blocks/blob/ebdb4ab1944db0c7c1c95a96025d7fab54fb538b/src/components/autocomplete-tokenfield.js#L156) which is passed along from the `edit.js` file: https://github.com/Automattic/newspack-blocks/blob/ebdb4ab1944db0c7c1c95a96025d7fab54fb538b/src/blocks/homepage-articles/edit.js#L363 

If you had previously saved an invalid attribute while in `trunk` then switch to this branch, you will need to re-save the attribute in order for those invalid values to be removed from attributes.

That said, for folks who have already saved null values in attributes, and don't wish to go through the process of re-saving, I've added some validation when querying for posts here: https://github.com/Automattic/newspack-blocks/pull/1671/commits/19a30e43be5aedc3b799d3f6604c90cdb055d62f

2024-02-20 08:34 UTC, adekbadek approved these changes
Works fine now!

> If you had previously saved an invalid attribute while in trunk then switch to this branch

The testing instructions do not state that block should be re-added after switching the branch, so I assumed this would fix existing attributes.

2024-02-20 14:41 UTC, chickenn00dle commented
> The testing instructions do not state that block should be re-added after switching the branch, so I assumed this would fix existing attributes.

Ah. Sorry about that @adekbadek!

2024-02-20 14:43 UTC, merged