fix(modal-checkout): ensure customer location when state is required but country is not
Automattic/newspack-blocks pull request #1683
Opened 2024-03-01 17:27 UTC by dkoo

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Alternative version of https://github.com/Automattic/newspack-plugin/pull/2960, but isolated only to modal checkout instances.

### How to test the changes in this Pull Request:

Follow testing instructions ins https://github.com/Automattic/newspack-plugin/pull/2960

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2024-03-01 20:19 UTC, chickenn00dle requested changes
Nice! This works for me @dkoo 

Just one issue then this is good to go 👍

2024-03-01 20:19 UTC, chickenn00dle commented on includes/class-modal-checkout.php
> +		$billing_fields = get_option( Donations::DONATION_BILLING_FIELDS_OPTION, [] );
`Donations::DONATION_BILLING_FIELDS_OPTION` lives in the main plugin so we will need to do a check to confirm this is active here, then properly namespace it.

2024-03-01 22:56 UTC, dkoo commented on includes/class-modal-checkout.php
> +		$billing_fields = get_option( Donations::DONATION_BILLING_FIELDS_OPTION, [] );
Whoops, a victim of copy/paste syndrome! Fixed in 9c92297

2024-03-02 01:30 UTC, chickenn00dle approved these changes

2024-03-04 18:15 UTC, merged