fix: show credit option for homepage posts & carousel blocks
Automattic/newspack-blocks pull request #1687
Opened 2024-03-05 21:22 UTC by dkoo

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Adds new block attribute options to show credits for Homepage Posts and Post Carousel blocks (and to show captions for the latter, too).

Closes `1206709674365921/1206688511006431`.

### How to test the changes in this Pull Request:

1. Check out this branch.
2. Add a Homepage Posts block and a Post Carousel block to the page, and configure so they show articles with featured images that have captions and credits.
3. Enable captions + credits for both blocks and confirm the captions are shown in both editor and front-end context:

| Editor  | Front-end |
| ------------- | ------------- |
| <img width="1061" alt="Screenshot 2024-03-05 at 2 14 27 PM" src="https://github.com/Automattic/newspack-blocks/assets/2230142/5329e5d6-94f2-432e-af3a-b06642ade653">  | <img width="1216" alt="Screenshot 2024-03-05 at 2 19 19 PM" src="https://github.com/Automattic/newspack-blocks/assets/2230142/8ac70988-5db9-4b54-96c3-123b950974f6">  |

4. Play with different combinations of caption and/or credit and confirm that the right info appears as expected in both editor and front-end. Try:
  - Caption enabled, credit disabled
  - Caption disabled, credit enabled
  - Both disabled

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2024-03-05 21:40 UTC, dkoo commented
Paging @kevinzweerink and @thomasguillot for design review!

2024-03-05 22:00 UTC, kevinzweerink commented
I don't have time to test this locally before I head out for the evening, but the type and color look good to me in the screenshot. I can test locally first thing tomorrow morning, but if it's urgent to merge this I'm comfortable approving based on the screenshot and can double-check tomorrow. As long as we're using standard type sizes and theme colors it looks good to me :)

2024-03-05 23:20 UTC, dkoo commented
Thanks, @kevinzweerink! I'm comfortable with your 👍  based on the screenshots. We can always tweak the styles separately after the fix goes out, if we want to.

2024-03-06 02:02 UTC, laurelfulford requested changes
This looks good @dkoo! I found a couple small things, but nothing major:

**Homepage Posts block + Featured image behind:** 
* There's a z-index issue with this placement and the caption -- I think bumping the z-index of the whole caption up to 3 or 4 [here](https://github.com/Automattic/newspack-blocks/blob/trunk/src/blocks/homepage-articles/view.scss#L347) should fix (right now it's visible, but you can't click on links in it).
* Links in the credit are also not picking up the correct colour (at least with the default theme/colours). Styling any links in the caption to be inherited or maybe white should fix!

<img width="390" alt="image" src="https://github.com/Automattic/newspack-blocks/assets/177561/c8d1b08a-3bbe-4af5-b77b-6eb6e0600aa4">

* This is kind of an edge case, but when I first added captions to the Homepage Posts blocks, I styled them to only display as one line and then trail off with an ellipsis when the featured image was set to 'behind', which I'm sure made sense at the time 😅 Unfortunately, it ends up cutting off the credit if it's really long, or if it's also shown with a caption. I think it's something we could iterate on after this PR; I can't think of any sites that actually use this placement _and_ a caption, to me the two seem to be at odds with each other. In the near-term if it IS an issue, using only a credit should fix it in most cases, and we could tweak on specific sites with CSS.

<img width="390" alt="image" src="https://github.com/Automattic/newspack-blocks/assets/177561/ebd239a0-9d05-4b87-931e-869daf400177">


**Post Carousel**
* When captions are enabled but a post doesn't have one, the div around it is still output on the front-end; it has a top margin, which adds a little extra space than normal on the front-end. This doesn't happen in the editor: 
<img width="412" alt="image" src="https://github.com/Automattic/newspack-blocks/assets/177561/734fdcea-debe-40f1-a4a9-7a9b4d42438a">

Otherwise, things look good! I tested the different visible post counts with the Post Carousel, and different font sizes and image placements for the Homepage Posts block, and didn't spot anything else!

2024-03-07 17:27 UTC, thomasguillot commented
I pushed some small changes: https://github.com/Automattic/newspack-blocks/pull/1687/commits/4f856ce6f93e4521e22fa5f629b7e2d2f7187b34

What it does is it uses the css variables available in:

1. Block Theme, if not,
2. "Classic" Theme, if not,
3. default value

2024-03-07 19:19 UTC, dkoo commented
> This is kind of an edge case, but when I first added captions to the Homepage Posts blocks, I styled them to only display as one line and then trail off with an ellipsis when the featured image was set to 'behind', which I'm sure made sense at the time 😅 Unfortunately, it ends up cutting off the credit if it's really long, or if it's also shown with a caption. I think it's something we could iterate on after this PR; I can't think of any sites that actually use this placement and a caption, to me the two seem to be at odds with each other. In the near-term if it IS an issue, using only a credit should fix it in most cases, and we could tweak on specific sites with CSS.

@laurelfulford agreed, this looks like an edge case that we shouldn't spend a lot of time accommodating. cca9d3b does add a `has-credit` class name to the `figcaption` if we want to do more.

> When captions are enabled but a post doesn't have one, the div around it is still output on the front-end; it has a top margin, which adds a little extra space than normal on the front-end. This doesn't happen in the editor:

Whoops, good. catch! The new function was still outputting empty HTML elements even if there's no caption or credit to display. cca9d3b fixes this.

2024-03-07 21:01 UTC, laurelfulford requested changes
Thanks for the fixes, @dkoo!

There's just one tweak remaining - once that's in place I think this is good to go!

2024-03-07 21:01 UTC, laurelfulford commented on src/blocks/homepage-articles/view.scss
> +			z-index: 3;
```suggestion
			z-index: 3;
			
			a,
			a:visited {
			    color: #fff;
			}
```

Just need to add a little tweak for links in the caption to make sure they're not picking up the theme colour -- I tested this and it should work for regular & visited links in credits!

(I only think this is an issue because the theme's link styles are pretty specific!)

2024-03-07 21:10 UTC, dkoo commented on src/blocks/homepage-articles/view.scss
> +			z-index: 3;
Thanks—totally forgot to test the different link states!

2024-03-07 21:12 UTC, laurelfulford approved these changes
Thanks @dkoo -- looks good! 🚢

2024-03-07 21:20 UTC, merged