feat(ras-acc): add newsletter signup option to checkout button and donation blocks
Automattic/newspack-blocks pull request #1705
Opened 2024-04-11 16:54 UTC by chickenn00dle

### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes https://app.asana.com/0/1206810965479792/1205992141743582/f

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2024-04-12 22:56 UTC, chickenn00dle commented
Just noting I'm having a pretty hard time getting the donate block to pass along newsletter related attributes to the iframe. This is pretty much the final piece of this before I can mark this ready for review. I will take another stab at this next week 🤞

2024-04-24 13:19 UTC, adekbadek requested changes
> If the form is hidden via the hide option, the customer will automatically be subscribed to the selected lists.

Noting that I've started a discussion about this bit internally (in task tracking).

2024-04-24 13:19 UTC, adekbadek commented on src/blocks/checkout-button/save.js
> +							value={ attributes.lists.join( ',' ) }
For some reason, the list on the front-end is not comma-separated. Perhaps some sanitization is stripping out the commas?

<img width="717" alt="image" src="https://github.com/Automattic/newspack-blocks/assets/7383192/ece380b0-103e-49be-ae34-5825ad246517">

As a result, no lists are displayed:

<img width="648" alt="image" src="https://github.com/Automattic/newspack-blocks/assets/7383192/7cfc42fa-7fe4-42d5-8bf7-29f5c362d784">

2024-04-24 13:19 UTC, adekbadek commented on includes/class-modal-checkout.php
> +							continue;
The result of this filtering may be that there are no lists available at all. The list should be filtered earlier and the whole UI skipped if there are no lists to subscribe to.

2024-05-07 14:37 UTC, chickenn00dle commented
Closing this as we decided to hold off on this for the time being. See 0-as-1205992141743582/1207160426336235/f

2024-05-07 14:37 UTC, closed without merging