feat: additional component updates
Automattic/newspack-blocks pull request #1719
Opened 2024-04-25 19:35 UTC by laurelfulford

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Updates the CSS classes used in Newspack Blocks, related to these changes: https://github.com/Automattic/newspack-plugin/pull/3091

Specifically:

* Replaced the `newspack-ui__inline-info` class with `newspack-ui__helper-text`, to line up with the Figma naming convention.
* Replaced the `newspack-ui__helper-text` class on the address with `newspack-ui__font--xs` to get the font size without picking up the lighter grey colour.
* Replaced the `newspack-ui__input-list` classname with `newspack-ui__input-card`.

### How to test the changes in this Pull Request:

1. See https://github.com/Automattic/newspack-plugin/pull/3091 for testing steps and test with it.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2024-05-15 15:10 UTC, laurelfulford commented
Just adding a note that the corresponding [Newspack Plugin PR got a thumbs up from design](https://github.com/Automattic/newspack-plugin/pull/3091#issuecomment-2111970780), so this one is good to go on that front, too!

2024-05-15 19:33 UTC, chickenn00dle requested changes
The changes look good, just noting that I think we have to account for the case where the blocks plugin is being used without the main newspack plugin. 

I've been creating some basic backup styles for this case and using the `newspack-blocks` prefix for this and have a helper method to decide which to use based on whether newspack ui is available or not: https://github.com/Automattic/newspack-blocks/blob/101c2c23c2a0acdb7d2005028fe32d96c9ce68f3/includes/class-modal-checkout.php#L1238-L1240

2024-05-15 20:49 UTC, laurelfulford commented
Oooo, thanks @chickenn00dle! I totally dropped the ball on updating those -- I'll do a sweep and make updates for when the Newspack Plugin isn't installed!

2024-05-15 21:35 UTC, laurelfulford commented
@chickenn00dle It doesn't look like these changes affect what's there, but things are definitely not close to 1:1. 

I spun up an issue for this in Asana here, and assigned it to 'Phase 2': 1205234045751551-as-1206899964006422. My thinking is:

* It'd be nice to figure out how close this should be -- it definitely shouldn't be broken-broken, but probably also not 1:1 for ease of maintenance. I see we have some straight-up WooCoomerce styles and stuff bleeding through without Newspack installed (like the checkout modal is two columns). Maybe we can leverage that instead of working against it? 
* It doesn't seem like a blocker for phase 1.

2024-05-16 14:33 UTC, chickenn00dle commented
Sounds good @laurelfulford! In that case, I'll give this a thumbs up 👍

2024-05-16 14:34 UTC, chickenn00dle approved these changes

2024-05-16 16:58 UTC, laurelfulford commented
Awesome -- thanks @chickenn00dle!

2024-05-16 16:59 UTC, merged