fix: add `woocommerce_after_order_notes` action for integrations that need it
Automattic/newspack-blocks pull request #1720
Opened 2024-04-25 21:02 UTC by dkoo

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Currently our custom checkout form doesn't include Woo's shipping form template, which is where the `woocommerce_after_order_notes` action lives. This PR adds it right before the `woocommerce_checkout_after_customer_details` action, which is roughly where it should appear in relation to the checkout fields. Only registers the action hook if it hasn't already been registered.

### How to test the changes in this Pull Request:

1. Check out this branch.
2. Create a custom action callback to execute on the `woocommerce_after_order_notes` hook, e.g.

```php
add_action(
	'woocommerce_after_order_notes',
	function( $checkout ) {
		error_log( 'woocommerce_after_order_notes action!!!' );
		error_log( print_r( $checkout, true ) );
	}
);
```

3. Start a purchase of a product via the Checkout Button block. On the second screen (with payment details) confirm that your action callback is executed and that the `$checkout` argument is an instance of `WC_Checkout`.
4. Go to your `/shop` page and start a purchase via the standard Woo checkout flow. Confirm that your action callback is executed here, too.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2024-04-26 07:42 UTC, adekbadek requested changes

2024-04-26 07:42 UTC, adekbadek commented on src/modal-checkout/templates/checkout-form.php
> +			if ( ! has_action( 'woocommerce_after_order_notes' ) ) {
In my testing, `has_action( 'woocommerce_after_order_notes' ) === true` (so the following lines don't get executed), _and_ the callback is never called.

2024-04-26 15:53 UTC, dkoo commented on src/modal-checkout/templates/checkout-form.php
> +			if ( ! has_action( 'woocommerce_after_order_notes' ) ) {
Whoops, `has_action` is the wrong method for checking whether an action hook has been registered. (`has_action` checks whether a _callback_ has been registered for the given action hook.) 9604ebb checks whether the action hook is registered on the global `$wp_actions` object instead.

2024-05-07 09:03 UTC, adekbadek approved these changes

2024-05-07 16:25 UTC, merged