fix(ras-acc): make sure checkout modal fires when logged in
Automattic/newspack-blocks pull request #1735
Opened 2024-05-16 23:36 UTC by laurelfulford

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR fixes a small issue I noticed when working on the components, but didn't really investigate: when you're logged in as a WordPress User (and not a Reader), the checkout modal didn't open. The variable modal did open, but then when you picked a variation, it would close the modal and not move to the checkout.

My fix is just to check for the `logged-in` CSS class, but there's probably a more elegant way that ties into the existing code!

### How to test the changes in this Pull Request:

1. On the epic/ras-acc branch, set up a donate block and a checkout button block that loads a product with variations.
2. In a window when you're logged into WordPress, try to run the checkout from each block. Note that it doesn't work (either doesn't open a modal, or closes the variation modal when you pick a variation).
3. In an incognito window, repeat step 2 and note the modals do work (it will open the registration modal first before the checkout modal). 
4. Apply this PR and run `npm run build`.
5. Repeat steps 2 and 3 and confirm the checkout modal can be reached in both cases.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2024-05-17 12:10 UTC, adekbadek requested changes

2024-05-17 12:10 UTC, adekbadek commented on src/modal-checkout/modal.js
> +						! loggedIn
There's the `newspack_ras_config` global – which is actually preventing the modal from opening.

https://github.com/Automattic/newspack-plugin/blob/ff256ee26865256d6817d7885fc7456e7f22d347/assets/reader-activation/index.js#L159-L160

Note that it should be included in the `globals` declaration at the top of the file.

2024-05-17 18:25 UTC, laurelfulford commented on src/modal-checkout/modal.js
> +						! loggedIn
AH! Thanks @adekbadek! I combed around for something in the Blocks like that, I should've checked the plugin. 

I've updated the PR -- just let me know if there's anything that needs adjusting!

2024-05-20 10:52 UTC, adekbadek approved these changes
👌

2024-05-20 19:40 UTC, merged