Fix/add product summary card to auth flow
Automattic/newspack-blocks pull request #1751
Opened 2024-05-28 03:33 UTC by chickenn00dle

### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes https://app.asana.com/0/1206943664367857/1207328906416559/f

This PR adds the product price summary card to the auth flow:

![Screenshot 2024-05-27 at 23 32 41](https://github.com/Automattic/newspack-blocks/assets/17905991/eb4b14c6-bdb9-4776-896b-8f2bb5603756)

### How to test the changes in this Pull Request:

TBA

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2024-05-31 20:05 UTC, dkoo requested changes
@chickenn00dle this works, but fetching the markup via REST API causes a  noticeable delay (~1-3 seconds on my local environment) when clicking the Checkout Button or submitting the Donate block.

What if we included the product details we need for this component in the hidden form fields we include in Checkout Button and Donate block forms and build the DOM elements on the fly with JS? It looks like we already include some product info here so adding some more shouldn't be a big deal if it helps us avoid a roundtrip REST API request and the delay it would cause. WDYT?

<img width="451" alt="Screenshot 2024-05-31 at 2 02 45 PM" src="https://github.com/Automattic/newspack-blocks/assets/2230142/68a1a608-c5b3-491e-934f-ab346def205d">

2024-06-04 08:01 UTC, chickenn00dle commented on src/blocks/checkout-button/view.php
> +		// Add hidden input with product price summary.
I am injecting the input as a string here. An alternative would be to move all of the render logic from `save.js` to this render callback instead. I didn't go this route since I didn't want to complicate this PR too much. But if you think it would be better, I can get a commit up for this.

2024-06-04 08:07 UTC, chickenn00dle commented
Thanks @dkoo!

> What if we included the product details we need for this component in the hidden form fields we include in Checkout Button and Donate block forms and build the DOM elements on the fly with JS? It looks like we already include some product info here so adding some more shouldn't be a big deal if it helps us avoid a roundtrip REST API request and the delay it would cause. WDYT?

My initial approach to this was this strategy but I ran into some complications with outputting the hidden inputs for price/frequency for dynamic products such as donations or variable products in general. I also didn't want to add any new attributes to the checkout button block since this would require publishers to resave their blocks. So I went with fetching via REST.

That said, I did take another stab at this, and managed to get this working without that fetch and moving the price summary content into a hidden input. Tbh, it feels a bit "hacky" to me but let me know what you think or if you have any suggestions for improvement!

2024-06-04 23:54 UTC, dkoo approved these changes
Thanks for the change in approach! It feels much snappier now. 💨

2024-06-04 23:54 UTC, dkoo commented on src/blocks/checkout-button/view.php
> +		// Add hidden input with product price summary.
I'm fine with doing it this way. I would rather every block render its content via the render callbacks instead of a `save` JS method, but that's a personal preference and beyond the scope of this PR. I also agree that `attributes` isn't the right place for this data since they're not editable block attributes.

Another non-blocking idea, if it's not too complex: we could unify the approach to appending all of these various hidden inputs. I think the others are being injected via JS right now, right?

<img width="544" alt="Screenshot 2024-06-04 at 5 44 32 PM" src="https://github.com/Automattic/newspack-blocks/assets/2230142/e2f31009-d9fc-4504-be63-7ce93e6a8ab9">

In this render callback we could build a JSON string with all of the hidden input names and values, and do a single injection as a `data-` attribute added to the wrapper div or the form element inside. Then use a `createHiddenInput` helper to create all the hidden inputs based on this data attribute.

But if that sounds too complex I'm okay with the split approach for now.

2024-06-05 05:16 UTC, chickenn00dle commented on src/blocks/checkout-button/view.php
> +		// Add hidden input with product price summary.
Thanks for the suggestion! I started working on this and realized I wasn't handling the tiered or untiered versions of the donation block 😞 

I'll go ahead and implement this strategy while I work on getting those added.

2024-06-05 10:13 UTC, chickenn00dle commented on src/blocks/checkout-button/view.php
> +		// Add hidden input with product price summary.
Alright @dkoo, this should be good for another round of review now. 

I should note that this got quite complicated as the various modes of the donation block behave inconsistently, so I'd appreciate a close look at these newer changes 🙇

2024-06-05 21:25 UTC, dkoo reviewed
Hey @chickenn00dle, thanks for catching that we missed the Tiered and Untiered layouts before. I've tested all and they're all working nicely.

Thanks also for unifying the approach for hidden inputs—given the added complexity from the various Donate block variations, I think this was the right call in the end. However, I do see that because we've changed the render output for the blocks, existing blocks are throwing validation errors in the editor:

```
Block validation: Block validation failed for `newspack-blocks/checkout-button` ( 
Object { name: "newspack-blocks/checkout-button", icon: {…}, keywords: (4) […], attributes: {…}, providesContext: {}, usesContext: [], selectors: {}, supports: {…}, styles: (2) […], variations: [], … }
 ).

Content generated by `save` function:

<div class="wp-block-newspack-blocks-checkout-button has-custom-width wp-block-button__width-100"><form><button class="wp-block-button__link has-primary-background-color has-background" type="submit">Variable subscription</button><input type="hidden" name="newspack_checkout" value="1"/><input type="hidden" name="after_success_button_label" value="Continue"/></form></div>

Content retrieved from post body:

<div class="wp-block-newspack-blocks-checkout-button has-custom-width wp-block-button__width-100"><form><button class="wp-block-button__link has-primary-background-color has-background" type="submit">Variable subscription</button><input type="hidden" name="product_id" value="433"/><input type="hidden" name="newspack_checkout" value="1"/><input type="hidden" name="is_variable" value="1"/><input type="hidden" name="after_success_button_label" value="Continue"/></form></div>
```

It doesn't prevent these blocks from working, but I wonder if it's worth refactoring the block to a dynamic block after all? Maybe in a separate PR?

2024-06-05 22:35 UTC, dkoo requested changes
Marking "changes requested" just to make it clear that we need to handle the block validation one way or another (either migrating to a dynamic block, or implementing deprecation/migration). Once we decide on an approach this can be merged to the epic if we decide to tackle that in a separate PR.

2024-06-06 05:38 UTC, chickenn00dle commented
Thanks for your patience with reviewing on this one @dkoo!

> but I wonder if it's worth refactoring the block to a dynamic block after all? Maybe in a separate PR? If not, then we'd need to implement a [block deprecation/migration](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-deprecation/) for this block content. Converting to a dynamic block seems like it would be less onerous to me, but what do you think?

Good catch on the validation errors. I went ahead and just refactored in this PR. I had some trouble replicating the functionality of `getBorderClassesAndStyles`, `getSpacingClassesAndStyles`, and `getColorClassesAndStyles` on the backend though, so ended up having to apply these styles and classes manually. Let me know if I've messed anything up there.

2024-06-17 23:24 UTC, dkoo approved these changes
@chickenn00dle thanks for the more extensive refactoring to convert the Checkout Button block to a dynamic render. I tested this on a site that had a Checkout Button block already, and although I did see an "invalid block" error in the editor after installing this branch, the block still worked on the front-end both before and after block recovery (and the recovery succeeded). I'll approve this, but let's keep an eye on things and make sure to add a note about this to the testing plan.

2024-06-18 15:29 UTC, chickenn00dle commented
Thanks @dkoo!

> but let's keep an eye on things and make sure to add a note about this to the testing plan.

I've added a note for this here: 1wlwA6SAL0B8leDQ5yrb-cHrQCxOBB4X4ReM6T5zdKPo-gdoc

2024-06-18 15:29 UTC, merged