feat(ras-acc) add welcome email template for checkout registration
Automattic/newspack-blocks pull request #1754
Opened 2024-05-30 06:29 UTC by chickenn00dle

### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes https://app.asana.com/0/1207385073694403/1205250932343413/f

This adds a new welcome email template for readers who register via checkout.

### How to test the changes in this Pull Request:

TBA

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2024-06-04 23:10 UTC, dkoo requested changes
Working well! Just left a couple of comments related to this feature needing to work for non-donation transactions as well.

2024-06-04 23:10 UTC, dkoo commented on includes/class-modal-checkout.php
> +		if ( ! $is_newspack_checkout && ! $is_newspack_donate ) {
Don't we want welcome emails to be sent for all transactions, not just donations?

2024-06-04 23:10 UTC, dkoo commented on includes/class-modal-checkout.php
> +		if ( $is_newspack_checkout ) {
Probably a redundant check if not changing the condition on line 163

2024-06-04 23:10 UTC, dkoo commented on src/modal-checkout/modal.js
> +function createHiddenInput( name, value ) {
Nice, this was sorely needed!

2024-06-05 11:24 UTC, chickenn00dle commented on includes/class-modal-checkout.php
> +		if ( ! $is_newspack_checkout && ! $is_newspack_donate ) {
This check should be adding the flag for all transactions that go through modal checkout. Checkout button transactions have the `newspack_checkout` flag and donate block transactions have the `newpsack_donate` flag. This check just ensures we have at least one of these, otherwise we bail early.

2024-06-06 07:53 UTC, chickenn00dle commented
@dkoo, I noticed an issue with the checkout button modal checkout throwing a session expired error in some cases so added some small changes in https://github.com/Automattic/newspack-blocks/pull/1754/commits/e8cadf2cecfb93b35549a8d9e2ae5ddecd14d2ca. This should be good for another round of review.

2024-06-07 17:49 UTC, dkoo commented on includes/class-modal-checkout.php
> +		if ( ! $is_newspack_checkout && ! $is_newspack_donate ) {
I must have misread the line before because I see what you're saying. Thanks for confirming

2024-06-26 20:56 UTC, dkoo approved these changes
Seems to be working now!

2024-06-26 21:04 UTC, merged