fix(ras-acc): tweak billing, shipping columns styles
Automattic/newspack-blocks pull request #1762
Opened 2024-06-04 23:58 UTC by laurelfulford

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR makes some minor tweaks to the billing/shipping field styles in the modal checkout, to make sure they sit in even columns. 

Rather than doing a bigger overhaul of the CSS, I tried to leverage the existing classes and a bit of hacky CSS to make fields full width when they'd otherwise be filling half the space.

See 1205234045751551-as-1207477278860637

### How to test the changes in this Pull Request:

1. Start on `epic/ras-acc` and set up at least two modal checkout situations: the donate block, and a checkout button for a regular product. 
2. Run through a checkout for each; with the default settings, you'll likely have a little orphan field, like this:

![image](https://github.com/Automattic/newspack-blocks/assets/177561/3aa09656-565a-4759-b888-4029d85167b0)

3. Apply the PR and run `npm run build`.
4. Confirm that the checkout with regular settings now doesn't have a lonely field:

![image](https://github.com/Automattic/newspack-blocks/assets/177561/5c74f500-70b0-4388-98fd-cc625bf817ff)

5. Navigate to WP Admin > Newspack > Reader Revenue, and toggle off some of the billing fields in the Donate tab, then run through the Donate checkout to make sure there are no gaps.
6. Repeat step 5 a couple times to make sure there aren't weird combinations that will leave a gap. Basically anytime a field that's normally floated left or right is alone on their row, they should become full-width.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2024-06-10 06:08 UTC, chickenn00dle requested changes
Nice! Works as expected. I left a comment for one small issue, then this should be good to go 👍

2024-06-10 06:08 UTC, chickenn00dle commented on includes/class-modal-checkout.php
> +	public static function change_phone_css_class( $fields ) {
Is there a reason we are using a separate method for this vs including this in the `woocommerce_checkout_fields` method above?

If not, I would suggest moving it there. Otherwise, we should probably add an `is_modal_checkout` check to make sure we are only applying this for modal checkout.

2024-06-10 22:01 UTC, laurelfulford commented on includes/class-modal-checkout.php
> +	public static function change_phone_css_class( $fields ) {
Ha, nope! I was having a hard time getting it to work the way I expected at first, and I didn't think to go back and try to consolidate these once it was okay. 

This has been updated in [65c3711](https://github.com/Automattic/newspack-blocks/pull/1762/commits/65c3711cf2e81cf225274bef4c58163b719987ee)!

2024-06-10 22:01 UTC, laurelfulford commented
Thanks @chickenn00dle! Good call on combining the functions -- this is ready for your eyes again!

2024-06-11 01:23 UTC, chickenn00dle approved these changes
Thanks Laurel!

2024-06-11 15:37 UTC, merged