fix(ras-acc): adjust nyp suggested price variation modal markup
Automattic/newspack-blocks pull request #1764
Opened 2024-06-10 07:30 UTC by chickenn00dle

### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2024-06-11 04:24 UTC, chickenn00dle commented
@laurelfulford I'm tagging you for review as this one involves some shady style changes that I'd love your second opinion on!

2024-06-12 21:28 UTC, laurelfulford requested changes
Thanks for tackling this one @chickenn00dle! My feedback is 100% super-nitpicky:

The negative margin gets the spacing super close, but it's not quite 1:1 with how the absolutely positioning gets things for the Sale price -- the top line lines up, but everything else is 2px off:

![nyp](https://github.com/Automattic/newspack-blocks/assets/177561/39a3b5d0-a5cf-454b-b30a-ae26622c6299)

(Told you it was going to be nitpicky!). 

We're probably going to struggle to get it 1:1 with the different approaches, but if we wanted to use absolute positioning here as well, it looks like the NYP plugin has a filter for that price, `wc_nyp_suggested_price_html`. 

I tested it out with some _super_ clunky HTML, but something like this would let us wrap the 'Suggested price' text in its own `span` with the CSS class `.suggested-prefix`, which could then be used to absolutely position the text the same way as the [sale price](https://github.com/Automattic/newspack-blocks/blob/epic/ras-acc/src/modal-checkout/modal.scss#L191-L197):

```
add_filter( 'wc_nyp_suggested_price_html', [ __CLASS__, 'update_suggested_price_html' ], 10, 2 );

... 

public static function update_suggested_price_html( $html, $product ) {
	$html = str_replace( '<span class="suggested-text">', '<span class="suggested-text"><span class="suggested-prefix">', $html );
	$html = str_replace( '<span class="woocommerce-Price-amount amount">', '</span><span class="woocommerce-Price-amount amount">', $html );
	return $html;
}
```

I realize I'm well into the weeds, so let me know if this sounds like mega-overkill 🙂 Marking as 'request changes' but I'm happy to discuss how far we want to go with these edge cases!

2024-06-18 18:05 UTC, chickenn00dle commented on src/modal-checkout/modal.js
> +					const variationModals = document.querySelectorAll( `.${ VARIATON_MODAL_CLASS_PREFIX }` );
Added this quick fix to address a problem loading the variation modal introduced in https://github.com/Automattic/newspack-blocks/pull/1751

2024-06-18 18:06 UTC, chickenn00dle commented
Nice! Thanks for the suggestion @laurelfulford.

I went with your approach, but placed the string replacement directly in the `render_variation_selection` method since adding it to the nyp hook will result in replacing the html everywhere as opposed to just in the checkout modal: https://github.com/Automattic/newspack-blocks/pull/1764/commits/1823fb9cb6ff84446edf7833360a5e890194e0f7

I also noticed I accidentally broke the variation modal in another merged PR, so added the fix to this PR since it was just one line and this PR is related to the variation modal (see https://github.com/Automattic/newspack-blocks/pull/1764/files#r1644863617)

2024-06-21 16:00 UTC, laurelfulford approved these changes
> I went with your approach, but placed the string replacement directly in the render_variation_selection method since adding it to the nyp hook will result in replacing the html everywhere as opposed to just in the checkout modal

Ah, good catch, @chickenn00dle! 

This looks good to me -- thanks for making the changes! :shipit:

2024-06-21 16:14 UTC, merged