Block caching
Automattic/newspack-blocks pull request #1772
Opened 2024-06-14 20:28 UTC by claudiulodro

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR introduces caching for the Posts and Carousel blocks. This is off by default for now, so I can run this on a dozen or so sites for a while and make sure it's solid, and we'll switch it to on by default at some point before elections.

### How to test the changes in this Pull Request:

You'll probably want to use a WP Cloud site for testing so that you have a good object cache running, but it may work OK on your local site. It definitely shouldn't cause issues or break anything if an object cache isn't present.

1. To your wp-config add: `define( 'NEWSPACK_LOG_LEVEL', 2 );` and `define( 'NEWSPACK_CACHE_BLOCKS', true );`.
2. Visit a Page with posts blocks and/or carousel blocks. On the first visit you should see something like this for each block on the page in the logs:
```
[14-Jun-2024 19:43:33 UTC] [74084][NEWSPACK][Newspack_Blocks_Caching::debug_log]: Checking cache for: np_cached_block_f87a58c1699b8f382352a28962df71a8
[14-Jun-2024 19:43:33 UTC] [74084][NEWSPACK][Newspack_Blocks_Caching::debug_log]: Cached data not found for: np_cached_block_f87a58c1699b8f382352a28962df71a8
[14-Jun-2024 19:43:33 UTC] [74084][NEWSPACK][Newspack_Blocks_Caching::debug_log]: Caching block: np_cached_block_f87a58c1699b8f382352a28962df71a8
```
3. Refresh the page. It should load much faster but should otherwise look exactly the same. In the logs you should see something like:
```
[14-Jun-2024 19:43:33 UTC] [74084][NEWSPACK][Newspack_Blocks_Caching::debug_log]: Checking cache for: np_cached_block_ae84d66a8217d97cc4e70226086bb965
[14-Jun-2024 19:43:33 UTC] [74084][NEWSPACK][Newspack_Blocks_Caching::debug_log]: Serving cached block: np_cached_block_ae84d66a8217d97cc4e70226086bb965
```
4. Update a post. This should invalidate the cache and force a re-cache of everything.
5. Add a Posts block to a widget area (e.g. sidebar). Visit a post, observe the block gets cached. Visit a different post, observe the cached version of the block gets served. This does not happen on Pages but should happen on Posts. See the explanation of the heuristic in the code.
6. `wp cache flush` to flush the cache if you want to start from the top.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2024-06-18 13:28 UTC, adekbadek requested changes

2024-06-18 13:28 UTC, adekbadek commented on includes/class-newspack-blocks-caching.php
> +			Newspack\Logger::log( $message );
There should be a `method_exists` check here, it's not guaranteed that this code will always run alongside `newspack-plugin`.

2024-06-18 13:28 UTC, adekbadek commented on includes/class-newspack-blocks-caching.php
> +		if ( defined( 'NEWSPACK_CACHE_BLOCKS' ) && NEWSPACK_CACHE_BLOCKS ) {
Nit: the prefix should match the repository name:
```suggestion
		if ( defined( 'NEWSPACK_BLOCKS_CACHE_BLOCKS' ) && NEWSPACK_BLOCKS_CACHE_BLOCKS ) {
```

2024-06-18 13:28 UTC, adekbadek commented on includes/class-newspack-blocks-caching.php
> +		if ( $last_update_timestamp > $cached_data['timestamp_generated'] ) {
This looks like the only method of invalidating the cache is publishing or updating a post. Changes to e.g. categories would not affect the cache. On my test site, I had a block set to display posts of "Sports" category. I've then removed this category - the editor correctly displayed a hole, while the frontend was displaying the cached content:

| Editor | Frontend | 
|--------------|-----------|
| <img width="1264" alt="image" src="https://github.com/Automattic/newspack-custom-code/assets/7383192/60e39ac9-9c0d-40e5-8ec5-af72cdb894fa"> | <img width="1138" alt="image" src="https://github.com/Automattic/newspack-custom-code/assets/7383192/b59193bf-a205-4dc0-bfef-e61e17fe329b"> |
  
This is definitely an edge case, but I think there should at least be a way to reset the cache (without having to fake-update a post). Alternatively, the cache could also be invalidated on any taxonomy update (e.g. removing a tag).

2024-08-08 22:37 UTC, claudiulodro commented on includes/class-newspack-blocks-caching.php
> +			Newspack\Logger::log( $message );
Good call. Fixed in https://github.com/Automattic/newspack-blocks/pull/1772/commits/4b570413299b5c22aabf9973d59290fed8b4fcc0

2024-08-08 22:38 UTC, claudiulodro commented on includes/class-newspack-blocks-caching.php
> +		if ( defined( 'NEWSPACK_CACHE_BLOCKS' ) && NEWSPACK_CACHE_BLOCKS ) {
https://github.com/Automattic/newspack-blocks/pull/1772/commits/4b570413299b5c22aabf9973d59290fed8b4fcc0

2024-08-08 22:39 UTC, claudiulodro commented on includes/class-newspack-blocks-caching.php
> +		if ( $last_update_timestamp > $cached_data['timestamp_generated'] ) {
The latest version sort-of solves this problem by having the cache expire after 5 minutes. The overall performance is the same according to the logs, and we don't have to worry about nearly as many edge cases if they fix themselves after a few minutes.

2024-08-08 22:43 UTC, claudiulodro commented
@adekbadek sorry about the delay on the revisions! 

I've adjusted the strategy after fine-tuning the logic on some sites. Now it simply caches for 5 minutes (or however long). The check to determine when the last post was published actually created DB load sometimes, and simply expiring the cache every 5 minutes is simpler and seems to achieve the same performance.

2024-08-14 16:29 UTC, leogermani commented on includes/class-newspack-blocks-caching.php
> +				$block_attributes['parent_post'] = get_the_ID();
I have a suggestion.

Instead of adding the `parent_post` id to the mix to build the cache key, we should use it as the cache group. We could have a `global` cache group for everything, and then a `post-$ID` group for pages.

That way we can a way (a button, a CLI) to clear the cache of all blocks in a page if needed at any point. (5 minutes can feel like an eternity for a news site homepage).

And also, having the global cache group allows us to clear all blocks cache without having to clear all the cache

2024-08-14 19:19 UTC, claudiulodro commented on includes/class-newspack-blocks-caching.php
> +				$block_attributes['parent_post'] = get_the_ID();
Great suggestion! So it would be e.g. `newspack_blocks` cache group for posts and `newspack_blocks-post-123` for pages (with the appropriate post ID)?

2024-08-15 06:54 UTC, adekbadek approved these changes
Works fine in my testing. Accepting but noting that there an unresolved discussion above 👆

2024-08-16 15:36 UTC, claudiulodro commented
Note to self: On cached blocks, it would be best to still populate that global array of used posts, so that other uncached blocks on the page continue to deduplicate nicely

2024-08-28 22:41 UTC, claudiulodro commented on includes/class-newspack-blocks-caching.php
> +				$block_attributes['parent_post'] = get_the_ID();
https://github.com/Automattic/newspack-blocks/pull/1772/commits/d4a8be67c4866e513162483ef48b3fd05fec0876

2024-08-29 00:29 UTC, claudiulodro commented
I spent a couple hours trying to do the global posts array population part, so the deduplication logic works if e.g. half the posts blocks are cached and half are not, but it was pretty complicated. I'll add that part in a follow-up PR after this is merged. Should be OK though since it's a pretty rare situation and fixes itself after a couple minutes. If it looks good with the cache groups, I think this can be shipped.

2024-08-29 15:21 UTC, merged