feat: start ga4 events fresh
Automattic/newspack-blocks pull request #1819
Opened 2024-07-31 20:38 UTC by laurelfulford

### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2024-08-20 15:59 UTC, leogermani commented on src/blocks/donate/frontend/class-newspack-blocks-donate-renderer-base.php
> +		$configuration['product_data'] = wp_json_encode( $product_data );
I'm getting `PHP Warning:  Undefined variable $product_data` here

2024-08-20 15:59 UTC, leogermani commented on includes/tracking/class-data-events.php
> +				return \Newspack\Data_Events\Utils::get_order_data( $order_id, true );
If I understand this correctly, I think we need to add some checks here to only fire this event if we can identify that this is a modal checkout interaction. Otherwise it will fire for all woo status order completed events

2024-08-20 15:59 UTC, leogermani commented on includes/tracking/class-data-events.php
> +				return \Newspack\Data_Events\Utils::get_order_data( $order_id, true );
also, this `get_order_data` has some issues apparently.. we have to look into it.

2024-08-20 15:59 UTC, leogermani commented on includes/tracking/class-data-events.php
> +			$product_type = 'membership';
I'm gonna propose that we create a canonical method in the main plugin to get the product_type, so we have one source of truth on how we categorize products. More on this coming soon

2024-08-20 15:59 UTC, leogermani commented on includes/tracking/class-data-events.php
> +				return \Newspack\Data_Events\Utils::get_order_data( $order_id, true );
WHen purchasing a normal product, I don't see the event being triggered. Probably because that method returns nothing.

When it's a donation, I see there's no action or action_type params. And there was an invalid param as well

`Parameter platform_data has an invalid value. It was removed from the np_modal_checkout_interaction event.`

2024-08-20 15:59 UTC, leogermani commented on src/modal-checkout/analytics/ga4/checkout-attempt.js
> +	const payload = getEventPayload( 'checkout_attempt', {
For consistency this action should be `form_submission`

2024-08-23 01:15 UTC, laurelfulford commented on includes/tracking/class-data-events.php
> +				return \Newspack\Data_Events\Utils::get_order_data( $order_id, true );
Thanks for catching this, @leogermani!

Digging into it, it seems to be the `woocommerce_order_status_completed` that's not firing for the checkout button block, but I'm not sure why (I tested it by trying to `error_log` a string when it was fired). It seems to work fine for Donate; in testing `woocommerce_payment_complete` and `woocommerce_checkout_order_processed` both seemed to fire for both the checkout button block and donate block, but I'm not sure why.

I'll keep digging into that and the `platform_data` bit, but if anything about the hook rings a bell, let me know!

2024-08-23 01:16 UTC, laurelfulford commented on src/modal-checkout/analytics/ga4/checkout-attempt.js
> +	const payload = getEventPayload( 'checkout_attempt', {
Good call! This has been updated in [0fcf0a1](https://github.com/Automattic/newspack-blocks/pull/1819/commits/0fcf0a14ce09b79adef8407618665eafe400cccc).

2024-08-23 01:17 UTC, laurelfulford commented on src/blocks/donate/frontend/class-newspack-blocks-donate-renderer-base.php
> +		$configuration['product_data'] = wp_json_encode( $product_data );
Eep, good catch! This looks like something I left behind when trying to pass information for the Donate block -- I've removed it in [3b1b4e1](https://github.com/Automattic/newspack-blocks/pull/1819/commits/3b1b4e1b2cacd1921cb15ba441b3fbfddc914a21).

2024-08-23 22:45 UTC, laurelfulford commented on includes/tracking/class-data-events.php
> +				return \Newspack\Data_Events\Utils::get_order_data( $order_id, true );
In [a32e023](https://github.com/Automattic/newspack-blocks/pull/1819/commits/a32e023e6a316d498449697661b9bb397c156288) I updated this bit to use `[a32e023](https://github.com/Automattic/newspack-blocks/pull/1819/commits/a32e023e6a316d498449697661b9bb397c156288)` (so it fires for both the donate block and checkout button block) and added a check (possibly not a great approach) to check whether it's in a modal checkout. It seems to work but it could probably use some refining!

2024-08-28 23:26 UTC, laurelfulford commented on includes/tracking/class-data-events.php
> +				return \Newspack\Data_Events\Utils::get_order_data( $order_id, true );
Bah, this took a ridic amount of time for me to figure out, but I think the issue with `platform_data` is that I was supposed to be doing some more massaging of the data in the `handle_modal_checkout_interaction()` function for this event [here](https://github.com/Automattic/newspack-plugin/pull/3297/files#diff-3dbb459c03feab9c03a7a641babce543932c7899efccb35734cc1cbf275633e4R459-R467).

I'm working on that now, following some of the other examples there -- I originally followed the `handle_prompt_interaction()` function as an example, but in retrospect it makes sense that it didn't work as is, especially looking at the other `handle_*` functions in the file.

2024-09-04 23:39 UTC, dkoo requested changes
@laurelfulford you've done great work on a big feature set here! I have some minor suggestions and nits on first pass here, but I think @leogermani's suggestion for standardizing product type and other product info is a good one.

To answer some of the open questions:

> The "opened" action fires twice for Checkout Button blocks set to use Variable Products that the reader can select. The initial time opens the variation picker, and the second time opens the modal checkout for the product that's picked. Should there be a different `action` param for these?

I think a separate action param is appropriate for this, since it's an additional step in the conversion flow. Maybe `opened_variations`?

> When applying a coupon, the `amount` doesn't change until the form is successfully submitted (`form_submission_success`). Should this change sooner?

I think this is okay for now, unless we want to try to fire an additional event when a coupon is successfully applied and extract the total then? That could get complicated, so maybe a separate PR if needed at all. Let's confirm with @kmwilkerson that it's needed

> When changing the price via the NYP field, the `amount` doesn't change until the form is successfully submitted (`form_submission_success`). Should this change sooner?

Same answer here—we could maybe do this with an additional event when the amount is updated, but not necessary for this PR until we confirm with @kmwilkerson whether it's needed.

> What `product_id` should be captured for the Donation products. Technically there's the main Donation product, plus there's a separate product for each frequency. Right now, it (incorrectly) uses both at random points.

I would suggest using the child product ID for each frequency, since that gives us more detailed info.

2024-09-04 23:39 UTC, dkoo commented on src/blocks/checkout-button/view.php
> +		if ( $varition_id ) {
```suggestion
		if ( $variation_id ) {
```

2024-09-04 23:39 UTC, dkoo commented on includes/tracking/class-data-events.php
> +		// Reassign the IDs to make sure the product is the product and the variation is the variation.
Assigning `$variation_id` with an empty string value helps avoid a `PHP Warning:  Undefined variable $variation_id in /newspack-repos/newspack-blocks/includes/tracking/class-data-events.php on line 154` when interacting with a non-variable product. We can also simplify the check of `$product_parent_id` slightly with just one `! empty()` check.

```suggestion
		// Reassign the IDs to make sure the product is the product and the variation is the variation.
		$variation_id = '';
		if ( ! empty( $product_parent_id ) ) {
			$variation_id = $product_id;
			$product_id   = $product_parent_id;
		}
```

2024-09-04 23:39 UTC, dkoo commented on includes/tracking/class-data-events.php
> +			'currency'     => \get_woocommerce_currency(),
Probably want to be a bit defensive here just in case, since this global function is defined outside of this plugin:

```suggestion
			'currency'     => function_exists( 'get_woocommerce_currency' ) ? \get_woocommerce_currency() : 'USD',
```

2024-09-04 23:39 UTC, dkoo commented on src/blocks/checkout-button/view.php
> +		if ( method_exists( 'Newspack_Blocks\Tracking\Data_Events', 'get_product_type' ) ) {
Unlike the defensive checks for `\Newspack\` methods or global functions defined by WooCommerce, there's no real reason we need to check for the existence of these methods since they're defined by this plugin (so if this code is running, we can be certain that the other code in the plugin exists too).

```suggestion
		$product_type = \Newspack_Blocks\Tracking\Data_Events::get_product_type( $product_id );
```

2024-09-04 23:39 UTC, dkoo commented on src/blocks/donate/frontend/class-newspack-blocks-donate-renderer-base.php
> +			<input type='hidden' name='donation_currency' value='<?php echo esc_attr( \get_woocommerce_currency() ); ?>' />
Probably want to check for the existence of this woo function before calling it, and store the value in a variable above where the HTML starts. Something like

```
$currency = function_exists( 'get_woocommerce_currency' ) ? \get_woocommerce_currency() : 'USD';

2024-09-04 23:39 UTC, dkoo commented on src/modal-checkout/analytics/ga4/checkout-attempt.js
> +	const { action_type, amount, currency, product_id, product_type, recurrence, referer, variation_id } = getProductDetails( 'modal-checkout-product-details' );
In general, when defining these variables from the output of `getProductDetails`, some will probably not be included in the output. So to guard against `undefined` values being sent, we can set defaults like this (using `variation_id` as an example):

```suggestion
	const { action_type, amount, currency, product_id, product_type, recurrence, referer, variation_id = '' } = getProductDetails( 'modal-checkout-product-details' );
```

2024-09-04 23:39 UTC, dkoo commented on includes/class-modal-checkout.php
> +				'referer'    => $referer,
Nit: in general, unless we're literally calling a PHP or WP function that intentionally spells it `referer`, we should use the spelling `referrer` for consistency. This includes when using defining variable names as well as the param name in the payload.

```suggestion
				'referrer'    => $referer,
```

2024-09-05 20:26 UTC, laurelfulford commented on includes/class-modal-checkout.php
> +				'referer'    => $referer,
D'oh! I remembered [this fix](https://github.com/Automattic/newspack-plugin/pull/2917) backwards 🤦‍♀️ Thank you!

2024-09-05 20:27 UTC, laurelfulford commented
Thank you for all this great feedback, @dkoo! I especially appreciate the "whys" -- working through the changes now! 🎉

2024-09-06 23:43 UTC, laurelfulford commented
I noticed while working on this that `loaded` fires when you try to submit the checkout with an error, too -- it should only fire when the modal is opened.

2024-09-07 00:48 UTC, laurelfulford commented on src/blocks/checkout-button/view.php
> +		if ( $varition_id ) {
🤦‍♀️ This has been fixed!

2024-09-07 00:49 UTC, laurelfulford commented on includes/tracking/class-data-events.php
> +		// Reassign the IDs to make sure the product is the product and the variation is the variation.
Ah, makes sense! Added 🙂

2024-09-07 00:50 UTC, laurelfulford commented on includes/tracking/class-data-events.php
> +			'currency'     => \get_woocommerce_currency(),
Done! I added it here and the other spots I used `get_woocommerce_currency()` -- thanks!

2024-09-07 00:51 UTC, laurelfulford commented on src/blocks/checkout-button/view.php
> +		if ( method_exists( 'Newspack_Blocks\Tracking\Data_Events', 'get_product_type' ) ) {
Makes sense! This has been removed, plus any others for methods coming from this plugin -- thanks!

2024-09-07 00:51 UTC, laurelfulford commented on src/blocks/donate/frontend/class-newspack-blocks-donate-renderer-base.php
> +			<input type='hidden' name='donation_currency' value='<?php echo esc_attr( \get_woocommerce_currency() ); ?>' />
👍

2024-09-07 00:51 UTC, laurelfulford commented on src/modal-checkout/analytics/ga4/checkout-attempt.js
> +	const { action_type, amount, currency, product_id, product_type, recurrence, referer, variation_id } = getProductDetails( 'modal-checkout-product-details' );
Ahhh good call! I've added this to this file, and the others. Thanks!

2024-09-08 18:38 UTC, laurelfulford commented
Okay, I think I got everything @dkoo!

> I noticed while working on this that loaded fires when you try to submit the checkout with an error, too -- it should only fire when the modal is opened.

This issue that I found has been fixed!

> I think a separate action param is appropriate for this, since it's an additional step in the conversion flow. Maybe `opened_variations`?

> I think this is okay for now, unless we want to try to fire an additional event when a coupon is successfully applied and extract the total then? That could get complicated, so maybe a separate PR if needed at all. Let's confirm with @kmwilkerson that it's needed

Left for now!

> Same answer here—we could maybe do this with an additional event when the amount is updated, but not necessary for this PR until we confirm with @kmwilkerson whether it's needed.

Also left for now!

> I would suggest using the child product ID for each frequency, since that gives us more detailed info.

Makes sense -- this has been updated!

2024-09-08 18:50 UTC, laurelfulford commented
Thanks again for your feedback on this, @leogermani and @dkoo! 

I've marked this and the corresponding PR ready for review officially. I know we're still discussing `product_type` internally, and that can be updated in this code once it's finalized, but it would be really nice to have this in place for the beta testing to make sure the other information is tracking correctly, and can be used to build reports as expected. 

I updated a couple points in the description, one being that I removed the `console.log( payload );` from modal-checkout/analytics/ga4/utils/index.js. If needed for testing, it can be added before/after the `window.gtag( 'event', eventName, payload );` line.

2024-09-10 21:19 UTC, dkoo commented
@laurelfulford working nicely! I verified that every action, action_type, and parameter documented in the description is getting logged in GA:

<img width="311" alt="Screenshot 2024-09-10 at 3 12 50 PM" src="https://github.com/user-attachments/assets/5480bbe6-55d7-40b8-8824-df721f5a7348">

I think this is ready to merge, with the caveat that we may need a follow-up PR to address this feedback which we're still discussing internally:

> I'm gonna propose that we create a canonical method in the main plugin to get the product_type, so we have one source of truth on how we categorize products. More on this coming soon

2024-09-10 21:20 UTC, dkoo commented
Also need to resolve conflicts with the base, but after that this is good to go

2024-09-10 21:20 UTC, dkoo approved these changes

2024-09-11 15:31 UTC, dkoo approved these changes

2024-09-11 21:28 UTC, laurelfulford commented
Thanks @dkoo! Happy to see the back of this one... 

> with the caveat that we may need a follow-up PR to address this feedback which we're still discussing internally.

... mostly 😆

2024-09-11 21:28 UTC, merged