feat(donate-block): hide buttons if only one frequency is available
Automattic/newspack-blocks pull request #1853
Opened 2024-08-23 12:29 UTC by adekbadek

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

If the Donate block is set to render just one frequency, the frequency buttons section should not be displayed.

@kevinzweerink – a side effect of the single-button behavior was that the whole block was "labeled" e.g. "One Time", signalling the frequency. With this change, it will be up to the page editor to signal the frequency of the donation. I'm not sure how big of an issue that might be and how reliant people were on single-frequency donation blocks, but I assume the usage in this configuration is small. 

| Before | After | 
|--------------|-----------|
| <img width="799" alt="image" src="https://github.com/user-attachments/assets/cca07e5e-f87e-4096-a727-68be05701b40"> | <img width="811" alt="image" src="https://github.com/user-attachments/assets/2c6e27bd-93fd-402c-bc1d-40b8f1d47a36"> |

### How to test the changes in this Pull Request:

1. On `trunk`, insert a Donate block on a page and toggle "Configure manually" in the "Suggested Donations" sidebar panel
2. Leave just one frequency selected
3. Observe the frequency choosing UI is rendered, with a single button
4. Switch to this branch, reload editor & frontend – observe the selection UI is not rendered

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2024-08-23 13:31 UTC, kevinzweerink commented
Hmm, I'm a bit hesitant about this — it seems too easy for a publisher to accidentally set up something where their description doesn't match the behavior,  i.e. a donation block is set to weekly, and the publisher mistakenly adds copy above it saying "Make a one-time donation." Even if the user notices that it's actually recurring in the checkout flow, they might feel mislead and abandon the donation.

What do you think about this idea: in cases where only one frequency is selected, that title is expanded to "Make a {frequency} donation."? That way it's more clear, but removes the risk of mislabeling a recurring product.

2024-08-26 09:40 UTC, adekbadek commented
The original request from a publisher was to hide the label. WDYT about making this an option? Then a publisher can hide the label (as an explicit step) and add their own using e.g. a paragraph block above the Donate block?

2024-09-04 13:58 UTC, kevinzweerink commented
Sure, we could do that. I don't love this direction in general because I feel like it introduces more hidden functionality to the donation block, which already features a lot of configuration options that you have to know to look for. At this stage I'm not sure it makes sense to revisit the general approach though.

If we want to go ahead and implement this, here's a mockup of where I think the control should live — I would make it a toggle that appears under the tier options when only one tier is selected; this way it's clear which label will be removed.

![CleanShot 2024-09-04 at 09 51 09@2x](https://github.com/user-attachments/assets/91643d1e-255e-4ce9-9e5e-1fa2378890a0)

2024-09-10 18:37 UTC, ronchambers commented
Hi Adam and Kevin.  I was invited by Claudiu to get up to speed on a number of Newspack products and dev environment in order to help out as needed.  He recommended I give a review to a number of PRs, including this one.  

I'll provide my review here if it helps in anyway 😃 

Overall I think this is a tough one.  I understand publishers wanting to remove an unneeded label when there is only one "tab", but I also understand that it could cause a publisher to accidentally sell a frequency that the user doesn't see. 

How about the following:

I noticed there are other configurations of the Donate Block that already show a "redundant" frequency in both the tab and in the content area.  

Please see these two screenshots:

![newspack-blocks-1853-example-1](https://github.com/user-attachments/assets/da59297c-f573-441d-9147-260e1f689277)
![newspack-blocks-1853-example-2](https://github.com/user-attachments/assets/d651ab20-80f2-4f87-a030-c04c081ee58c)


So maybe this same "redundancy" can be applied to the following layouts.  This way, if there is only one tab/label and it is auto-hidden, the user can still see the frequency in the content box.  

Please see these 3 mockups:

![newspack-blocks-1853-new-1](https://github.com/user-attachments/assets/cb22aa25-2010-4894-92fb-f3ec7926bde9)
![newspack-blocks-1853-new-2](https://github.com/user-attachments/assets/763a2c36-ceda-4501-bd43-f4c014f832c1)
![newspack-blocks-1853-new-3](https://github.com/user-attachments/assets/6495c259-588e-46e6-9dd4-e1bf4214daa6)

In the end, my thoughts would be to do:

1) Keep the code in this PR that automatically hides the single tab when there is only one label/frequency. I think this is good and "makes sense" to not have an unneeded single tab.  Also I would assume (but can't confirm) that from an Accessibility point of view it's probably best to remove the single tab or at minimum remove the single tab's click-action/link so accessible browsers are not confused by a single tab that doesn't change anything when clicked. 

2) Add the redundant frequency into the block content area for the 3 "mockup" layouts above.  This will make all 5 layouts more similar in design.  Be sure to keep this new text on all screen sizes, don't hide on mobile.

3) With this approach we should be able to avoid any new toggles since I agree there is quite a bit going on in the configurations.

I hope this might help :-)

Thanks!

2024-09-19 11:26 UTC, adekbadek commented
Thanks @ronchambers ! I like the idea. WDYT @kevinzweerink ?

2024-10-07 10:35 UTC, adekbadek commented
Thanks @ronchambers! I've applied your suggestions.

2024-10-10 03:11 UTC, ronchambers commented
@adekbadek  - Thanks for these changes.  If you ever need me to QA/review sooner, feel free to let me know a deadline or ping me on slack too :-)

Overall I really like the new "per month" and "per year" labels on all the different styles.  And I really like the new sentence "Donation amount per month" and "Donation amount per year".  I also noticed that a single-tab will disappear when there is only one tab.  Awesome!

I have two pieces of feedback:

1) I noticed a small bug for the "default" style with the attached configuration.  When clicking "other" the label should be hidden/removed like in the other styles.

![donate-block-per-month-per-month](https://github.com/user-attachments/assets/f121c813-1201-4e83-a9ca-881cb5a11cb7)


2) I think we should put a label for "one-time or once" like you just did for "per month" / "per year".  For the sentence I would recommend "Donation amount (one-time)" with parenthesis.  I'll attached the idea. (I prefer the word "one-time" instead of "once" if possible...)  If it's easier to put the "()" parenthesis around the label too, that seems fine with me.

![donate-block-one-time](https://github.com/user-attachments/assets/8bdcf617-bc3f-4659-8df1-0ba6fdae8bc8)

2024-10-11 09:16 UTC, adekbadek commented
> I noticed a small bug for the "default" style with the attached configuration. […]

Good catch! Fixed in bbed5adb0610c8e050e1b7005521c404b4ed0248

> I think we should put a label for "one-time or once" like you just did for "per month" / "per year". 

I'm not a fan of how this looks. I think it's fine to assume that a donation is a one-time donation.

2024-10-14 06:15 UTC, ronchambers commented
Nice, I retested and bug is fixed.  As for adding "one-time" or "once", personally I think something is needed since users and publishers "could" get confused, but I also think what you said is reasonable in that most people would probably assume a donation is "one-time" unless stated otherwise.  So cool with me either way :-)

2024-10-15 00:24 UTC, ronchambers approved these changes
I tested the functionality and it works as described.  I did not do a code review - I just tested via the wp-admin / blocks editor.

2024-10-17 16:05 UTC, dkoo commented
@adekbadek is this ready to merge?

2024-10-23 09:12 UTC, adekbadek commented
Sorry, forgot about this one. It would use a code review on top of QA. I've asked @ronchambers on Slack.

2024-11-13 20:20 UTC, miguelpeixe requested changes
Code looks good, except for the linting questions I left inline.

The tiered block in the editor has a small misalignment on the "per month" text. On the page it looks good.

| Editor | Page |
| --- | --- |
| <img width="846" alt="image" src="https://github.com/user-attachments/assets/cbf4b775-44d3-4675-b232-6bef9f171a66"> | <img width="815" alt="image" src="https://github.com/user-attachments/assets/ed5734da-9f08-44a6-a1ad-d8b9324c7d28"> |

2024-11-13 20:20 UTC, miguelpeixe commented on webpack.config.js
> +	if ( fileExists ) {
There's some inconsistent spacing and missing `;` here.

2024-11-13 20:20 UTC, miguelpeixe commented on src/blocks/donate/view.ts
> +/**
Did we change our linting rules? This file does not follow our usual practices.

2024-11-14 09:43 UTC, adekbadek commented on webpack.config.js
> +	if ( fileExists ) {
Fixed in f40d8310cd2da2a4e8b5e851d4597e2e6bb0b33d

2024-11-14 09:44 UTC, adekbadek commented on src/blocks/donate/view.ts
> +/**
There's something odd indeed, stemming from #1774. When I format the code of a file untouched by the changes here, with the npm script, it does make edits. For example:

```
$ ./node_modules/.bin/newspack-scripts wp-scripts lint-js ./src/blocks/author-list/edit.js
-> no errors, linting is ok
$ ./node_modules/.bin/newspack-scripts wp-scripts format ./src/blocks/author-list/edit.js
-> edits are made to the file
$ ./node_modules/.bin/newspack-scripts wp-scripts lint-js ./src/blocks/author-list/edit.js
-> still no linting errors, despite the fact that the file is edited and all formatting changed
```

But that's not something introduced by this PR, so it's a subject for another discussion.

2024-11-14 09:45 UTC, adekbadek commented
> The tiered block in the editor has a small misalignment on the "per month" text. On the page it looks good.

I can't reproduce:

<img width="724" alt="image" src="https://github.com/user-attachments/assets/ee736300-9168-481b-bdec-07eb5937249a">

Can you make sure that the CSS is rebuild and [this CSS](https://github.com/Automattic/newspack-blocks/pull/1853/files#diff-4cb18c379cf8936c938c81a47912aeb3f2d6a8de7b20a201a25156f8f24c0b04R238-R245) applied (via the inspector)?

2024-11-14 12:33 UTC, miguelpeixe approved these changes
Thanks, @adekbadek! Not sure what happened there, it's rendering fine now.

2024-11-15 08:23 UTC, merged