fix(modal-checkout): optimize iframe load
Automattic/newspack-blocks pull request #1896
Opened 2024-10-08 15:34 UTC by miguelpeixe

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Introduces a new strategy to detect iframe load so it can be ready sooner. The `load` event dispatch waits for render-blocking assets to load before firing. The new strategy watches for the iframe content document to trigger when the DOM is ready.

The dequeuing strategy is now reversed so that only whitelisted assets can be enqueued. This prevents unnecessary assets from loading.

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2024-10-08 15:42 UTC, chickenn00dle commented on includes/class-modal-checkout.php
> +			'wc_',
Its not uncommon for woo extensions to utilize these prefixes for scripts, so we probably wouldn't be fully covered. That said this is definitely a more thorough approach and better than what we have now.

2024-10-08 16:15 UTC, chickenn00dle commented on src/modal-checkout/modal.js
> +		function addEvent( elem, event, fn ) {
Question: Is the reason we need to generalize adding the event listener like this related to scope?

2024-10-08 16:27 UTC, chickenn00dle reviewed
Nice! Very cool way to decouple the iframe logic from the load event. I like this approach, although it doesn't seem to take into account the transition between completing checkout and loading the thank you view. 

![Screenshot 2024-10-08 at 12 25 21](https://github.com/user-attachments/assets/355da6b7-3300-4432-9f1c-f7c47e2b723f)

I think we will need to unflag the ready state during this transition so the handler doesn't return early. Or maybe implement a new flag that triggers the complete state separately?

2024-10-08 18:22 UTC, miguelpeixe commented
> doesn't seem to take into account the transition between completing checkout and loading the thank you view.

 Oops! Thank you for catching that. That was actually because the newsletter subscription script wasn't whitelisted to be enqueued. Fix in f0972b7345e95b11b11365500e162b0225062de2

Also, the iframe resize observer failed to resize the modal after the checkout because of the new `iframe._ready` checks. I tweaked it a bit in f55c4bb4a739af8d4a6baaf1812fac0635892745 and should work now.

2024-10-08 18:23 UTC, miguelpeixe commented on src/modal-checkout/modal.js
> +		function addEvent( elem, event, fn ) {
It's meant to support <= IE8. The `addEvent` calls both `addEventListener` and the legacy `attachEvent`, but we're not doing that anywhere else so I removed in f55c4bb4a739af8d4a6baaf1812fac0635892745

2024-10-08 21:51 UTC, miguelpeixe commented
25f6118f9e95b507e410f721ab4a98a4d5269c3a removes the `init_checkout` listener and runs the `init()` directly. The Woo trigger is called on the main thread, whereas our listener is attached asynchronously (both async script tag and after `domReady`). This causes a race condition and the modal to eventually never leave the loading state.

It's safe to run the logic outside the trigger. To keep the diff reasonable, I'm maintaining the code inside an `init()` function, but we might want to remove that.

2024-10-09 15:00 UTC, chickenn00dle reviewed
Thanks for the changes @miguelpeixe!

I am running into a new issue where stripe throws the following exception when removing the init logic from the `init_checkout` event, which causes modal checkout to be stuck in a blocked state on the payment gateway step:

```
{
  "message": "We could not retrieve data from the specified Element.\n              Please make sure the Element you are attempting to use is still mounted."
}
```
This only happens when I've throttled my network speed to 3G and when going through the auth + checkout flow as a new reader, so maybe another race condition between Woo payment gateway logic and our init method? Not sure.

2024-10-09 18:35 UTC, miguelpeixe commented
I found another race condition issue with the domReady callback. It's an immediately invoked function that will not run as a domReady callback. Updated in 7dcfc124c9824c791b85ddc64fef1aa979d0cee1

2024-10-11 18:40 UTC, miguelpeixe commented on includes/class-modal-checkout.php
> -		$is_newspack_donate         = filter_input( INPUT_GET, 'newspack_donate', FILTER_SANITIZE_NUMBER_INT );
I removed this because donations are not handled here. Please let me know if I'm missing something.

2024-10-11 19:00 UTC, chickenn00dle commented on includes/class-modal-checkout.php
> -		$is_newspack_donate         = filter_input( INPUT_GET, 'newspack_donate', FILTER_SANITIZE_NUMBER_INT );
IIRC, this method will set the registration checkout flag for donations, which is why this was added. This was to set some order meta so we know whether to send a regular thank you email, or a welcome + thank you email. Maybe there is a better way to handle this now with the async cart.

2024-10-11 19:01 UTC, chickenn00dle commented on includes/class-modal-checkout.php
> +			'wc_',
I think we talked about making this filterable so that publishers can have other payment gateways if they'd like.

2024-10-11 19:08 UTC, miguelpeixe commented on includes/class-modal-checkout.php
> -		$is_newspack_donate         = filter_input( INPUT_GET, 'newspack_donate', FILTER_SANITIZE_NUMBER_INT );
Is it working? Because donation checkout requests are processed in a [different method](https://github.com/Automattic/newspack-plugin/blob/bfab5b77db7ce142c8649508cadf9c975c3c3442/includes/class-donations.php#L652). We can replicate the flag logic there.

2024-10-11 19:12 UTC, miguelpeixe commented on includes/class-modal-checkout.php
> +			'wc_',
Right! Thank you for reminding me, updated in 893a9c41576a432465ded2fc9ac84186690b0ee0

2024-10-11 19:14 UTC, miguelpeixe commented on includes/class-modal-checkout.php
> -		$is_newspack_donate         = filter_input( INPUT_GET, 'newspack_donate', FILTER_SANITIZE_NUMBER_INT );
Ah I see it works because it's before the `is_newspack_product` check. WDYT we replicate it to the donate request method?

2024-10-11 19:17 UTC, miguelpeixe commented on includes/class-modal-checkout.php
> -		$is_newspack_donate         = filter_input( INPUT_GET, 'newspack_donate', FILTER_SANITIZE_NUMBER_INT );
Hmm... Given the entire logic for the checkout registration flag lives in the blocks plugin, I see why it's better to have it there. I'll restore it.

2024-10-11 19:22 UTC, miguelpeixe commented on includes/class-modal-checkout.php
> -		$is_newspack_donate         = filter_input( INPUT_GET, 'newspack_donate', FILTER_SANITIZE_NUMBER_INT );
Updated in 35b6d59c5146f3588fe0b09316582274715809b6. I've also changed the `is_newspack_checkout` to be a guard clause for consistency.

2024-10-11 20:03 UTC, miguelpeixe commented on includes/class-modal-checkout.php
> -		$is_newspack_donate         = filter_input( INPUT_GET, 'newspack_donate', FILTER_SANITIZE_NUMBER_INT );
I just now realized that because of the new strategy, the registration flag has to be handled differently. The anonymous cart generation doesn't know if it's a registration or not. Moved in 50f0e686f1719411ec5d82946fe21077010c6e29 so [this](https://github.com/Automattic/newspack-blocks/blob/50f0e686f1719411ec5d82946fe21077010c6e29/src/modal-checkout/modal.js#L377-L384) can set the WC session var.

2024-10-11 20:12 UTC, chickenn00dle requested changes
Nice work @miguelpeixe!

This is working very nicely for the most part. It looks like I am no longer able to receive the welcome + thankyou emails for new registration checkout though. These should look like this:

![Screenshot 2024-10-11 at 15 51 49](https://github.com/user-attachments/assets/3b604c1f-8df2-4f63-97b8-5ee477c70bd4)

We use that checkout registration flag to set session data, and when the order is created set some order meta that our email logic can use to determine which thank you email to send: https://github.com/Automattic/newspack-blocks/blob/6a68ca67f9f85edb2d4fab374fa75673a353b698/includes/class-modal-checkout.php#L1703

2024-10-11 20:12 UTC, chickenn00dle commented on src/modal-checkout/modal.js
> +	 * Generate cart.
Non-blocking suggestion: Just so it's documented somewhere in the code, maybe its worth adding some further details about the need to trigger this asynchronously to avoid potential session buginess?

2024-10-11 20:12 UTC, miguelpeixe commented on src/modal-checkout/modal.js
> +	 * Generate cart.
Good call!

2024-10-11 20:13 UTC, miguelpeixe commented
Thank you for reviewing, @chickenn00dle!

>  I am no longer able to receive the welcome + thankyou emails for new registration checkout though. These should look like this

Yes! I noticed that too, I've recently pushed some changes that should address that. I commented further [here](https://github.com/Automattic/newspack-blocks/pull/1896#discussion_r1797377637)

2024-10-11 20:18 UTC, miguelpeixe commented on src/modal-checkout/modal.js
> +	 * Generate cart.
Updated in bffe9297a6a96ead84dbffb094cde3a73e0f12ff, let me know if it's clear enough

2024-10-11 20:30 UTC, chickenn00dle approved these changes
Thanks for all the changes @miguelpeixe! This is looking good now! I left one non-blocking comment but feel free to ignore that.

2024-10-11 20:30 UTC, chickenn00dle commented on src/modal-checkout/modal.js
>  	const handleModalCheckoutUrlParams = () => {
Non-blocking nit: Even though we are no longer using url params for the magic link, I think it might be worth keeping this checkoutURLParam logic so publishers can do things like craft urls in newsletters so readers can be taken directly to checkout for xyz product.

2024-10-11 20:39 UTC, miguelpeixe commented on src/modal-checkout/modal.js
>  	const handleModalCheckoutUrlParams = () => {
Good call! Restored in 21f542cc6cea76f7bdee1f881100bd7f23424564

2024-10-11 21:05 UTC, chickenn00dle approved these changes
Great. Thanks for the quick turnaround @miguelpeixe! 🙌

2024-10-11 22:02 UTC, miguelpeixe commented
Thank you for the reviews!

2024-10-11 22:03 UTC, merged