fix(ras-acc): handle recaptcha v2 errors
Automattic/newspack-blocks pull request #1912
Opened 2024-10-21 18:04 UTC by chickenn00dle

### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes https://app.asana.com/0/1207817176293825/1208344705374759/f

This PR fixes how we handle recaptcha v2 errors. The recaptcha script returns a string error which our blocks script seemed to not handle correctly. To fix this, add a try/catch when handling the error message and if jquery false to convert the string to a jquery object, we append it to a paragraph instead. We also add a new onSuccess and onError callback to the recaptcha render call.

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2024-10-21 21:11 UTC, chickenn00dle commented on src/modal-checkout/index.js
> +							$( document.body ).on( 'checkout_error', () => newspack_grecaptcha.render( $form.get(), onSuccess, onError ) );
Moved these over from the plugin script since these bits are specific to modal checkout

2024-10-21 21:12 UTC, chickenn00dle commented on src/modal-checkout/index.js
> +								$form.get( 0 ).scrollIntoView( { behavior: 'smooth' } );
Moved scrolling the form over from the plugin script since this was specific to modal checkout

2024-10-22 14:11 UTC, miguelpeixe requested changes
It's working great for the v2 invisible badge! I also tested what happens with the v2 checkbox version and I get an infinite loop of `There was an error with reCAPTCHA. Please try again.` alerts in the frontend.

Can we make this unsupported strategy fail better? It would be nice to detect that while saving the keys, but I'm not sure Google has an API for that.

Besides that, just another comment inline.

2024-10-22 14:11 UTC, miguelpeixe commented on src/modal-checkout/index.js
> +						}
I suggest a small refactor here to avoid the use of try/catch:

```js
					if ( error_message.indexOf( '<' ) !== 0 ) {
						// If error_message is not an HTML string, wrap it in a <li />.
						handleErrorItem( $( '<li />' ).append( error_message ) );
					} else if ( ! error_message.includes( '<li' ) ) {
						// If not a list, handle as a single error.
						handleErrorItem( $( error_message ) );
					} else {
						// Handle multiple errors.
						const $errors = $( error_message );
						$errors.find( 'li' ).each( function () {
							handleErrorItem( $( this ) );
						} );
					}
```

I also changed the wrapper to `<li />` so the handler doesn't have to [generate a new node](https://github.com/Automattic/newspack-blocks/blob/e7457201337fe0f7a4c80ac0a241308b57d4e502/src/modal-checkout/index.js#L242-L244).

2024-10-22 15:00 UTC, chickenn00dle commented on src/modal-checkout/index.js
> +						}
Good idea! Updated in https://github.com/Automattic/newspack-blocks/pull/1912/commits/cf06a1d509e9a7e286c11832817ec7f00840a702

2024-10-22 16:03 UTC, chickenn00dle commented
Thanks for the review @miguelpeixe!

> Can we make this unsupported strategy fail better? It would be nice to detect that while saving the keys, but I'm not sure Google has an API for that.

I also didn't see a way to detect this when saving keys, but added a retry count to the recaptcha render to prevent this infinite failure when the API keys are incorrect: https://github.com/Automattic/newspack-plugin/pull/3489/commits/18d16b460a8448417fdeab818c613d8fb8af45f4

There is still some weirdness with the modal checkout, but I think this is fine given the issue is invalid API keys and checkout will never succeed in these cases.

2024-10-22 17:27 UTC, miguelpeixe approved these changes
Thank you for revising! The retry count is a good workaround.

2024-10-22 17:46 UTC, merged