fix: override some common Custom CSS issues
Automattic/newspack-blocks pull request #1922
Opened 2024-10-24 00:04 UTC by laurelfulford

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This ended up being a pretty minor PR, but along with https://github.com/Automattic/newspack-plugin/pull/3496 it fixes some issues I noticed when testing RAS-ACC against the Custom CSS from 20 of our publisher sites. 

### How to test the changes in this Pull Request:

1. Copy the following CSS into the Additional CSS field in the Customizer -- it captures snippets of CSS that caused issues that these PRs fix.

```
h1, h2, h3, h4, h5, h6 {
	letter-spacing: 0.02em;
	text-transform: uppercase;
}

body {
	background-color: #FCF9F3;
}

.wp-block-button__link:not(.has-background),
.button, 
button, 
input[type="button"],
input[type="reset"], 
input[type="submit"], 
.wp-block-search__button-outside .wp-block-search__button {
	font-style: italic;
}

p,
li {
	font-size: 16px;
	line-height: 24px;
}

```

2. On the front-end, test a purchase flow as a not-logged in user. You'll notice some issues like:
    * Odd headings
    * Italicized buttons
    * A beige background on the modal checkout
    * Too-large footer disclaimer text.
![CleanShot 2024-10-23 at 17 02 04](https://github.com/user-attachments/assets/027e099b-ee42-4f36-a31f-5234c72fc2c5)

![CleanShot 2024-10-23 at 17 01 31](https://github.com/user-attachments/assets/557aeef1-9e03-455c-9558-d99cdb7b22cd)

3. Apply this PR and https://github.com/Automattic/newspack-plugin/pull/3496 and run `npm run build` in both.
4. Confirm that the odd issues noted above have been fixed.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2024-10-24 11:26 UTC, adekbadek requested changes
Everything except the footer size is fixed:

<img width="278" alt="image" src="https://github.com/user-attachments/assets/6a113e53-1098-4cb4-98a9-c56af1554a52">

2024-10-24 18:18 UTC, laurelfulford commented
Thanks @adekbadek! Turns out I had to make the font size classes more specific to cascade right -- should be fixed in [2e2aed3](https://github.com/Automattic/newspack-plugin/pull/3496/commits/2e2aed336f437c4ac539874e1796606f91b8ff6f) and I caught and fixed an issue with the WooPayments test credit card number picking up the button italics (which isn't anything a reader would see, but it was bugging me 😆 ). 

Just let me know if anything looks off!

2024-10-25 09:03 UTC, adekbadek approved these changes

2024-10-25 18:24 UTC, laurelfulford commented
Thanks @adekbadek 🥳

2024-10-25 18:24 UTC, merged