fix(ia): endpoint updates
Automattic/newspack-blocks pull request #1974
Opened 2024-11-26 18:52 UTC by miguelpeixe

### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2025-02-05 23:52 UTC, dkoo requested changes
Almost missed this one! I think it still needs some slight adjustments, see below.

2025-02-05 23:52 UTC, dkoo commented on src/blocks/donate/edit/index.tsx
>  					{ __( 'Go to donation settings to troubleshoot.', 'newspack-blocks' ) }
```suggestion
				<ExternalLink href="/wp-admin/admin.php?page=newspack-audience#/payment">
					{ __( 'Go to checkout & payment settings to troubleshoot.', 'newspack-blocks' ) }
```

2025-02-05 23:52 UTC, dkoo commented on src/blocks/donate/edit/index.tsx
>  					{ __( 'Go to donation settings to update the platform.', 'newspack-blocks' ) }
```suggestion
				<ExternalLink href="/wp-admin/admin.php?page=newspack-audience#/payment">
					{ __( 'Go to checkout & payment settings to update the platform.', 'newspack-blocks' ) }
```

2025-02-10 18:49 UTC, miguelpeixe commented
Thanks for catching those, @dkoo!

2025-02-10 18:55 UTC, dkoo approved these changes

2025-02-10 19:08 UTC, merged