WIP Article Block Height: Add range control for top padding (option C)
Automattic/newspack-blocks pull request #198
Opened 2019-10-31 23:14 UTC by laurelfulford

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This is another riff on #196 and #197, but rather than setting a minimum height, it sets a top padding.

It's similar to #197 in that it uses a measurement that changes with the viewport (in this case, `vw`, to better get a feel for how much that shifting affects things). 

One plus of this approach, over a minimum height, is that it doesn't fully disappear on smaller screens (even if the padding value is relatively smaller, it's always a value on top of the current height, vs. the minimum height becoming shorter than the actual height of the article, based on the content height.

See #153 

### How to test the changes in this Pull Request:

1. Apply the PR and run npm run build:webpack
2. Add an article block to a page.
3. Set the article block to use the Show media behind image position.
4. Confirm you now have a field in the Featured Image Settings labelled 'Top Padding', with a default of `0`:

![image](https://user-images.githubusercontent.com/177561/67992210-12105700-fbf9-11e9-90a2-43d9d074c963.png)

5. Try setting it to a variety of settings, and make sure they're respected on the front-end and in the editor.
6. Add a block with a taller top padding (40-50). On the front-end, try adjusting the width of the browser window and confirm that the padding on the block visually adjusts too.
7. Make sure the minimum height isn't applied to an article in the set that doesn't have a featured image.
8. Try hiding the featured image; make sure the 'Minimum height' option is hidden, and the height is no longer applied.
9. Try changing the image positioning to top, left, or right, and make sure the 'Minimum height' option is hidden, and the height is no longer applied.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?

2019-11-01 16:20 UTC, thomasguillot requested changes
I really like this option and overall it works as expected.

2019-11-01 16:20 UTC, thomasguillot commented on src/blocks/homepage-articles/view.php
> +					$styles = 'padding-top: ' . $attributes['paddingTop'] . 'vw';
Should it be `vh` instead?

2019-11-01 19:22 UTC, laurelfulford commented on src/blocks/homepage-articles/view.php
> +					$styles = 'padding-top: ' . $attributes['paddingTop'] . 'vw';
Ah, thanks Thomas! I was experimenting with the `vw` but `vh` in this case really makes more sense. Updated in aeaea27.

2019-11-03 20:45 UTC, laurelfulford commented
Closing this PR in favour of going forward with #199.

2019-11-03 20:45 UTC, closed without merging