fix: remove reCAPTCHA for Woo from modal checkout
Automattic/newspack-blocks pull request #1984
Opened 2024-12-03 20:11 UTC by laurelfulford

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR removes and dequeues code from the reCAPTCHA for WooCommerce plugin from our modal checkout.

See 1207817176293825-as-1208873550136264

Note: the way I went about removing the scripts might be terrible; it seemed kind of duplicative, but I couldn't think of a better way that didn't require spelling out each allowed script. 

### How to test the changes in this Pull Request:

1. Install reCAPTCHA for WooCommerce and enable it on your site.
2. Try running through a modal checkout; note you get an error.
3. Apply this PR.
4. Confirm that you can complete the modal checkout.
5. View source in the modal checkout and confirm you don't have anything referencing `recaptcha` from the plugin (a `g-recaptcha` div, plus the script, rcfwc.js?ver=1.0](https://lfulford.ngrok.io/wp-content/plugins/recaptcha-woo/js/rcfwc.js?ver=1.0)
6. Confirm that those elements still exist in the regular checkout and that the reCAPTCHA there doesn't throw errors.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2024-12-03 21:03 UTC, chickenn00dle requested changes

2024-12-03 21:03 UTC, chickenn00dle commented on includes/class-modal-checkout.php
> +		$skip_assets    = apply_filters( 'newspack_blocks_modal_checkout_skip_assets', $skip_assets );
Hmm, rather than adding another array for skipped assets, can we instead fix the check for `allowed_assets` below so that this script and any others with similar situations where the allowed asset string is found but the script itself is actually not expected?

2024-12-03 21:03 UTC, chickenn00dle commented on includes/class-modal-checkout.php
> +				if ( false !== strpos( $handle, $allowed_asset ) && ! in_array( $handle, $skip_assets ) ) {
See my comment above. This would be where we want to fix the check for `allowed_assets`. I think what we want to do here is ensure the `strpos` is always equal to 0 to indicate the script begins with the `allowed_asset` string rather than just existing anywhere within it.

2024-12-03 21:03 UTC, chickenn00dle commented on includes/class-modal-checkout.php
> +	public static function remove_recaptcha_hooks() {
Question: How common is this extension? It feels strange to have to account for specific 3rd party plugin hooks like this within our own plugin. It also doesn't seem very sustainable for other cases that might be impacting checkout down the line.

Is it possible to do this more dynamically using an approach similar to how we handle allowed scripts?

2024-12-03 21:30 UTC, laurelfulford commented on includes/class-modal-checkout.php
> +	public static function remove_recaptcha_hooks() {
> How common is this extension?

It's active on 28 sites now (and installed but inactive on others) -- definitely more than I would have expected! 

> Is it possible to do this more dynamically using an approach similar to how we handle allowed scripts?

Like pass a filterable array of hooks to remove? I can dig into it!

2024-12-04 00:28 UTC, laurelfulford commented
Ok I think I have everything sorted, @chickenn00dle! 

As an extra precaution, I did some error logging for the scripts/styles getting removed before and after this change, and re-added a couple -- one (the woocommerce styles one) was causing issues. I didn't see any issues caused by selectWoo, but better safe than sorry! 

For the remove_action part, I added an array with the hook and callback that can be filtered using `newspack_blocks_modal_checkout_remove_hooks`. 

Just let me know if anything needs changing -- thanks!

2024-12-04 16:09 UTC, chickenn00dle requested changes
Hmm, I tested with the changes but am still seeing the recaptcha error on my end:
![Screenshot 2024-12-04 at 10 58 59](https://github.com/user-attachments/assets/34b2ef84-3779-4ce1-b40e-8cf8dcd3a33d)

Not sure if its the same extension but I am testing with this one: https://woocommerce.com/products/recaptcha-for-woocommerce/

I also left two small comments that are non-blocking (sort of). Let me know what you think!

2024-12-04 16:09 UTC, chickenn00dle commented on includes/class-modal-checkout.php
> +				'callback' => 'rcfwc_field_checkout',
Another (non-blocking question) I had a look through the code and am seeing we have this array of fields to filter out during validation in the modal checkout js: https://github.com/Automattic/newspack-blocks/blob/f398d8c69ba1322ae0b57b28a27a5e561c3b3815/src/modal-checkout/index.js#L618-L620

For this hook, which I'm assuming is adding a checkout field, is this something that can be removed using the same strategy?

We'd still need to remove hooks associated with any backend logic of course, but if we can stick to the same strategy for bypassing field validation that'd be great!

2024-12-04 16:09 UTC, chickenn00dle commented on includes/class-modal-checkout.php
> +		$remove_list = apply_filters( 'newspack_blocks_modal_checkout_remove_hooks', $remove_list );
Another non-blocking comment. This is definitely better. But in the end we are still needing to specify the `rcfwc_` callbacks here. This is fine if this is the only one, but I can't imagine we don't run into similar issues in the future with other extensions.

I haven't dug too deep into it, but it's possible to view all hooks associated with a specific action via the `$wp_filter` global. Is it possible to do something like create an allow list of plugins, and check the added filters for the checkout processing hook(s), then remove if not in the allow list?

I'm happy to go with this quick fix specific to recaptcha for woocommerce, but really feel this should be improved so we don't have to keep accounting for one-off plugins like this.

2024-12-04 16:22 UTC, laurelfulford commented on includes/class-modal-checkout.php
> +				'callback' => 'rcfwc_field_checkout',
> For this hook, which I'm assuming is adding a checkout field, is this something that can be removed using the same strategy?

I'm not sure of the ins and outs of how this works, but it's adding a `div`, like:

`<div class="g-recaptcha" data-sitekey="6LfrhJEqAAAAAPuv8JoMdAqEM6G-TKQxc2Es_37A"></div>`

I double-checked, and it doesn't look like anything related to reCAPTCHA is included in `$form.serializeArray()`, which is what we're checking `removeFromValidation` for.

2024-12-04 16:29 UTC, laurelfulford commented on includes/class-modal-checkout.php
> +		$remove_list = apply_filters( 'newspack_blocks_modal_checkout_remove_hooks', $remove_list );
I think for now (and in the interest of getting this fixed and rolled out during alphas), my vote would be to keep it simple and revisit when we need to add more plugins 😅 I know something more abstracted would be ideal but I'm worried about cutting this too close to the wire.

2024-12-04 18:42 UTC, laurelfulford commented on includes/class-modal-checkout.php
> +		$remove_list = apply_filters( 'newspack_blocks_modal_checkout_remove_hooks', $remove_list );
I'm going to spin up a separate issue to capture this and see what I can do with it! 🙂

2024-12-04 18:42 UTC, laurelfulford commented
I've updated the code to actually work with the correct ReCaptcha for WooCommerce plugin 😆 

Anything related to the plugin should be dequeued/removed in the modal checkout, but still be present in the regular checkout. The plugin uses the prefix `i13` for scripts and elements it inserts.

2024-12-04 19:18 UTC, chickenn00dle approved these changes
Looks good. Thanks @laurelfulford

2024-12-04 19:18 UTC, chickenn00dle commented on includes/class-modal-checkout.php
> +		if ( method_exists( 'I13_Woo_Recpatcha', '__construct' ) ) {
non-blocking nit: we can just do a check for the class with `class_exists`.

2024-12-04 20:01 UTC, laurelfulford commented on includes/class-modal-checkout.php
> +		if ( method_exists( 'I13_Woo_Recpatcha', '__construct' ) ) {
Thanks Raz! Fixed in [ad577d6](https://github.com/Automattic/newspack-blocks/pull/1984/commits/ad577d6e040e72dacb494191da2166c3ec4376a3).

2024-12-04 20:04 UTC, merged