feat(homepage-articles): rename block and reorganise settings
Automattic/newspack-blocks pull request #2000
Opened 2024-12-12 16:02 UTC by thomasguillot

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

See https://github.com/Automattic/newspack-blocks/pull/1943 for details

I just a few more changes based on the feedback received in p2

### How to test the changes in this Pull Request:

See https://github.com/Automattic/newspack-blocks/pull/1943 for details

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2025-01-31 19:40 UTC, dkoo requested changes
@thomasguillot this is still really clean and the changes are much-needed and more user-friendly than before. I ran into a few very minor issues and had some non-blocking suggestions which you're welcome to dismiss if you disagree.

2025-01-31 19:40 UTC, dkoo commented on src/blocks/homepage-articles/edit.tsx
> +					{ ! showFullContent && (
**Bug:** If the display setting is "Full Post", this hides the toggle control for showing the "more" link, but if that's already toggled on, it still appears below the full post content.

To fix this I think we'd just need to change [this condition in the template](https://github.com/Automattic/newspack-blocks/blob/update/homepage-posts-block-improvements/src/blocks/homepage-articles/templates/article.php#L156) from:

```php
			if ( $post_link && ( $attributes['showReadMore'] ) ) :
```

to:

```php
			if ( $post_link && ! $attributes['showFullContent'] && $attributes['showReadMore'] ) :
```

2025-01-31 19:40 UTC, dkoo commented on src/blocks/homepage-articles/edit.tsx
> +								{ __( 'Full Post', 'newspack-blocks' ) }
Non-blocking suggestion:

```suggestion
								{ __( 'Full Content', 'newspack-blocks' ) }
```

2025-01-31 19:40 UTC, dkoo commented on src/components/editor-panels.js
>  			<CheckboxesGroup
This may be true of `trunk` too, but if you de-select all options, it behaves the same as selecting "Posts" only. Maybe we should force the checkbox for "Posts" to be selected in this scenario.

2025-01-31 19:40 UTC, dkoo commented on src/blocks/homepage-articles/edit.tsx
> +						label={ __( 'Allow duplicate stories', 'newspack-blocks' ) }
Not related to these changes, so no action needed on this. But noting so I don't forget.

If you add a Post Carousel block above the Content Loop and set both to NOT allow duplicate stories, the stories shown in the editor vs. the front-end will differ:

- In the editor, the Content Loop block will show the stories shown in the Post Carousel block
- On the front-end, the Content Loop will NOT show the stories shown in the Post Carousel block

2025-01-31 19:40 UTC, dkoo commented on src/components/autocomplete-tokenfield.js
> +					__next40pxDefaultSize
Not a requirement, but while we're touching this code, should we replace this `AutocompleteTokenField` component with the one imported from `newspack-components`? I tested this locally and it seemed to work without any issues. It results in a slightly smaller visual size for the autocomplete fields:

<img width="270" alt="Screenshot 2025-01-31 at 12 26 57 PM" src="https://github.com/user-attachments/assets/b070a268-6e94-45fd-ba7c-3789ad5da635" />

If we decide to do this, we can delete this file and its SCSS file and change the import in `query-controls.js`.

2025-01-31 19:40 UTC, dkoo commented on src/components/query-controls.js
> +						label={ __( 'Type', 'newspack-blocks' ) }
Non-blocking suggestion:

```suggestion
						label={ __( 'Mode', 'newspack-blocks' ) }
```

2025-01-31 19:40 UTC, dkoo commented on src/blocks/homepage-articles/edit.tsx
> +								/>
Here's a suggestion that I thought of while testing this with an existing instance of the Homepage Posts block. I had forgotten I had created this instance of the block while testing #1968, so it had author-related query attributes that are no longer valid. These attributes are no longer handled by the UI, so the "Authors" field appeared blank, but it was still querying posts by CAP author terms that were stored in the block attributes, and I couldn't figure out why this was happening until I debug-logged the query arguments on the back-end. 

All this to say, maybe if any of these Content query attributes are set to something other than the defaults, we could consider showing a button to restore default settings for this panel? Otherwise, the only way to fix a scenario like the above is to delete and recreate the block (losing all other display-related or style attributes you had set), or enter Code mode and delete the invalid attributes (no one but developers would probably be comfortable doing this). WDYT? Could be done in a separate PR if you prefer.

2025-02-06 14:32 UTC, thomasguillot commented on src/components/editor-panels.js
>  			<CheckboxesGroup
Done here: https://github.com/Automattic/newspack-blocks/pull/2000/commits/92b1e3d5d16756481036b06fd116583e13d1e9c6

Let me know if the logic/code make sense.

2025-02-06 14:33 UTC, thomasguillot commented on src/blocks/homepage-articles/edit.tsx
> +								{ __( 'Full Post', 'newspack-blocks' ) }
Unfortunately, "Content" is too long.
![Screenshot 2025-02-06 at 13 58 56@2x](https://github.com/user-attachments/assets/8060247d-94f0-4417-86b5-84fa89701fe5)

2025-02-06 14:34 UTC, thomasguillot commented on src/blocks/homepage-articles/edit.tsx
> +								{ __( 'Full Post', 'newspack-blocks' ) }
Unless I remove "Full"?

![Screenshot 2025-02-06 at 14 33 50@2x](https://github.com/user-attachments/assets/d71f4cf5-ca9c-4a56-9ea4-e69e980eff1b)

2025-02-06 14:35 UTC, thomasguillot commented on src/blocks/homepage-articles/edit.tsx
> +					{ ! showFullContent && (
Oops! https://github.com/Automattic/newspack-blocks/pull/2000/commits/d5feefe8479875a205cbaf541e7e862fe81507b1

2025-02-06 14:36 UTC, thomasguillot commented on src/blocks/homepage-articles/edit.tsx
> +						label={ __( 'Allow duplicate stories', 'newspack-blocks' ) }
This should probably be its own issue?

2025-02-06 14:40 UTC, thomasguillot commented on src/components/autocomplete-tokenfield.js
> +					__next40pxDefaultSize
I think I'd want to revist the `AutocompleteTokenField` from `newspack-components` first. It's probably slightly outdated (enhanced why it doesn't support `__next40pxDefaultSize`)

2025-02-06 14:45 UTC, thomasguillot commented on src/blocks/homepage-articles/edit.tsx
> +								/>
I have a list of enhancements:

* When using the Query Loop type, place the Filters (Authors, Categories, etc.) in a [ToolsPanel](https://href.li/?https://wordpress.github.io/gutenberg/?path=/docs/components-experimental-toolspanel--docs) (similar to the Query block). This would allow users to select only the filters they need and make resetting easier.
* Add background color support to the block
* Support typography settings instead of the custom Type Scale setting
* Replace the Grid Spacing with Core’s Block Spacing
* Use [ToggleGroupControl](https://href.li/?https://wordpress.github.io/gutenberg/?path=/docs/components-experimental-togglegroupcontrol--docs) instead of the custom ButtonGroup I created
* Move the “Read More” link text setting inline, like the “Load more posts” button

And I think using the ToolsPanel would help restoring these settings to default.

2025-02-06 18:28 UTC, dkoo commented on src/blocks/homepage-articles/edit.tsx
> +								/>
Those enhancements sound great! Seems appropriate to tackle that in a separate PR.

2025-02-06 18:56 UTC, dkoo commented on src/blocks/homepage-articles/edit.tsx
> +						label={ __( 'Allow duplicate stories', 'newspack-blocks' ) }
Logged in `1200550061930446/1209344566417561`

2025-02-06 18:56 UTC, dkoo commented on src/blocks/homepage-articles/edit.tsx
> +								{ __( 'Full Post', 'newspack-blocks' ) }
I'm okay with keeping it "Full post" since it's clearer to me than just "Content"

2025-02-06 19:00 UTC, dkoo commented on src/components/editor-panels.js
>  			<CheckboxesGroup
Works for me!

2025-02-06 19:20 UTC, dkoo approved these changes
@thomasguillot thanks for the changes and feedback. Pre-approving this with some non-blocking suggestions—feel free to accept or reject, and merge when you decide!

2025-02-06 19:20 UTC, dkoo commented on src/components/editor-panels.js
> +const CheckboxesGroup = ( { options, values, onChange, defaultRequiredSlug } ) => {
Nit: offer a default `null` value to show that this prop isn't required

```suggestion
const CheckboxesGroup = ( { options, values, onChange, defaultRequiredSlug = null } ) => {
```

2025-02-06 19:20 UTC, dkoo commented on src/components/editor-panels.js
> +		const isDisabled = isDefaultType && !otherTypesSelected;
Nit: explicitly account for `defaultRequiredSlug` prop not being passed, and simplify check for other selected options:

```suggestion
		const isDefault = defaultRequiredSlug && slug === defaultRequiredSlug;
		const otherOptionsSelected = defaultRequiredSlug && values.some( value => value !== defaultRequiredSlug );
		const isDisabled = isDefault && ! otherOptionsSelected;
```

2025-02-06 19:20 UTC, dkoo commented on src/components/editor-panels.js
>  					onChange( cleanPostType );
Nit: tweak variable name and comment to clarify that this component can be used for data types other than post types, too (since it's used for the "additional post statuses" panel as well):

```suggestion
					const cleanOptions = [ ...new Set( values ) ];
					if ( value && cleanOptions.indexOf( slug ) === -1 ) {
						cleanOptions.push( slug );
					} else if ( ! value && cleanOptions.indexOf( slug ) > -1 ) {
						cleanOptions.splice( cleanOptions.indexOf( slug ), 1 );
					}
					// If no options would be selected, force the default required one
					if ( defaultRequiredSlug && cleanOptions.length === 0 ) {
						cleanOptions.push( defaultRequiredSlug );
					}
					onChange( cleanOptions );
```

2025-02-06 19:20 UTC, dkoo commented on src/components/editor-panels.js
>  			<CheckboxesGroup
I have some nitpicky/non-blocking suggestions below for these changes, let me know what you think

2025-02-06 21:56 UTC, thomasguillot commented
Thank you so much for your suggestions (and review), @dkoo ❤️

2025-02-06 21:56 UTC, merged