fix(modal-checkout): add custom modal checkout validation
Automattic/newspack-blocks pull request #2008
Opened 2024-12-17 22:19 UTC by chickenn00dle

### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR moves the modal checkout validation request to newspack blocks. We still call `WC_Checkout::process_checkout`, but beforehand we override the needs payment flag so that step 1 of modal checkout doesn't validate payment method (not needed at this point).

### How to test the changes in this Pull Request:

1. Smoke test modal checkout using various payment methods.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2024-12-19 02:38 UTC, laurelfulford requested changes
Thanks for tackling this, @chickenn00dle! 

I worked through all the payment gateways you listed, and the only issue I ran into is PayPal Payments now shows a "Proceed to PayPal" button: 

![CleanShot 2024-12-18 at 18 35 14](https://github.com/user-attachments/assets/80f30ce4-d182-4bcf-b031-41b0d362b330)

When I switch back to trunk, the button goes away. The Yellow button works as expected; the Proceed to PayPal button technically works, but it's kind of weird - it loads the form inside of the checkout modal, and then redirects to a full screen to authenticate, then into a non-modal order confirmation. 

Just let me know if this doesn't match what you're seeing and I'll see if I can recreate it elsewhere!

2024-12-19 19:33 UTC, chickenn00dle commented
Thanks for the review @laurelfulford!

> When I switch back to trunk, the button goes away. The Yellow button works as expected; the Proceed to PayPal button technically works, but it's kind of weird - it loads the form inside of the checkout modal, and then redirects to a full screen to authenticate, then into a non-modal order confirmation.

Good catch! 

I was checking `$wp_script->src` when iterating through `$wp_styles` so the paypal css assets were missing 🤦 .

Fixed in https://github.com/Automattic/newspack-blocks/pull/2008/commits/93392a5d372547044f4020f1605ca601fa5a9340

2024-12-19 19:35 UTC, chickenn00dle commented on includes/class-modal-checkout.php
> +	public static function validate_checkout_request() {
@miguelpeixe, I'd love your opinion on this approach for "hijacking" the form validation from Woo. In particular, do you think its safe to rename the `woocommerce-process-checkout-nonce` on the front end, then reassign in the backend before triggering `WC_Checkout::process_checkout`?

2025-01-20 21:49 UTC, chickenn00dle commented
Seems this is no longer needed, so gonna close this one!

2025-01-20 21:49 UTC, closed without merging