fix: add supported gateways check
Automattic/newspack-blocks pull request #2009
Opened 2024-12-18 01:58 UTC by laurelfulford

### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2025-01-08 23:57 UTC, dkoo requested changes
Ran into a few minor issues here. Aside from these, the redirect is working in all test scenarios.

1. After creating a new account, when being directed to the regular checkout page the `_newspack_checkout_registration` param is still appended to the URL.

2. When logging into an existing account via OTP, if you click "Continue" without filling in the code or after entering an incorrect code, the auth modal still has a translucent overlay on it that doesn't go away:

<img width="652" alt="Screenshot 2025-01-08 at 4 27 16 PM" src="https://github.com/user-attachments/assets/e2324822-6b76-4f27-8a8c-750aa1ac0cac" />

3. If I get redirected to the regular checkout page and then hit the "back" button in my browser, the Checkout Button or Donate block remains in the "loading" state and the extra params are appended to the URL.

<img width="980" alt="Screenshot 2025-01-08 at 4 50 29 PM" src="https://github.com/user-attachments/assets/5118c920-27e2-4c77-a79c-e4f1433a06b1" />

2025-01-08 23:57 UTC, dkoo commented on src/modal-checkout/modal.js
> +		const generateNonModalCheckoutUrl = ( url ) => {
Nit: rather than relying on regex and text manipulation of the URL, a cleaner way to do this might be to not append the modal checkout-related hidden fields if there's an unsupported payment gateway.

2025-01-16 01:26 UTC, laurelfulford commented
Thanks @dkoo! 

Something else I noticed while fixing these is that the Donate Button doesn't actually animate for me unless I also have the checkout button block on the same page. When you tested this, did you have both blocks on that donate page? I've made some changes and I'm trying to rule out if it's something I've introduced or something that was already there 😅

2025-01-16 19:52 UTC, laurelfulford commented
> Something else I noticed while fixing these is that the Donate Button doesn't actually animate for me unless I also have the checkout button block on the same page.

I figured this out - I was blocking the JS file from loading due to changes I made to the Donate Block 😅 I've tweaked things so it should now work.

2025-01-16 21:00 UTC, laurelfulford commented
Thank you for testing this, @dkoo! I think everything should be fixed.

When you re-check this, I could definitely use a gut-check about the changes in [6aa043d](https://github.com/Automattic/newspack-blocks/pull/2009/commits/6aa043d78c1e51de0d142ed1b0372f2f58c73cab). This is the approach I used to fix the back button "still loading" issue -- I noticed when I started testing that, that the registration modals also would hang around when you clicked "Back". 

I ended up moving the "close" const to make it available outside of `docReady`, but I'm not sure that and the rest is the most elegant way to go about it. Any specific feedback/suggestion on this -- and the rest -- are appreciated. Thanks!

2025-01-16 21:30 UTC, dkoo commented
> When you tested this, did you have both blocks on that donate page? I've made some changes and I'm trying to rule out if it's something I've introduced or something that was already there 😅

Yes, I did have both blocks on the same testing page!

2025-01-16 22:25 UTC, dkoo approved these changes
I like the new method of not including hidden fields in the first place when they're not needed!

The Donate and Checkout Button blocks still get stuck in a "loading" state if I click back from the checkout page, but that's a minor issue and we can consider it non-blocking if we can't get it working in this PR.

2025-01-16 22:25 UTC, dkoo commented on src/modal-checkout/modal.js
> +				window.location.href = url.replace( /&?modal_checkout=1/, '' ).replace( /\?$/, '' );
Ideally we'd also prevent the `?modal_checkout=1` param from being appended too so we wouldn't need regex to strip it. It might be possible to add a condition [here](https://github.com/Automattic/newspack-blocks/blob/feat/payment-gateway-fallback/src/modal-checkout/modal.js#L178) for this, but if it adds too much complication then it's okay as-is.

2025-01-17 01:05 UTC, laurelfulford commented
Thanks @dkoo! I'm digging into the `?modal_checkout=1` bit. For the 'Back' button, can you let me know what browser etc. you're using? It seems to work for me but I feel like I'm missing something silly 🙂 Thanks!

2025-01-17 16:19 UTC, dkoo commented
> For the 'Back' button, can you let me know what browser etc. you're using?

I'm testing on Chrome

2025-01-17 22:47 UTC, laurelfulford commented
Thanks @dkoo! 

I think I've sorted out the query string issue, and I _hope_ the back button issue, too 🤞 

In retesting this, I ran into a new issue where, if you had a unsupported payment gateway enabled and then simply signed in using the button in the header, you couldn't close the modal by clicking the 'Continue' button, only the 'Close' button. That should also be fixed in [the Newspack Plugin PR that goes with this one](https://github.com/Automattic/newspack-plugin/pull/3650).

Could you please retest when you have a moment and make sure things look good to you, too? I'm kind of paranoid about introducing some weird fresh issue 😬 Thank you!

2025-01-20 21:41 UTC, dkoo approved these changes
Working great in my testing now, thanks for the fixes!

2025-01-20 22:02 UTC, laurelfulford commented
Sweet! Thanks for all the testing on this one, @dkoo!

2025-01-20 22:03 UTC, merged