Add dev centered npm scripts
Automattic/newspack-blocks pull request #224
Opened 2019-11-22 13:31 UTC by getdave

### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Building on previous work update the build scripts as follows:

1. Remove unnecessary `:webpack` qualifier on build commands
2. Make a dedicated `dev` command.
3. Make `npm start` reference the `dev` command. It's better that `start` is an alias not a command in its own right.

### How to test the changes in this Pull Request:

1. `npm start`
2. Does it run the build in watch mode?

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2019-11-22 15:00 UTC, WunderBart requested changes
Can we update the [readme](https://github.com/Automattic/newspack-blocks/blob/master/README.md) too, please? Otherwise, it looks good! 👍

2019-11-22 16:12 UTC, getdave commented
@WunderBart Docs updated.

2019-11-22 16:15 UTC, WunderBart commented on README.md
> +To generate a build of the current blocks, run `npm run build:webpack`.
I guess this would be now `npm run build`?

2019-11-22 16:29 UTC, WunderBart approved these changes
:shipit:

2019-11-25 00:05 UTC, jeffersonrabb approved these changes
Looks good, thanks for doing this!

2019-11-25 00:05 UTC, merged

2019-11-25 09:20 UTC, getdave commented
Ah was wondering where this PR went. Thanks for closing it 👍