WiP: Bring back More button (with AMP support)
Automattic/newspack-blocks pull request #226
Opened 2019-11-25 12:11 UTC by WunderBart

This is a rebased version of https://github.com/Automattic/newspack-blocks/pull/217 with removed commits that introduced the Mustache template. We've decided to continue the approach of reusing existing PHP render function and compile post's HTML into the newly created endpoint response, as planned originally.

2019-11-25 18:01 UTC, WunderBart commented
I'm having a hard time trying to use the correct layout for the [`amp-list`](https://amp.dev/documentation/examples/components/amp-list/?format=websites) element so the initial content is always rendered at full height - no fixed height, no overflow, etc. The only layout that supports that is `container`, but it's not supported as an initial layout (?). It can be switched to via the `is-layout-container` attribute, but it has to use [`amp-bind`](https://amp.dev/documentation/components/amp-bind/) to do it. AFAIK, value binding can happen only by manual trigger (like a button click), so it won't work on initial load, unfortunately.

I've found an alternative component that seems like a more suitable choice for rendering the latest posts list - the [`amp-live-list`](https://amp.dev/documentation/components/amp-live-list/). Unfortunately, it doesn't support the `Load more` functionality, only pagination 😄 

Our use-case seems to be a mix between what the `amp-list` and the `amp-live-list` are designed for. I will continue the research tomorrow but would love to get any feedback on this. Would switching to `amp-live-list` even make sense if there's no support for the "more" button?

2019-11-26 01:16 UTC, obenland commented
If we were to make all attributes first-class args to the API, we'd be able to shed the validation/saitization callbacks. We could then just pass the json file as the arguments schema and let the API handle all validation & sanitization. It would also make the `page` argument a little less special and have it just be part of the other query args. Yay/nay?

2019-11-26 15:59 UTC, WunderBart commented
After spending some time on the documentation and trying out various configurations for the `amp-list` component, it turns out that it doesn't support dynamic resizing on page load. What that means, is that it requires a fixed height value to be provided for every layout it supports.

I'm considering it a blocker at this point as the content we want to render has variable height, and we'd always want to show it as is, without the `overflow` button to uncover the remaining part.

For more context on this issue, see [this huge thread](https://github.com/ampproject/amphtml/issues/10230) (and [this comment](https://github.com/ampproject/amphtml/issues/10230#issuecomment-376968125)).
_FYI, this [has been supported](https://github.com/ampproject/amphtml/pull/16564) at some point in the past, but it [got rid of due to some issues it caused](https://github.com/ampproject/amphtml/issues/18849)._

Even if we'd be able to use the `amp-list` component (e.g. when the `container` layout gets supported on page-load), there's another thing that would need addressing - The `list` wrapper `div` doesn't accept extra class-names and cannot be opted-out (it's being rendered even if the item's template is empty). This is how it looks: `<div role="list">{items}</div>`. This basically means that we can't use any shared/imported class-names and would have to write/copy additional CSS to keep currently applied styling.

2019-11-27 13:28 UTC, getdave requested changes
Nice start to the `view.js` for the "Load More" @WunderBart 👍 

A few refinements would be great 🥇

2019-11-27 13:28 UTC, getdave commented on src/blocks/homepage-articles/view.js
> +const loadMoreButton = document.getElementById( 'load-more-button' );
Using IDs here could be problematic if we have multiple blocks on the page. I would recommend selecting by a data attribute.

2019-11-27 13:28 UTC, getdave commented on src/blocks/homepage-articles/view.php
> +			<div id="posts-container" class="<?php echo esc_attr( $classes ); ?>" style="<?php echo esc_attr( $styles ); ?>">
Not sure we can use an `id` attr here because it should be unique in the DOM and if we have multiple Blocks on the page if won't be.

See also comment about `getElementByID()`.

2019-11-27 13:28 UTC, getdave commented on src/blocks/homepage-articles/view.js
> +  const request = new XMLHttpRequest();
We should be able to use `@wordpress/api-fetch` here which wraps the `fetch` API in browsers.

2019-11-27 13:28 UTC, getdave commented on src/blocks/homepage-articles/view.js
> +      console.log( 'Something went wrong!' );
Next step: let's display something to the user if something went wrong. Probably by displaying a human friendly notice and allowing them to try again by re-clicking the button.

2019-11-27 13:28 UTC, getdave commented on src/blocks/homepage-articles/view.js
> +      const payload = JSON.parse( request.responseText );
This will throw a SyntaxError exception if it's not valid JSON. We should wrap in `try/catch` and use a error handler to show an notice to the user.

2019-11-27 13:28 UTC, getdave commented on src/blocks/homepage-articles/view.js
> +  const postsHTML = items.map( item => item.html );
I'm confused about this code because `postsHTML` would be an **array** of HTML strings. `insertAdjacentHTML ` expects a string of text as it's second argument.

How is this even working? 😄

2019-11-27 13:28 UTC, getdave commented on src/blocks/homepage-articles/view.js
> +function renderPosts( items ) {
Can we check that when this JS is "built" it is properly "rolled up" inside a closure or something that is protecting the scope of the vars and function declarations from bleeding into the global scope?

2019-11-27 13:28 UTC, getdave commented on src/blocks/homepage-articles/view.js
> +      renderPosts( payload.items );
Could we

1. Show a loading indicator?
2. Disable the button from repeated clicks?
3. Only allow a single request at a time (via closure in code). This builds on 2 above.

2019-11-27 13:47 UTC, WunderBart commented on src/blocks/homepage-articles/view.js
> +  const postsHTML = items.map( item => item.html );
Good catch! Yeah, it stringifies it and leaves the `,` between every div. Will update 👍

2019-11-27 13:50 UTC, WunderBart commented on src/blocks/homepage-articles/view.js
> +function renderPosts( items ) {
It is wrapped as a module, so nothing gets out :)

2019-11-27 14:42 UTC, WunderBart commented on src/blocks/homepage-articles/view.js
> +      renderPosts( payload.items );
Ad 1. Should we:
   - use some existing loading component,
   - replace button's text to `Loading...` or
   - hide button and render `Loading...` text (would address no. 2 and _almost_ 3, too)?

2019-11-27 14:45 UTC, WunderBart commented on src/blocks/homepage-articles/view.js
> +      console.log( 'Something went wrong!' );
Can we use some notice component here?

2019-11-27 15:16 UTC, getdave commented on src/blocks/homepage-articles/view.js
> +      console.log( 'Something went wrong!' );
Don't think so. Just a paragraph probably. We don't have any components available like this.

2019-11-27 15:16 UTC, getdave commented on src/blocks/homepage-articles/view.js
> +      renderPosts( payload.items );
One of the later two.

2019-11-27 15:19 UTC, getdave requested changes
Some tweaks.

2019-11-27 15:19 UTC, getdave commented on src/blocks/homepage-articles/view.js
> +const postsContainer = document.querySelector( '[data-posts-container]');
These selectors should be scoped from the `loadMoreBtn`.

```
const loadMoreLoadingText = loadMoreBtn.querySelector( '[data-load-more-loading-text' );
```

If you don't do this you may select the wrong element.

2019-11-27 15:19 UTC, getdave commented on src/blocks/homepage-articles/view.js
> +  const loadMoreURL = this.getAttribute( loadMoreBtnURLAttr );
We should probably avoid `this` here if possible. Try and get a ref to the target.

2019-11-27 18:04 UTC, WunderBart commented
At this moment, the `view.js` script supports:
  - multiple instances of the `Load more` button by switching block scope,
  - basic, but user-friendly loading and error messages,
  - hiding the `Load more` button if there are no more posts to load (`next` is _falsy_).

2019-11-27 18:10 UTC, WunderBart commented on src/blocks/homepage-articles/view.js
> +    .then(( data ) => {
@getdave should we validate here if the `data` is a JSON?

2019-11-27 19:08 UTC, obenland commented on src/blocks/homepage-articles/view.php
> +				<p data-load-more-eod-text hidden><?php _e( 'No more posts to load!' ); ?></p>
Let's not show that. The lack of a load more button should be indicator enough.

2019-11-28 09:30 UTC, getdave commented on src/blocks/homepage-articles/view.php
> +				<p data-load-more-eod-text hidden><?php _e( 'No more posts to load!' ); ?></p>
Agreed 👍

2019-11-28 09:31 UTC, getdave commented on src/blocks/homepage-articles/view.js
> +    .then(( data ) => {
Yes we should. 

Additional: We could also check it conforms roughly to the schema we're expecting, namely objects containing `items` containing a `String`.

2019-11-28 10:23 UTC, getdave requested changes
Looking much better. Nice job! A few tweaks and questions. Let's discuss.

Also we need to be testing and developing against a Post containing multiple instances of this Block.

2019-11-28 10:23 UTC, getdave commented on src/blocks/homepage-articles/view.js
> +if ( page ) {
I like the event delegation approach here 👍 

Could/should we not simply delegate to the document as that is guaranteed to exist whereas the `id="page"` isn't?

2019-11-28 10:23 UTC, getdave commented on src/blocks/homepage-articles/view.js
> +	const isLoadMoreBtnClick = !!event.target.hasAttribute( loadMoreBtnURLAttr );
Do we need to check for the existence of `event.target` first?

```js
!! event.target && event.target.hasAttribute( loadMoreBtnURLAttr );
```

2019-11-28 10:23 UTC, getdave commented on src/blocks/homepage-articles/view.js
> +	if ( !loadMoreBtn || isFetching || isEndOfData ) {
My guess is we should have already guarded against `null` values of `loadMoreBtn` but I guess I make sense to be doubly cautious!

2019-11-28 10:23 UTC, getdave commented on src/blocks/homepage-articles/view.js
> +	if ( !loadMoreBtn || isFetching || isEndOfData ) {
Good to have `isEndOfData` check as well 👍

2019-11-28 10:23 UTC, getdave commented on src/blocks/homepage-articles/view.js
> +	console.log( el.outerHTML );
Let's ditch the `console` here.

2019-11-28 10:23 UTC, getdave commented on src/blocks/homepage-articles/view.js
> +				showEl( loadMoreEODText );
I think we can remove this as @obenland suggested elsewhere in his review.

2019-11-28 10:23 UTC, getdave commented on src/blocks/homepage-articles/view.js
> +			if ( data.next ) {
Minor: should we _also_ check for the `.length` here? Just in case the endpoint updates and the value is an empty string?

2019-11-28 10:23 UTC, getdave commented on src/blocks/homepage-articles/view.js
> +			renderPosts( postsContainer, data.items );
We should def validate the data is what we're expecting before we attempt to `renderPosts` here. Probably in a dedicated method.

2019-11-28 10:23 UTC, getdave commented on src/blocks/homepage-articles/view.js
> +			console.error( error );
Minor: should we only log this when in some sort of dev mode? Trying to recall if WP provides the state of `WP_DEBUG` to JS or not.

2019-11-28 10:23 UTC, getdave commented on src/blocks/homepage-articles/view.js
> +	const postsHTML = items.map( item => item.html ).join( '' );
Do you think its worth having some sort of guard here against `item.html` being undefined?

2019-11-28 10:46 UTC, getdave requested changes
Found a major bug. Essentially [one Block can stop others from loading more posts](https://cld.wthms.co/woHrMq)!

2019-11-28 10:46 UTC, getdave commented on src/blocks/homepage-articles/view.js
> +let isEndOfData = false;
**Major**: i've just realised this is a global state var. This means that if you have multiple Blocks on the page and your exhaust the posts in one Block (ie: you've loaded all the posts) then this var will Block all the other Blocks from loading more posts.

2019-11-28 10:50 UTC, getdave commented on src/blocks/homepage-articles/view.js
> +let isEndOfData = false;
Also if one Block is fetching that probably shouldn't stop other Blocks from fetching.

2019-11-28 10:52 UTC, WunderBart commented on src/blocks/homepage-articles/view.js
> +if ( page ) {
Good point. I assumed `page` is a convention and it will always be there. If there's any possibility that it will not, we should absolutely move to something higher, but I think `body` would be better than the whole document to attach the listener to in this case?

2019-11-28 11:46 UTC, getdave commented on src/blocks/homepage-articles/view.js
> +let isEndOfData = false;
Let's use closure to contain the state to a per load more button "instance" basis.

2019-11-28 11:48 UTC, getdave commented on src/blocks/homepage-articles/view.js
> +if ( page ) {
I've always used `document` on delegation. What do others think @marekhrabe @retrofox @frontdevde @obenland?

2019-11-28 11:59 UTC, WunderBart commented on src/blocks/homepage-articles/view.js
> +			if ( data.next ) {
It should be fine - `""` (empty string) is treated as false, too 👍

2019-11-28 12:08 UTC, WunderBart commented on src/blocks/homepage-articles/view.js
> +			renderPosts( postsContainer, data.items );
If the data object isn't valid it will be caught by the promise and the error message will be rendered. I think that would be the correct behaviour in such a situation?

2019-11-28 12:09 UTC, WunderBart commented on src/blocks/homepage-articles/view.js
> +let isEndOfData = false;
Great catch! Will address it in the next commit. Thanks!

2019-11-28 12:10 UTC, marekhrabe commented on src/blocks/homepage-articles/view.js
> +if ( page ) {
I think it’s smart to use more specific wrapping element for delegation but in wp world, there is no guarantee of a theme markup so I think document might be appropriate

2019-11-28 13:59 UTC, getdave requested changes
I've tested this and it now works functionality wise. Great 👍 

Some code points to tidy up.

2019-11-28 13:59 UTC, getdave commented on src/blocks/homepage-articles/view.js
> +		if ( isFetching || isEndOfData ) {
We should be able to extract the handler `function` definition outside of the event listener. That way we don't redeclare it onclick each time.

2019-11-28 13:59 UTC, getdave commented on src/blocks/homepage-articles/view.js
> +	if ( !targetEl || !items || items.length === 0 ) {
Nit: `!items.length` will have the same effect no?

2019-11-28 13:59 UTC, getdave commented on src/blocks/homepage-articles/view.js
> +	.forEach( makeLoadMoreHandler )
Missing `;`. Not sure how this getting past the linter...

2019-11-28 13:59 UTC, getdave commented on src/blocks/homepage-articles/view.php
> +				<button type="button" data-load-more-btn data-load-more-url="<?php echo $articles_rest_url ?>"><?php _e( 'Load more articles' ); ?></button>
`data-load-more-url="<?php echo $articles_rest_url ?>` needs escaping using the appropriate `esc_*` function.

2019-11-28 13:59 UTC, getdave commented on src/blocks/homepage-articles/view.js
> +				// console.error( error );
Can we remove this comment?

2019-11-28 14:22 UTC, getdave commented on src/blocks/homepage-articles/view.js
> +			renderPosts( postsContainer, data.items );
It will catch invalid JSON, but it won't necessarily match the schema (shape) of the data we're expecting.

I was just thinking we should check for a collection of `items` with an `html` prop which is a `String`.

2019-11-28 15:44 UTC, getdave commented
Just noticed a bug with https://github.com/Automattic/newspack-blocks/blob/a1a11c41ba2018ac81860192c88975390bc571f6/src/blocks/homepage-articles/edit.js#L146.

`post.title.rendered` may or may not exist. We need to test.

2019-12-02 13:45 UTC, getdave commented
## Status of this PR

* May require splitting into two PRs: one for refactor and one for the REST API work. Possibly overkill? 
* Fix some minor code hygiene points.

2019-12-03 00:08 UTC, obenland commented on src/blocks/homepage-articles/edit.js
> +							help={ __('Only available for non-AMP requests.', 'newspack-blocks') }
I worry this help text would be more confusing than helpful to the average user

2019-12-03 10:47 UTC, WunderBart commented on src/blocks/homepage-articles/edit.js
> +							help={ __('Only available for non-AMP requests.', 'newspack-blocks') }
I agree. I guess making the text less confusing is one option, but wouldn't it be even better if we just hide the whole toggle for non-AMP requests?

2019-12-03 11:33 UTC, jeffersonrabb commented on src/blocks/homepage-articles/edit.js
> +							help={ __('Only available for non-AMP requests.', 'newspack-blocks') }
This text appears in the editor and the concept of being an AMP request only really applies to the view. It's conceivable the text could be shown only if the AMP plugin is activated but that seems complex and error-prone.

2019-12-03 11:46 UTC, WunderBart commented on src/blocks/homepage-articles/edit.js
> +							help={ __('Only available for non-AMP requests.', 'newspack-blocks') }
Thanks, @jeffersonrabb - I've totally missed that fact! Keeping the text to make editors aware makes total sense.

2019-12-04 13:49 UTC, jeffersonrabb commented
Closing, as this work will continue in https://github.com/Automattic/newspack-blocks/pull/259.

2019-12-04 13:49 UTC, closed without merging