Add field for a block section header
Automattic/newspack-blocks pull request #30
Opened 2019-05-31 19:30 UTC by laurelfulford

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR adds a basic section heading to the homepage block -- it's an optional string of text that appears above the articles in the block, to help differentiate the different areas on the homepage.

With this PR I've also included some font-related variables, to be used in this block to make it easier to assign throughout; it can be moved to a more central location once we have more blocks to use it with.  

Fixes #23.

### How to test the changes in this Pull Request:

1. Apply patch.
2. Add a Homepage block to a page. 
3. Under 'Display Settings', there should now be a field labelled "Block Section Header".
4. Confirm that adding text here appears in the editor.
5. Save and publish and confirm that the text appears on the front end. 
6. Check out some other settings and make sure you don't see any weirdness (a good one is switching the block to a grid). 

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?

2019-06-03 12:31 UTC, jeffersonrabb commented
Note: https://github.com/Automattic/newspack-blocks/pull/25 has been merged into this branch, so the build script is now `build:webpack` instead of just `build`. E.G.:

`npm rum build:webpack -- --watch`

2019-06-03 12:42 UTC, jeffersonrabb requested changes
I suggest we handle this a little differently, as a `RichText` component that can be edited directly on the block as opposed to a text input in the sidebar. This is more in line with block design best practices. The Jetpack GIF block has this feature—an optional title that can be input directly on the block—so it might be a good model to look at. Some relevant code:

https://github.com/Automattic/jetpack/blob/master/extensions/blocks/gif/edit.js#L197-L210
https://github.com/Automattic/jetpack/blob/master/extensions/blocks/gif/gif.php#L63-L65

2019-06-04 00:58 UTC, laurelfulford commented
Ah I like that idea! I somehow forgot about that component between initially exploring Gutenberg, and working on this block.

I've updated the PR to use RichText component. It's set up to only show when the block is focused on, which I think is more standard for things like captions, but I'm not 100% if it's confusing in this context. Give it a spin and let me know what you think!

2019-06-04 14:49 UTC, jeffersonrabb commented on src/blocks/homepage-articles/edit.js
> +							<span>
What's the reasoning for the `<span/>` wrapper here?

2019-06-04 15:34 UTC, laurelfulford commented on src/blocks/homepage-articles/edit.js
> +							<span>
It's 100% for ease of styling :) For some of the styles I've been exploring, having another HTML element in there makes it a lot easier to pull things off. For example, line the darker border to the right edge of the text in something like this:

![image](https://user-images.githubusercontent.com/177561/58892577-57107b80-86a3-11e9-9abc-4bb6b29e1c0c.png)

I'm happy to explore another approach if this seems like overkill!

2019-06-04 16:04 UTC, laurelfulford commented
Just noting that I'm making one more change to this PR and removing the font families I added -- it makes it harder for the block to inherit styles from the theme, and it seems better to keep things simpler here so we're not fighting the styles.

2019-06-04 16:05 UTC, jeffersonrabb commented on src/blocks/homepage-articles/edit.js
> +							<span>
Here's why I ask. The `RichText` component has an optional `tagName` property that determines what the editable element will be. Using that plus `className`, you could replace all of that markup with just this, _except_ for that problematic `<span/>`:

```
<RichText
	tagName="div"
	className="article-section-title"
	onChange={ value => setAttributes( { sectionHeader: value } ) }
	placeholder={ __( 'Write header…' ) }
	value={ sectionHeader }
/>
```

2019-06-04 17:03 UTC, laurelfulford commented on src/blocks/homepage-articles/edit.js
> +							<span>
Right! Is it okay if we table this to a separate issue, and I explore other ways to handle styles like this? I added the HTML reluctantly, and would be glad to get rid of it, but I'm not sure off the top of my head the best way to approach it and still have the style flexibility.

2019-06-04 17:15 UTC, jeffersonrabb commented on src/blocks/homepage-articles/edit.js
> +							<span>
The only thing is I believe a `<div/>` within a `<span/>` is illegal markup, so it's not just a question of code brevity. Has the flexible styling been implemented somewhere? Part of why this threw me is that I don't see that styling in either of the block's stylesheets currently.

2019-06-04 17:42 UTC, laurelfulford commented on src/blocks/homepage-articles/edit.js
> +							<span>
I'm confused -- it should be a `span` inside of a `div` (which should be okay)? 

I'm working on styles for the theme right now that match the screenshot above -- it wouldn't be the block default (I'd like to keep that as simple as possible, so we don't have to override a bunch of styles).

2019-06-04 17:49 UTC, jeffersonrabb commented on src/blocks/homepage-articles/edit.js
> +							<span>
The `RichText` element renders out as an element itself (actually a tree of multiple elements). `tagName` is the way to determine what the outermost element is. Here's what the markup of what we have now looks like:

<img width="803" alt="Screen Shot 2019-06-04 at 1 47 31 PM" src="https://user-images.githubusercontent.com/1477002/58901601-850bb500-86cf-11e9-869e-5fc9d8d56c55.png">

So we have `div->span->div->div->div->div->div`

2019-06-04 17:53 UTC, laurelfulford commented on src/blocks/homepage-articles/edit.js
> +							<span>
Ohhh I see! I was matching the markup I was adding on the front end (which just ends up being `<div><span></span></div>`. Since the span would more likely than not be display inline, it seemed to make sense to use that as an element, rather than a div and setting it to display inline (which doesn't look like it'd work in the editor anyway). 

Is there a way to add multiple HTML elements to something in the editor, or is it always one? I might be able to do something hacky with the other markup there, too, but I'd like to avoid it in case it backs us into a corner later on.

2019-06-04 19:16 UTC, laurelfulford commented on src/blocks/homepage-articles/edit.js
> +							<span>
I discussed this with @jeffersonrabb, and there doesn't seem to be a great way to add this same markup structure in the editor, since there are so many other pieces to it.

For now, we've opted to remove the markup from the editor in 33ec1e0, and keep it on the front-end; I can explore ways to create a similar-ish preview for the above style in the editor. I think it will just need to have the darker grey part of the border always be the same width, but that seems like a good trade-off compared to trying to get elements of the editor markup to still work after being switched to `display: inline`.

2019-06-04 19:23 UTC, jeffersonrabb commented on src/blocks/homepage-articles/view.scss
> +<<<<<<< HEAD
Looks like an unresolved merge conflict here.

2019-06-04 21:06 UTC, laurelfulford commented on src/blocks/homepage-articles/view.scss
> +<<<<<<< HEAD
Gah, I'm not sure how I missed that one -- fixed in b119a68!

2019-06-04 21:20 UTC, jeffersonrabb approved these changes
🚢 . Nice work!

2019-06-04 21:30 UTC, laurelfulford commented
Thanks for your help on this one, @jeffersonrabb!

2019-06-04 21:30 UTC, merged