Add small screen-specific font sizes
Automattic/newspack-blocks pull request #31
Opened 2019-06-02 20:10 UTC by laurelfulford

This PR copies over some screen size variables and a `@media` mixin from the Newspack theme, and adjusts the font size for the block down depending on screen size. 

This is a partial fix for #16; the blocks still need some work on how the columns break down, to make sure that when they're multi-column, they don't get too crowded, _especially_ when they're nested inside of another block that creates column (like the default Columns block).

## To test

1. Add 8 test blocks to a page -- make each 1 article long, and give them each a different type scale value, ranging from 1 to 8. 
2. View the blocks on a desktop, tablet, and mobile sized screen.
3. Make sure the article title and avatar sizes are scaling up and down, and that nothing feels to overwhelmingly large on the smaller screens.

2019-06-03 11:55 UTC, jeffersonrabb requested changes
Looks good - I followed the testing instructions and used Browser Stack to verify on tablet and phone. I had trouble getting avatars to load in Browser Stack but I'm sure that's fully unrelated to this PR. The only issue I spotted is that at type scale 4, the avatar is actually smaller than 3. Here are the avatar sizes by type scale I'm seeing, and you can see that 4 looks like an aberration:

1 - 24x24
2 - 28x28
3 - 32x32
4 - 28x28
5 - 40x40
6 - 44x44
7 - 48x48
8 - 48x48

2019-06-03 12:08 UTC, jeffersonrabb commented
Note: https://github.com/Automattic/newspack-blocks/pull/25 has been merged into this branch, so the build script is now `build:webpack` instead of just `build`. E.G.:

`npm rum build:webpack -- --watch`

2019-06-04 01:12 UTC, laurelfulford commented
🤦‍♀ Thanks for catching that, @jeffersonrabb! The sizes have been updated so 4 shows the avatar at 36x36, makes a lot more sense in the context of that list.

2019-06-04 14:12 UTC, jeffersonrabb approved these changes
🚢 !

2019-06-04 17:44 UTC, laurelfulford commented
Thanks @jeffersonrabb!

2019-06-04 17:44 UTC, merged