Google Ad Manager block
Automattic/newspack-blocks pull request #39
Opened 2019-07-02 11:30 UTC by philipjohn

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Provides a Gutenberg block for inserting pre-defined ad inventory into the editor. Ads are pulled from the Newspack plugin where the Ads Wizard allows users to insert ad codes from Google Ad Manager.

### How to test the changes in this Pull Request:

1. Apply the patch
2. Apply [https://github.com/Automattic/newspack-plugin/pull/138]
3. Add some ads using the Google Ad Manager wizard
4. Add a new post, and add an Ad Manager block
5. Try the different ad size options
6. Check the ad code is printed on the frontend

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2019-07-04 18:08 UTC, philipjohn commented
@sonjaleix and I talked about how this block works today and decided to try a change.

When we use the Ad Manager block we give users two things:

1. Ad size in block controls
2. Ad unit in inspector controls

The ad size is purely visual, to allow the user to see the ad in the editor in the right size. If it doesn't match the size of the ad unit selected the user may end up confused as the ad unit will render in whatever size it is _supposed_ to be, not the size selected in the block control.

The ad unit code includes width and height parameters, so instead of the block control we are going to try and extract the width/height from the ad code and dynamically alter the size of the block based on the selected ad unit.

2019-07-04 19:16 UTC, sonjaleix commented
Great chat today. To add to the above, we've also discussed various approaches of how we can offer a way to support mobile ads – this has been a concern that came up during the charter meeting this week. 

We've discussed the following options we've discovered so far:

- Ad Manager has an option parameter called `data-multi-size`, that allows to pick multiple sizes (e.g. 468x60 and mobile ad banner 320x50). When testing to set up this option on the Ad Manager side, we ran into an error. It seems you can't randomly select two ad sizes, somehow they need to be "compatible" (unclear of the definition here) to each other for this option. 
- We could also borrow from the Gutenberg ads block toggle to control if a slotted ads block will display on mobile or not. This would be a work around to help editors add mobile ads

We'll be testing these options to explore which direction is most feasible and user-friendly.

2019-07-05 10:40 UTC, jeffersonrabb commented
@philipjohn could you add instructions to this PR about minimum steps to set up Ad Units in Ad Manager for testing?

2019-07-08 12:52 UTC, philipjohn commented
Thanks for the assist, @jeffersonrabb .

I've also updated the PR description with better testing instructions and sample ad codes so that it's super easy to test, as well as adding more thorough testing suggestions.

One outstanding issue: there's an issue with centre alignment. Looks like the AMP plugin might be interfering there, so looking into that. Any thoughts welcome!

2019-07-08 14:36 UTC, philipjohn commented
https://github.com/Automattic/newspack-theme/blob/eb2e43ac39fa0c421b997d5776c9aee3618f421b/styles/style-1.css#L3099-L3105

2019-07-08 14:37 UTC, philipjohn commented
> One outstanding issue: there's an issue with centre alignment. Looks like the AMP plugin might be interfering there, so looking into that. Any thoughts welcome!

Actually, it seems to be the theme. Specifically, [this code](https://github.com/Automattic/newspack-theme/blob/eb2e43ac39fa0c421b997d5776c9aee3618f421b/styles/style-1.css#L3099-L3105) so with that as a caveat, I think this PR is ready to go.

2019-07-08 20:58 UTC, sonjaleix reviewed
I've tested the ad block. 

Can't tell if you've implemented what we've discussed: adjusting the ad unit display size in the Editor based on the selected ad unit. If you have, this isn't working for me. Front-end size is displaying correctly.

The main issue I'm running into, is that it seems to only render one ad on the page, even though there are multiple ad blocks set up on a post (with different ad units for each selected). _I'm seeing some AMP conflicts in my local instance, might have something to do with it?!_

A small odd bug I ran into with the ad unit name field: 
To replicate, create an ad unit and call it "Ad 300x250". Once you've saved the ad unit and you land back on the ad units overview screen you'll see the ad unit name display as "Ad 300&#215;250". See screenshot: 
<img width="702" alt="Screenshot 2019-07-08 14 05 42" src="https://user-images.githubusercontent.com/4823744/60839281-0b615e00-a18a-11e9-859a-80820f871241.png">

2019-07-10 03:41 UTC, jeffersonrabb requested changes
Most of this PR is unused and can be deleted. There doesn't appear to be any width/height regex in this PR — I pushed a branch with a proposed approach to this (https://github.com/Automattic/newspack-blocks/compare/add/gam-block...add/gam-block+regex). Added a note about how to wrap the front-end rendered content, and a few other notes.

2019-07-10 03:41 UTC, jeffersonrabb commented on src/blocks/google-ad-manager/edit.js
> +			width: `${ activeAdData.width }px`,
Following [this PR closure](https://github.com/Automattic/newspack-plugin/pull/167#issuecomment-509213072) I don't see any dimensions extraction regex in here? 

Here's a branch with a stab at one: https://github.com/Automattic/newspack-blocks/compare/add/gam-block...add/gam-block+regex

2019-07-10 03:41 UTC, jeffersonrabb commented on src/blocks/google-ad-manager/edit.js
> +import { withState } from '@wordpress/compose';
This can be removed.

2019-07-10 03:41 UTC, jeffersonrabb commented on src/blocks/google-ad-manager/view.php
> +	return $ad_code;
This needs to be wrapped in a div with classes identifying the block and alignment. This is probably why @sonjaleix  is only seeing one ad per page, and why block alignment isn't working. Here's a suggested approach:

```suggestion
	return sprintf(
		'<div class="%s">%s</div>',
		esc_attr( Newspack_Blocks::block_classes( 'google-ad-manager', $attributes )),
		$ad_code
	);
```

2019-07-10 03:41 UTC, jeffersonrabb commented on src/blocks/google-ad-manager/editor.scss
> +.newspack-gam-ad-leaderboard .components-placeholder {
Neither of these are used anymore.

2019-07-10 03:41 UTC, jeffersonrabb commented on src/blocks/google-ad-manager/editor.scss
> +[data-type='newspack-blocks/google-ad-manager'][data-align='center'] .newspack-gam-ad {
This file can probably be much simpler. I was able to get more or less the same results with only this:

```
.newspack-gam-ad .components-placeholder {
	display: block;
	height: 100%;
	display: flex;
	min-height: 31px;
}
```

2019-07-10 03:41 UTC, jeffersonrabb commented on src/blocks/google-ad-manager/view.scss
> +@import "sass/variables";
This file looks like it was copied directly from the `homepage-articles` block. This block doesn't seem to need any view-side styling, so this can be deleted completely. You can also delete `src/blocks/google-ad-manager/view.js`. And in `src/blocks/google-ad-manager/index.js` you can remove line 16: `import './view.scss';`

2019-07-10 03:41 UTC, jeffersonrabb commented on src/blocks/google-ad-manager/sass/_mixins.scss
> +
Unused. Remove pls.

2019-07-10 03:41 UTC, jeffersonrabb commented on src/blocks/google-ad-manager/sass/_variables.scss
> +$mobile_width: 600px;
Unused. Remove pls.

2019-07-10 03:41 UTC, jeffersonrabb commented on src/blocks/google-ad-manager/view.js
> +//alert( "hello!");
This can be removed.

2019-07-10 03:41 UTC, jeffersonrabb commented on src/blocks/google-ad-manager/index.js
> +import './view.scss';
This line should be removed.

2019-07-10 15:08 UTC, philipjohn commented on src/blocks/google-ad-manager/view.php
> +	return $ad_code;
So, I'd already done this and hadn't committed and pushed :facepalm:

2019-07-10 15:23 UTC, philipjohn commented
> Can't tell if you've implemented what we've discussed: adjusting the ad unit display size in the Editor based on the selected ad unit. If you have, this isn't working for me. Front-end size is displaying correctly.

Sorry, Sonja, I think this is my fault - I was still running it locally using the API to send the sizes through which you would have been missing.

> The main issue I'm running into, is that it seems to only render one ad on the page, even though there are multiple ad blocks set up on a post (with different ad units for each selected). I'm seeing some AMP conflicts in my local instance, might have something to do with it?!

Hmm, I saw this too, once - it flashed up then disappeared. A reload of the page shows both ad units fine now though.

> To replicate, create an ad unit and call it "Ad 300x250". Once you've saved the ad unit and you land back on the ad units overview screen you'll see the ad unit name display as "Ad 300×250". See screenshot:

I'm gonna drop that into a new issue (#51) as I think it might be a bit more involved.

2019-07-10 16:52 UTC, jeffersonrabb requested changes
Left a few more comments, all pretty minor.

For the bad HTML characters @sonjaleix is seeing when there's an `x` in the Ad Unit name, let's not worry about that in this PR. We'll have to dig in, but it's probably a `newspack-plugin` issue, since the same formatting problem is seen in the Wizard.

When I test with AMP units I see what looks like a placeholder with the word "Ad". When I test with non-AMP units, I haven't seen anything. Ideally I'd like to see at least one real ad render in each environment before approving this.

2019-07-10 16:52 UTC, jeffersonrabb commented on src/blocks/google-ad-manager/editor.scss
> +.newspack-gam-ad .components-placeholder {
What would you think about centering the `Placeholder` in the block? It looks a little funny when you have a small, square unit left justified within  full-width block.

2019-07-10 16:52 UTC, jeffersonrabb commented on src/blocks/google-ad-manager/index.js
> +	keywords: [ __( 'ad' ), __( 'advert' ), __( 'ads' ), __( 'Google' ) ],
I believe there's a three keyword limit.

2019-07-10 16:52 UTC, jeffersonrabb commented on src/blocks/google-ad-manager/edit.js
> +						label={ __( 'Advert' ) }
For consistency's sake, could we use `Ad unit` here and in the placeholder?

2019-07-10 16:52 UTC, jeffersonrabb commented on src/blocks/google-ad-manager/edit.js
> +					<div className="newspack-gam-ad" style={ style }>
It would be nice to change the label if no ad has been selected. Here's a proposed approach:

```
<div className="wp-block-newspack-blocks-google-ad-manager">
					{ !! activeAdData && (
						<div className="newspack-gam-ad" style={ style }>
							<Placeholder icon={ icon } label={ __( 'Ad Unit' ) + dimensions } />
						</div>
					) }
					{ ! activeAdData && (
						<div className="newspack-gam-ad">
							<Placeholder icon={ icon } label={ __( 'Select an Ad Unit' ) } />
						</div>
					) }
				</div>
```

2019-07-10 16:52 UTC, jeffersonrabb commented on src/blocks/google-ad-manager/index.js
> +	<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
For the icon we should use the `wordpress/components` SVG components: `SVG` and `Path` (they're already imported so all you need to do is replace the tags).

2019-07-10 19:10 UTC, philipjohn commented
> When I test with AMP units I see what looks like a placeholder with the word "Ad". When I test with non-AMP units, I haven't seen anything.

Yep, there's definitely an assumption of AMP here, sorry that isn't clear. However, the improvements I've discussed with Sonja this week would change that, by providing more flexibility and adding the ability to add header code (which is needed for non-AMP ads).

2019-07-10 19:14 UTC, philipjohn commented on src/blocks/google-ad-manager/view.php
> +	if ( isset( $attributes['className'] ) ) {
Oh nice

2019-07-10 19:16 UTC, philipjohn commented on src/blocks/google-ad-manager/index.js
> +	keywords: [ __( 'ad' ), __( 'advert' ), __( 'ads' ), __( 'Google' ) ],
Ugh, so there is

2019-07-10 19:20 UTC, philipjohn commented on src/blocks/google-ad-manager/index.js
> +	<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
TIL!

2019-07-17 13:06 UTC, jeffersonrabb commented
This functionality has been extracted to a feature plugin. Closing in favor of https://github.com/Automattic/newspack-plugin/pull/184 + https://github.com/Automattic/newspack-gam.

2019-07-17 13:06 UTC, closed without merging