Feat: add support for the aside post format
Automattic/newspack-blocks pull request #591
Opened 2020-09-10 21:06 UTC by laurelfulford

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR adds support for post formats to the Homepage Posts block, and some different treatment to the Aside post format (not adding a link to the title, and displaying `the_content` rather than `the_excerpt`.

This PR needs to be tested with [Link TK]; additional information and testing steps are in that issue.

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2020-09-11 14:15 UTC, thomasguillot requested changes
![Screenshot 2020-09-11 at 15 13 34](https://user-images.githubusercontent.com/177929/92936043-8a62be00-f441-11ea-8237-4af785f80194.png)

I see the author thumbnail in the editor

2020-09-11 19:44 UTC, laurelfulford commented
Thanks Thomas! I had the author avatar turned off on my test block 🤦‍♀️ Should be fixed now!

2020-09-14 09:26 UTC, thomasguillot approved these changes
Looks good!

2020-09-15 10:47 UTC, adekbadek commented
Merging since this is approved and Laurel is AFK

2020-09-15 10:47 UTC, merged