Register Newspack Patterns like Core instead of custom solution
Automattic/newspack-blocks pull request #639
Opened 2020-12-02 15:34 UTC by thomasguillot

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR updates the way we offer our Patterns to users. Previously we used a custom solution. Now we can rely on Core's functions to offer them.

_Note: The previews for the Homepage Posts are quite slow (at least on local). Not quite sure what we can do about it._

### How to test the changes in this Pull Request:

1. Switch to this branch
2. Test all the different patterns. Do you see them, do they work?

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2020-12-02 18:30 UTC, jeffersonrabb commented
@thomasguillot did you notice if there's a way to register patterns only for certain custom post types? In the original implementation we only showed Homepage Posts patterns on Pages which made the pattern selection much cleaner in Campaigns. This is especially true given the slowness loading previews of Homepage Posts patterns.

2020-12-03 14:56 UTC, thomasguillot commented
> @thomasguillot did you notice if there's a way to register patterns only for certain custom post types? In the original implementation we only showed Homepage Posts patterns on Pages which made the pattern selection much cleaner in Campaigns. This is especially true given the slowness loading previews of Homepage Posts patterns.

Good point.
Done in https://github.com/Automattic/newspack-blocks/pull/639/commits/e415b04d639a9068ca0d89a5d5476a21205a86c4

2020-12-08 03:44 UTC, jeffersonrabb requested changes
The post type filtering isn't working quite right. When a new post/page/CPT is first created, none of the patterns are available. If the post is saved and the page refreshed, then it works (because the post ID can be extracted from the URL). Also, the mailing list patterns aren't showing up under any circumstances. I'd guess this is because `has_block()` is being called before the Mailchimp block has been registered.

2021-01-12 16:15 UTC, jeffersonrabb commented
@dkoo I'm interested to get your take on this work, as it's similar to work you've done with Newspack Listings patterns.

2021-01-12 17:00 UTC, dkoo commented
> @dkoo I'm interested to get your take on this work, as it's similar to work you've done with Newspack Listings patterns.

So the issue at question is to register block patterns only for certain post types, right? I have a solution in Listings which is kind of messy, but works for now. The problem is that block patterns must be registered pretty early on (`admin_init`), which is before functions like `get_post_type` or even the global post object are available. So in Listings, I tried getting the post type from the raw request params like so: https://github.com/Automattic/newspack-listings/pull/23/files#diff-e7aef70bd283581544beeaf8ae8ff938e3437abdf2793a22c8ac2d5b3858bacaR154-R168

Not sure if this is the best method, but it was the only way I was able to make it work.

2021-01-12 17:11 UTC, dkoo commented
@thomasguillot @jeffersonrabb I see now that this PR attempts to do the same thing I did in Listings to determine post type. I think we'll need to figure out a different method to get that info before the global `$post` object is available. `has_block` also depends on the global `$post` object, so that's probably why that function also isn't working as expected.

One thing we could try is to register block patterns for all posts to begin with, then use [`unregister_block_pattern`](https://developer.wordpress.org/block-editor/developers/block-api/block-patterns/#unregister_block_pattern_category) for the posts and post types we don't want on a later hook. That might let us run `has_block` on the content hook, too.

2021-03-09 16:50 UTC, thomasguillot commented
@dkoo @jeffersonrabb I have removed the post type check and the Mailchimp check. I'm OK having the various patterns available to all the post types. I think it's up to the user common sense.

2021-03-09 18:39 UTC, dkoo commented
@thomasguillot Sorry about the delay, I was working on 372a30d to do the selective block pattern registration by post type, but your comment beat me to it. I was having trouble with new posts until implementing 21d1821. I had to figure this out because the same issue exists in the Listings plugin. Anyway, take a look and see if it works for you. What it does:

* Moves class PHP files to an `includes` folder to match the other Newspack plugins; directory structure
* Turns the patterns file into a class for consistency
* This is the key: uses `admin_init` instead of `init` to register patterns—this hook runs a bit later than `init`, so the `$_REQUEST` params are available by then.
* Handles new posts: the `$_REQUEST['post']` param doesn't exist for those, but `$_REQUEST['post_type']` does, so we can just use that instead of trying to get the post type by a non-existent post ID.

I tested with various post types and it seems to work for me for both new posts and editing existing posts. How I tested:

1. Create a new post: confirm that the "Newspack Donations" and "Newspack Subscribe" categories and patterns exist.
2. Edit an existing post: confirm the same.
3. Create a new page: confirm that the "Newspack Homepage Posts", Newspack Donations" and "Newspack Subscribe" categories and patterns exist.
4. Edit an existing page: confirm the same.
5. Create a new prompt: confirm that the "Newspack Homepage Posts", Newspack Donations" and "Newspack Subscribe" categories and patterns exist.
6. Edit an existing prompt: confirm the same.
7. Create a new post of another CPT (such as a listing type), and confirm that none of these patterns are available.
8. Edit an existing CPT and confirm the same.

2021-03-09 18:39 UTC, dkoo commented
@jeffersonrabb or @adekbadek, could use a review from one of you since I contributed code to this PR.

2021-03-10 08:45 UTC, thomasguillot commented
It's great, I like it. Thank you @dkoo

2021-03-10 17:19 UTC, adekbadek approved these changes

2021-03-10 17:35 UTC, dkoo commented on includes/class-newspack-blocks-patterns.php
> +				( null === $post_type || in_array( $post_type, [ 'page', 'post', 'newspack_popups_cpt' ], true ) )
Good suggestion—added in 3e61bb7.

2021-03-10 17:43 UTC, adekbadek approved these changes

2021-03-11 00:42 UTC, merged