Homepage Posts block: add optional 'continue reading' link underneath excerpts
Automattic/newspack-blocks pull request #656
Opened 2020-12-17 01:59 UTC by laurelfulford

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR adds an option to add a customize-able 'Read More' link for each story on a per-post basis.

Unfortunately, current behaviour in WP.com themes could complicate this. This is a comment from me from the [original enhancement request](https://github.com/Automattic/newspack-blocks/issues/495):

> There are a number of themes that replace the [...] at the end of automatically generated excerpts with something else by filtering excerpt_more ([example](https://github.com/Automattic/themes/blob/b6ae2c8a45c2317cef960b8c0ef94da55427ffa5/textbook/inc/template-tags.php#L181-L201)). The reason the link doesn't happen with Custom Excerpts is that the [...] is not there, since it's assumed that those would end with a full stop and not need an ellipsis.

To work around this, I added a filter that should override any `entry_more` customization in the theme, switching it to `...` when the 'Read More' link is turned on, then removing the filter so it falls back to whatever a theme might be doing for blocks that have it left off. 

Closes #495

Note: I've added the 'Don't Merge' tag so some theme styles can be added for this as well (there is a bit adding an arrow already, but it could use refining); in the meantime the block uses the comment class name `more-link` on the link, so it should pick up styles from most WordPress themes that it's already getting links from.

### How to test the changes in this Pull Request:

1. Apply the PR and run `npm run build`
2. Add a homepage posts block to the editor; in the Post Control settings section, confirm there is an option to enable a 'Read More' link that is off by default. Toggle it on and confirm a field to change the read more text appears below it, with the default text "Keep reading":

![image](https://user-images.githubusercontent.com/177561/102427257-d5065000-3fc5-11eb-8ba4-b3e661d86b36.png)

3. Add 4 Homepage posts block to the editor with different configurations including:
* A block with the excerpt on and the read more link on; change the read more text.
* A block with the excerpt on, a custom excerpt length, and the read more link on.
* A block with no excerpt, and the read more link on; change the read more link text.
* A block with the excerpt on, and the read more link off. 
4. Confirm on the front end and in the editor, your settings are respected, including the different read more link text, and, when enabled, that the default `[...]` is replaced with `...`.
5. Note: on the front-end, you can see that the `.more-link` already has styles in the theme, adding an arrow; that will be updated:
![image](https://user-images.githubusercontent.com/177561/102431647-fbc58600-3fc7-11eb-8de0-539bae1d411f.png)

6. Download Varia from WordPress.com and enable it on your test site. 
7. View on the front end and confirm that Varia's custom `excerpt_more` filter ("Continue Reading") is being picked up on blocks that don't have the 'Read More' link set, but the ones with a 'Read More' link set should still be applying it. All of the links should be applying the arrow from Varia, since it also uses the `.more-link` CSS class. (Note: Varia's custom filter will not be applied in the editor, since the theme only applies it to the front-end; in that case, the blocks without the 'Read More' link enabled should still fall back to the default `[...]`):

![image](https://user-images.githubusercontent.com/177561/102428058-092e4080-3fc7-11eb-851f-cc781f4af880.png)

8. Enable the 'Load More Posts' option on the blocks, and confirm that the Read More options are being applied correctly to posts that are newly loaded, both with and without AMP enabled.
9. On the front-end, click on the Read More links to confirm they go to the correct posts. 

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2020-12-17 22:07 UTC, dkoo requested changes
Works great, except when using the "Load More" button I'm seeing 500 fatal errors like this:

```
PHP Fatal error:  Uncaught Error: Call to undefined method Newspack_Blocks::remove_excerpt_ellipsis_filter() in /Users/dkoo/Local Sites/newspack/app/public/wp-content/plugins/newspack-blocks/src/blocks/homepage-articles/class-wp-rest-newspack-articles-controller.php:103
```

I think we just need to update some method names in the API controller as suggested below. Otherwise, looks good!

2020-12-17 22:07 UTC, dkoo commented on src/blocks/homepage-articles/class-wp-rest-newspack-articles-controller.php
> +		Newspack_Blocks::filter_excerpt_ellipses( $attributes );
Looks like this doesn't match the method name in `class-newspack-blocks.php`? This works for me:

```suggestion
		Newspack_Blocks::filter_excerpt_more( $attributes );
```

2020-12-17 22:07 UTC, dkoo commented on src/blocks/homepage-articles/class-wp-rest-newspack-articles-controller.php
> +		Newspack_Blocks::remove_excerpt_ellipsis_filter();
Same issue, this doesn't match the method name in `class-newspack-blocks.php`.

```suggestion
		Newspack_Blocks::remove_excerpt_more_filter();
```

2020-12-18 00:05 UTC, laurelfulford commented
Thanks @dkoo! 

I ran into this exact issue while running though the texting steps for the PR yesterday, committed a fix in 430ffcc... and then forgot to push it up 🤦‍♀️ That update is now actually on GitHub, and not just hanging around on my local copy of the branch!

2020-12-18 16:38 UTC, dkoo approved these changes
Looks good now! :shipit:

2021-01-05 22:38 UTC, merged