Deduplication - use same store form Carousel and Homepage Posts blocks
Automattic/newspack-blocks pull request #725
Opened 2021-03-26 13:19 UTC by adekbadek

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #664 

### How to test the changes in this Pull Request:

1. On `master`, create a page with both Carousel and Homepage Posts blocks interspersed
2. Observe that posts are duplicated (in the editor and on the front-end)
3. Switch to this brach, rebuild
4. Observe there is no duplication now ✨

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2021-03-30 00:44 UTC, dkoo requested changes
A couple of very minor nits below. But also, I threw this onto my WP.com sandbox and it's not working for me when run as part of the FSE plugin. In that context, the Carousel always shows this in the editor:
 
<img width="640" alt="Screen Shot 2021-03-29 at 6 43 17 PM" src="https://user-images.githubusercontent.com/2230142/112916881-a87ecb80-90be-11eb-874c-f3f768f93547.png">

And an empty container on the front-end (speaking of which, if there are legitimately no posts to show on the front-end, we should bail before any markup is rendered).

2021-03-31 15:27 UTC, adekbadek commented on src/blocks/homepage-articles/utils.js
> +const getRandomId = () => Math.round( Math.random() * 9999 );
Why not, done in a0b7e94eddb0c49b90e9895d6c4671c53a57bdb8

2021-03-31 15:32 UTC, adekbadek commented on src/blocks/homepage-articles/view.js
> +		document.querySelector( 'div[data-current-post-id]' ).getAttribute( 'data-current-post-id' )
It'd be nice to reduce duplicattion, but `windows.newspack_blocks_data` is meant for the editor, not frontend :/ But it could be a meta tag in the head 🤔 Anyway, that's for another time IMO: https://github.com/Automattic/newspack-blocks/issues/728

2021-03-31 15:33 UTC, adekbadek commented
@dkoo 

> I threw this onto my WP.com sandbox and it's not working for me when run as part of the FSE plugin

This should fix things: https://github.com/Automattic/wp-calypso/pull/51583

2021-03-31 16:06 UTC, dkoo commented on src/blocks/homepage-articles/view.js
> +		document.querySelector( 'div[data-current-post-id]' ).getAttribute( 'data-current-post-id' )
Ah yes, you're right. Definitely a nice-to-have and not a blocker.

2021-03-31 16:06 UTC, dkoo commented on src/blocks/homepage-articles/utils.js
> +const getRandomId = () => Math.round( Math.random() * 9999 );
:nice:

2021-04-05 22:18 UTC, dkoo approved these changes
I'm going to approve this so we can handle the downstream fixes in another PR, if more work is needed.

2021-04-06 09:29 UTC, merged