feat: add carousel block attribute for slidesPerView
Automattic/newspack-blocks pull request #750
Opened 2021-05-03 23:11 UTC by dkoo

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Adds a new Post Carousel block attribute to set the number of visible slides at a time. This will effectively make each slide visually smaller.

Also fixes a dependency bug for non-AMP pages where `@wordpress/x` modules weren't being imported correctly due to the `view.js` being enqueued too early.

### How to test the changes in this Pull Request:

#### Dependency bugfix

1. On `master`, add a Post Carousel to a post or page and turn off AMP.
2. On the front-end, observe a JS console error similar to `'@wordpress/i18n' Cannot read property 'sprintf' of undefined`
3. Also observe that the swiper bullets don't update properly when changing slides.
4. Check out this branch, rebuild and refresh. Confirm that both issues are fixed.

#### New attribute

1. On this branch, create or edit a Post Carousel.
2. Under the Slideshow Settings panel, observe a new range slider for "Number of slides to show at once"
3. Confirm that the min and default is `1`
4. Confirm that the max is either:
  - The "Number of items" setting, if in query mode
  - The total number of posts returned by the query, in either query or specific posts mode
  - 6, if any of the above is more than that
5. Confirm that changing the setting updates the slider view in both the preview and on the front-end, in both AMP and non-AMP mode.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2021-05-03 23:15 UTC, dkoo commented
Note: discovered #751 while testing for this, but will work on that in a separate PR.

2021-05-04 10:20 UTC, adekbadek requested changes
The switch to `amp-base-carousel` might enable us to start using [Bento AMP, as it is a ported component](https://amp.dev/documentation/components/amp-base-carousel/?format=websites) 😎

1. The block is cropped in non-AMP & editor contexts when set to more than one slides to show at once:

![image](https://user-images.githubusercontent.com/7383192/116989724-6acf1d00-acd2-11eb-975a-0eb03d32e839.png)

2. In AMP context, something's off with the layout:

![image](https://user-images.githubusercontent.com/7383192/116989843-96ea9e00-acd2-11eb-876c-a878a0bb57a2.png)

![image](https://user-images.githubusercontent.com/7383192/116989969-c26d8880-acd2-11eb-90c7-25850bf8f93d.png)

2021-05-04 10:20 UTC, adekbadek commented on src/blocks/carousel/view.php
> +										'class'      => 'contain' === $attributes['imageFit'] ? 'image-fit-contain' : 'image-fit-cover',
I'm getting a PHP notice here: `Undefined index: imageFit` - probably because the attribute is not registered in the [block registration call](https://github.com/Automattic/newspack-blocks/blob/006e7f8eb7acfc477f167e56bf63ffa6630c4fc6/src/blocks/carousel/view.php#L343).

2021-05-04 17:55 UTC, dkoo commented on src/blocks/carousel/view.php
> +										'class'      => 'contain' === $attributes['imageFit'] ? 'image-fit-contain' : 'image-fit-cover',
Fixed in c331f21

2021-05-04 18:03 UTC, dkoo commented
> The switch to `amp-base-carousel` might enable us to start using [Bento AMP, as it is a ported component](https://amp.dev/documentation/components/amp-base-carousel/?format=websites) 😎

Nice! I haven't seen any major issues with the switch from `amp-carousel` to `amp-base-carousel`, but the latter is what lets us display multiple slides at once.

> 1. The block is cropped in non-AMP & editor contexts when set to more than one slides to show at once

The use of `position: absolute` with no fixed height on the `.entry-wrapper` element makes this hard to avoid when there are multiple slides being shown at once. It's extra unavoidable in the AMP context because of the `layout="responsive"` on the `amp-base-carousel`, which forces the slides to a specific aspect ratio (4:3).

Since the main use case of the multiple images being shown at once is sponsor logos with no `.entry-meta` content, I think we can leave this for now, and if necessary advise users to not try to cram too much content into each slide.

> 2. In AMP context, something's off with the layout:

I think c331f21 addresses the AMP styles a bit better—can you re-test?

2021-05-05 16:53 UTC, dkoo commented on src/blocks/carousel/view.php
> +										'class'      => 'contain' === $attributes['imageFit'] ? 'image-fit-contain' : 'image-fit-cover',
This was also fixed in #754, so resolved the conflict in 995f524.

2021-05-06 09:10 UTC, adekbadek requested changes

2021-05-06 09:10 UTC, adekbadek commented on src/blocks/carousel/view.php
> +			$has_link           = ! empty( $post_type_info->public ) || ! empty( $external_url ); // False if a sponsor or supporter without an external URL.
Duplicated logic (from `includes/class-newspack-blocks-api.php`) could be abstracted to a `Newspack_Blocks` method.

2021-05-06 09:10 UTC, adekbadek commented on src/blocks/carousel/view.php
> +			'<amp-base-carousel class="wp-block-newspack-carousel__amp-carousel" width="%1$s" height="3" layout="responsive" snap="true" type="slides" data-next-button-aria-label="%2$s" data-prev-button-aria-
In order to mitigate the cropping issue, how about setting the `width` to `1` and allowing the user to choose aspect ratio via an attribute that would translate to `height` (in 0-1 range)?

2021-05-06 09:11 UTC, adekbadek commented
> Since the main use case of the multiple images being shown at once is sponsor logos with no .entry-meta content, I think we can leave this for now

With the block being available in Gutenberg, I don't think we have the luxury of making such assumptions ;)

2021-05-07 00:14 UTC, dkoo commented
> With the block being available in Gutenberg, I don't think we have the luxury of making such assumptions ;)

I hear you—maybe your suggestion to make the aspect ratio a configurable attribute will help with this.

2021-05-07 00:14 UTC, dkoo commented on src/blocks/carousel/view.php
> +			'<amp-base-carousel class="wp-block-newspack-carousel__amp-carousel" width="%1$s" height="3" layout="responsive" snap="true" type="slides" data-next-button-aria-label="%2$s" data-prev-button-aria-
This is a great idea—will explore this option.

2021-05-07 20:58 UTC, dkoo commented on src/blocks/carousel/view.php
> +			$has_link           = ! empty( $post_type_info->public ) || ! empty( $external_url ); // False if a sponsor or supporter without an external URL.
Good idea! I added a helper method for this in 54d2be2.

2021-05-07 20:58 UTC, dkoo commented on includes/class-newspack-blocks.php
> +			$classes[] = 'is-amp';
Removed in 54d2be2.

2021-05-07 22:27 UTC, dkoo commented
@adekbadek, in 91e87e4 I added some new block attributes to control aspect ratio (also another simpler attribute that lets you hide the slideshow controls). Test instructions:

#### Hide controls

1. Under "Slideshow Settings", observe a new option to "Hide Controls", which is disabled by default.
2. Enable the option and confirm that the slideshow controls are visually hidden a.) in the editor preview, b.) on the front-end with AMP on, and c.) on the front-end with AMP off.

#### Aspect ratio

Note that it's still possible to create a slideshow with text that ends up overflowing the container, especially if you use a short aspect ratio such as `16:9`, but it's much easier to avoid using the options available now.

1. Under "Slideshow Settings", observe a new set of buttons to set the aspect ratio. The default value is `4:3`, which is what the AMP carousel was previously set to under all conditions.
2. Try out the various options available. Confirm that changing the option updates the aspect ratio of all the slides in the slideshow in the editor preview.
3. Test the various options on the front-end with both AMP and non-AMP. Confirm that the slides render as expected.

2021-05-12 17:10 UTC, dkoo commented
Added another feature in 3da829f: below the mobile breakpoint (600px as defined in the theme), the carousel will display a max of 2 slides (only if the attribute is set to greater than 1) in both AMP and non-AMP. This addresses publisher feedback that the slides get too visually small on mobile devices.

2021-05-13 10:24 UTC, adekbadek requested changes
Just some small tweaks needed

2021-05-13 10:24 UTC, adekbadek commented on src/blocks/carousel/view.php
> +		'data-aspect-ratio=' . $attributes['aspectRatio'],
Getting a PHP notice here: `Undefined index: aspectRatio`

2021-05-13 10:24 UTC, adekbadek commented on includes/class-newspack-blocks-api.php
> +				'post_link'                       => Newspack_Blocks::get_post_link( $post_id ),
Getting a PHP notice here: `Undefined variable: post_id`

2021-05-13 15:18 UTC, dkoo commented on src/blocks/carousel/view.php
> +		'data-aspect-ratio=' . $attributes['aspectRatio'],
Ah, forgot to register that attribute in PHP. Fixed in e484fbd.

2021-05-13 15:18 UTC, dkoo commented on includes/class-newspack-blocks-api.php
> +				'post_link'                       => Newspack_Blocks::get_post_link( $post_id ),
Good catch—fixed in e484fbd.

2021-05-13 15:23 UTC, adekbadek requested changes
I didn't notice before, sorry - in non-AMP version, the controls are hidden when the screen is below 600px wide.

2021-05-13 15:32 UTC, adekbadek approved these changes
The missing arrows are ok - this is for mobile users, who are more likely to swipe anyway.

2021-05-13 15:34 UTC, merged