feat: author profile block
Automattic/newspack-blocks pull request #763
Opened 2021-05-28 22:40 UTC by dkoo

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Registers a new "Author Profile" block which allows editors to choose either vanilla WP users or Co-authors Plus guest authors and display them in a standardized format in post or page content.

Closes #723.

### How to test the changes in this Pull Request:

1. In a post, confirm there's a new "Author Profile" block under the Newspack category in the block inserter.
2. Insert an author profile block. Observe the search UI and confirm that the list of suggestions shows both regular WP users and Co-authors guest authors*:

<img width="816" alt="Screen Shot 2021-05-28 at 4 34 45 PM" src="https://user-images.githubusercontent.com/2230142/120047762-a491fb80-bfd2-11eb-909e-3f2bac444178.png">

3. Save the post without selecting an author. View on the front-end; confirm that the block renders nothing if no author is selected.
4. Back in the editor, select an author from the suggestions list and by typing a name into the autocomplete input. (Use the "clear" button to choose another author after selecting one.) Add a second Author Profile block and make sure one contains a regular WP user and the other a guest author. Confirm that the preview shows the author info in both cases as expected**:

<img width="817" alt="Screen Shot 2021-05-28 at 4 37 03 PM" src="https://user-images.githubusercontent.com/2230142/120047888-f470c280-bfd2-11eb-80a3-930bd609406a.png">

5. Save the post, view on the front-end. Confirm that both blocks render as expected:

<img width="795" alt="Screen Shot 2021-05-28 at 4 39 22 PM" src="https://user-images.githubusercontent.com/2230142/120048011-44e82000-bfd3-11eb-9d51-b8a457c78b49.png">

6. Back in the editor, play with the various attribute options. Confirm that both the editor preview and the front-end render as expected based on the options selected.

<img width="279" alt="Screen Shot 2021-05-28 at 4 40 10 PM" src="https://user-images.githubusercontent.com/2230142/120048060-621cee80-bfd3-11eb-80ca-f2640f37ca1c.png">

* Because guest authors are a custom post type, we can't query both regular users and guest authors in a single query. Instead, we must query them separately and combine the results. For this reason, the list of suggestions will always alternate between the two types of authors and may not display strictly in reverse chronological order.
** The only _display_ difference between regular WP users and guest authors is in the social links: WP users have more metafield options for various social media services, whereas guest authors basically have just a website and email field (also Yahoo, AIM, and Jabber, but these aren't used elsewhere in the theme so I didn't include handling for them). WP users and guest authors also differ in the format of their edit links and archive page links.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2021-05-28 22:50 UTC, dkoo commented
@thomasguillot I notice that for square images like the avatars, there's no visual difference between `border-radius: 50%` and any value higher than 50%. Should we limit the range to a max of 50?

2021-06-02 13:07 UTC, adekbadek requested changes
Words fine, I like how versatile the `AutocompleteWithSuggestions` component is! Just a small block-keywords nitpick to fix.

2021-06-02 13:07 UTC, adekbadek commented on src/blocks/author-profile/edit.js
> +	const socialLinks = showSocial && author && author.social ? { ...author.social } : {};
Nit: `{...obj}` is same as `obj`:
```suggestion
	const socialLinks = ( showSocial && author && author.social ) || {};
```

2021-06-02 13:07 UTC, adekbadek commented on src/blocks/author-profile/index.js
> +		__( 'subscriptions', 'newspack-blocks' ),
These keywords are a bit odd in the context of authors - should be updated ;)

2021-06-02 16:23 UTC, thomasguillot commented
> And, I couldn't figure out how to create a number input like you had in the mockup

The Columns block is using this input

<img width="270" alt="Screenshot 2021-06-02 at 17 20 18" src="https://user-images.githubusercontent.com/177929/120516277-14372a80-c3c7-11eb-945d-4a311327a0c9.png">
<img width="273" alt="Screenshot 2021-06-02 at 17 20 26" src="https://user-images.githubusercontent.com/177929/120516283-15685780-c3c7-11eb-9014-b82851e100cd.png">

If it's too complex, let's limit the range to a max of 50%.

2021-06-02 16:58 UTC, thomasguillot commented
![Screenshot 2021-06-02 at 17 52 48](https://user-images.githubusercontent.com/177929/120520157-611d0000-c3cb-11eb-9809-671536c96f54.png)

Where is Dev McFly's avatar? 🤔  You can see in my dev tools that there is an image... is it because of lazy loading and it's a Gutenberg issue?

2021-06-02 17:03 UTC, thomasguillot requested changes
Overall this looks good. A few things:

* Move the "Clear" option to the toolbar with an Edit icon
* Remove the alignment option (is this really needed?)
* Disable links
* When in a group:
    * Fix the avatar resizing issue
    * Make sure the links and headings have the correct colour
![Screenshot 2021-06-02 at 18 01 24](https://user-images.githubusercontent.com/177929/120521356-c6bdbc00-c3cc-11eb-96e8-2cbf1bf3db80.png)

2021-06-02 17:26 UTC, dkoo commented
@thomasguillot Thanks for the design feedback! Just a few questions to clarify:

> Disable links

What do you mean by this? Remove any links in the author's bio text?

> Make sure the links and headings have the correct colour

Do we have functions in the theme or blocks plugin to determine the correct color based on background color? Could you point me to an example of a feature that does this so I can follow the same pattern?

2021-06-02 20:29 UTC, thomasguillot commented
>  I think I get it—you mean disabling outgoing links in the editor preview, right?

Yes

2021-06-02 20:39 UTC, thomasguillot commented
> Do we have functions (or CSS class names) in the theme or blocks plugin to determine the correct color based on background color? Could you point me to an example of a feature that does this so I can follow the same pattern?

Should be fixed in https://github.com/Automattic/newspack-blocks/pull/763/commits/a9b8e3e60e30e8e1aca7cba981e71f84f74b95df

2021-06-02 20:43 UTC, thomasguillot commented
Another idea, instead of a strict 240px avatar. What if we had a S/M/L/XL option?

* 72
* 128 (default)
* 192
* 256

2021-06-03 17:07 UTC, dkoo commented
> Another idea, instead of a strict 240px avatar. What if we had a S/M/L/XL option?

That's a good idea. That way, the relative widths of the avatar vs. author meta would be fluid based on the avatar size.

2021-06-03 21:42 UTC, dkoo commented on src/blocks/author-profile/edit.js
> +	const socialLinks = showSocial && author && author.social ? { ...author.social } : {};
I was maybe a bit overzealous when it comes to not mutating the `author` state object, but your suggestion doesn't seem to cause any issues as far as I can tell. Updated in d7e4a91.

2021-06-03 21:42 UTC, dkoo commented on src/blocks/author-profile/index.js
> +		__( 'subscriptions', 'newspack-blocks' ),
Whoops, fixed in  in d7e4a91!

2021-06-03 22:00 UTC, dkoo commented
> The Columns block is using this input

Thanks for the example! Updated to the `UnitControl` in bc637f5.

2021-06-03 22:18 UTC, dkoo commented
> A few things:
> 
> * Move the "Clear" option to the toolbar with an Edit icon
> * Remove the alignment option (is this really needed?)
> * Disable links

All updated in 7aa9e38!

2021-06-03 22:43 UTC, dkoo commented
> Another idea, instead of a strict 240px avatar. What if we had a S/M/L/XL option?

This is implemented in b8f79f0.

<img width="277" alt="Screen Shot 2021-06-03 at 4 42 45 PM" src="https://user-images.githubusercontent.com/2230142/120721300-c7b52300-c48a-11eb-9cef-b5021db49640.png">

2021-06-04 10:01 UTC, thomasguillot approved these changes
Looks good! Thanks @dkoo

2021-06-08 13:33 UTC, adekbadek approved these changes

2021-06-08 14:56 UTC, merged