feat(donate): streamlined block option
Automattic/newspack-blocks pull request #784
Opened 2021-07-01 07:54 UTC by adekbadek

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Introduces an experimental, streamlined option for the Donate block. When activated, the donation flow will be as short as possible - the donor will only have to provide credit card details & email address. 

### TODOs

- [ ] List to Stripe successfull payment via webhooks to send custom event to GA and update Campaigns data)

### How to test the changes in this Pull Request:

1. Set `newspack-plugin` to `feat/donation-block-streamlined` branch
2. Nothing should change yet, so test both donation platforms (WooCommerce (Newspack) and NRH) and confirm that donation flow works as before
3. Configure the site to use AMP Plus by adding the following env variable to `wp-config.php`: `define( 'NEWSPACK_AMP_PLUS_ENABLED', true );`
4. Set the Reader Revenue platform to NRH in the Reader Revenue wizard
5. Fill in the Stripe keys and choose a currency
6. On a page, insert a Donate block. Observe a new panel in editor sidebar - "Streamlined". Toggle the option on and publish the page
7. Observe that the Donate block features a credit card & email inputs
8. [Test](https://stripe.com/docs/testing#cards) a successful transaction with a `4242 4242 4242 4242` card (and any valid other details) and observe a green "Thank you" notice and a successful charge in Stripe (and a Customer created)
9. Test a 3D Secure (requiring authentication) transaction with a `4000 0027 6000 3184` card
9. Test a failed transaction with a `4000000000000002` card

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2021-07-01 17:48 UTC, dkoo requested changes
I'm not able to fully test this yet. When viewing a page with a streamlined Donate block on the front-end, I see this JS error in the console:

<img width="548" alt="Screen Shot 2021-07-01 at 11 34 56 AM" src="https://user-images.githubusercontent.com/2230142/124166716-6e77e980-da60-11eb-8912-51271b6940c5.png">

And the Stripe form doesn't load. Seems like it's a webpack build error. This is after running `npm ci && npm run build` in this repository. Also tried clearing `package-lock.json` and running `npm i && npm run build` with the same result. I'm running node v12.21.0.

2021-07-01 18:07 UTC, dkoo requested changes
Ok, I was able to get past the webpack error after rebuilding a few more times. I have no idea what caused it in the first place, but after clearing `node_modules` and `package-lock.json`, running `npm i`, then clearing them out again, restoring the checked-in `package-lock.json` and running `npm ci` again, I'm no longer seeing the error.

The streamlined flow works great and is so much more user-friendly than redirecting to a separate checkout page. I have a few suggestions below about the messaging and UI. Since payment processing can be a sensitive user experience I think we want to be as communicative as possible. We may even want to offer admins the ability to write their own success and error messaging (which would let them tailor their messaging according to their audience), but that could be a future enhancement.

2021-07-01 18:07 UTC, dkoo commented on src/blocks/donate/streamlined.js
> +			if ( error ) {
Could we add a message for the loading state instead of just disabling the form? When submitting something like credit card details it's nice to know what's happening at every step of the process. Even something simple like `Processing payment...` could be more reassuring that something is happening.

2021-07-02 10:10 UTC, adekbadek commented on src/blocks/donate/view.php
> +				<?php echo $form_footer; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
The `input[type="email"]` does not make it through sanitization. I think it's fine to ignore the warnings here, since any dynamic content in `newspack_blocks_render_block_donate_footer` is sanitized.

2021-07-02 10:19 UTC, adekbadek commented on src/blocks/donate/streamlined.js
> +			if ( error ) {
Good idea, done in 3f98383bbf79368b1b4e189410cefa07f0658700

2021-07-02 11:43 UTC, adekbadek commented on src/blocks/donate/streamlined.js
> +				renderMessages( [ __( 'Thank you!', 'newspack-blocks' ) ], messagesEl, 'success' );
Good ideas, done in 31ff9294242559ca1e7d405696a89d8341a5742d & 211bd99829dffdee9e19d1b02a87d8244254acc5

2021-07-02 11:53 UTC, adekbadek commented on src/blocks/donate/edit.js
> +						<i>{ __( 'Stripe credit card form will be rendered here.', 'newspack' ) }</i>
Done in 1df39caf1e3e3883f82e4c1e2fc22fd2d27aa181

2021-07-02 12:08 UTC, adekbadek commented
> We may even want to offer admins the ability to write their own success and error messaging (which would let them tailor their messaging according to their audience), but that could be a future enhancement.

Good idea, we should do that later.

> This is on the site owner to ensure they're compliant. Maybe we could include a link to this Stripe security guide in the "Stripe" tab in the dashboard if we want to educate users about security requirements, but I don't think we need to do anything beyond this in the code.

Added an SSL check & a warning in the Plugin part of this feature 👍

2021-07-02 20:59 UTC, dkoo commented on src/blocks/donate/view.php
> +				<?php echo $form_footer; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
Sounds good, thanks for clarifying.

2021-07-02 21:18 UTC, dkoo commented on src/blocks/donate/edit.js
> +						<i>{ __( 'Stripe credit card form will be rendered here.', 'newspack' ) }</i>
Looks good!

2021-07-02 21:18 UTC, dkoo commented on src/blocks/donate/streamlined.js
> +				renderMessages( [ __( 'Thank you!', 'newspack-blocks' ) ], messagesEl, 'success' );
🙌

2021-07-02 21:18 UTC, dkoo commented on src/blocks/donate/streamlined.js
> +			if ( error ) {
👍

2021-07-02 21:19 UTC, dkoo approved these changes
Thanks for the changes!

2021-07-05 15:46 UTC, thomasguillot approved these changes
I pushed a few design changes (nothing major -- just to be a little be more inline with the theme) https://github.com/Automattic/newspack-blocks/pull/784/commits/1d2c155a33b6977206b4ed356c71f47ecdbea3cd

2021-07-15 10:46 UTC, merged