Update prettier to wp-prettier@2.2.1-beta-1
Automattic/newspack-blocks pull request #817
Opened 2021-07-28 12:12 UTC by scinos

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

* Updates `wp-prettier` to the latest version, `2.2.1-beta-1`
* Re-format existing files to match the new prettier version

As part of this change, spaces in `package.json` and `package-lock.json` have been converted to tabs (as specified in `.prettierrc`). I strongly recommend disabling whitespace to review this PR.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2021-07-28 17:04 UTC, adekbadek approved these changes

2021-07-28 17:05 UTC, dkoo requested changes
@scinos Thanks for the updates! I tested locally and on an Atomic test site and saw no issues. However, I noticed that on this branch, Prettier auto-formatting in VSCode no longer works. Any idea why that might be?

2021-07-28 17:07 UTC, adekbadek requested changes
Whoops, duplicated review with @dkoo . I use Atom editor and did not run into issues. Un-approving so it's not mergeable and waiting for the resolution of the VS Code issue.

2021-07-28 17:10 UTC, dkoo approved these changes
Actually, it looks like after switching to the branch I just need to update certain formatting settings in VS Code settings. Approving!

2021-07-29 11:14 UTC, adekbadek approved these changes

2021-07-29 12:08 UTC, merged