Homepage Posts, Post Carousel: Add span to 'by' in block bylines
Automattic/newspack-blocks pull request #843
Opened 2021-08-19 20:12 UTC by laurelfulford

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR adds a `<span>` around the `by` text in the byline of the Post Carousel and Homepage Posts block.

It's to help us control this piece of the text differently with CSS, whether hiding (outstanding request), making it all caps or a different style, etc....

Closes #842.

### How to test the changes in this Pull Request:

1. Apply the PR and run `npm run build`.
2. Add a Homepage Posts and Post Carousel block to the editor. 
3. In the editor, inspect the blocks; confirm that the 'by' text in the byline is wrapped in a span, like `<span>by</span>`.
4. Publish the post. 
3. On the front-end, inspect the blocks; confirm that the 'by' text in the byline is wrapped in a span, like `<span>by</span>`.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2021-08-19 23:17 UTC, miguelpeixe requested changes
With the current approach, I still miss a class for the ability to easily select the element. This element has a sibling `<span />` with the classes `author vcard`. It would require the CSS selector to be something like `.byline span:not(.vcard)`, which is not ideal.

2021-08-20 00:14 UTC, laurelfulford commented
@miguelpeixe that's a really good point! Having a class will make for much nicer, and clearer, CSS. Added the class `.author-prefix` in e288302. Thanks!

2021-08-20 14:23 UTC, miguelpeixe approved these changes
💯

2021-08-20 18:04 UTC, laurelfulford commented
🙌 Thanks!

2021-08-20 18:04 UTC, merged