feat: author list block
Automattic/newspack-blocks pull request #947
Opened 2021-11-30 00:41 UTC by dkoo

### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-theme/blob/master/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes # .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2021-12-17 16:31 UTC, adekbadek requested changes
I imagine this will be a very useful features, not only for news publications 💪 
Gotta point out though that it's intimidating to review such a large PR 😬

2021-12-17 16:31 UTC, adekbadek commented on src/blocks/author-list/view.php
> + * Server-side render functions for the Author Profile block.
Nit:

```suggestion
 * Server-side render functions for the Author List block.
```

2021-12-17 16:31 UTC, adekbadek commented on src/blocks/author-list/view.php
> +			$first_letter = strtoupper( substr( $author['last_name'], 0, 1 ) );
A user with login `admin`, without neither first nor last name, ends up in "W" section when chunked alphabetically:

<img width="441" alt="image" src="https://user-images.githubusercontent.com/7383192/146574331-9b8163f6-27b8-4519-b1a1-b13e6ab1a896.png">

This is the last item on the whole list, so maybe the it's a matter of listing un-sortable (nameless) users after the sorted users. This happens both in editor and on the frontend.

2021-12-17 16:31 UTC, adekbadek commented on src/blocks/author-profile/view.php
> +	);
When a guest user has an avatar set, the avatar is **not displayed** on Author Block on the frontend (editor is fine). This does not happen on `master`.

2021-12-17 16:31 UTC, adekbadek commented on src/templates/author-profile-card.php
> +						<?php echo wp_kses_post( $author['avatar'] ); ?>
Hard to pin down the conditions (aspect ratio, size?), but when using this image, it comes out stretched: 

<img width="156" alt="image" src="https://user-images.githubusercontent.com/7383192/146575952-b0984dda-5cff-4a58-8473-db02d2cda2fd.png">

Image:

![image](https://user-images.githubusercontent.com/7383192/146576215-a47c505b-af9d-4613-929a-8b107569f970.png)

2021-12-17 19:37 UTC, dkoo commented on src/blocks/author-list/class-wp-rest-newspack-author-list-controller.php
> +		if ( 'users' !== $options['author_type'] && class_exists( 'CoAuthors_Guest_Authors' ) ) {
Most likely it won't, but this is a good suggestion for readability. Done on lines 159 and 186 in 2f972bb.

2021-12-17 19:47 UTC, dkoo commented on src/blocks/author-list/edit.js
> +								excludeEmpty ? __( 'Hide', 'newspack-blocks' ) : __( 'Show', 'newspack-blocks' )
Updated this and several other help messages in d586a1b.

2021-12-17 21:31 UTC, dkoo commented on src/blocks/author-list/edit.js
> +							label={ __( 'Exclude authors with 0 posts', 'newspack-blocks' ) }
This was a tricky one to debug. Investigating it uncovered a bug in Co-Authors Plus! When a guest author has a linked WP user the [`get_author_post_count` method](https://github.com/Automattic/Co-Authors-Plus/blob/3f71c41f3628bd5b848c401195798cf95f994c3b/co-authors-plus.php#L1763) only returns the post count of the linked WP user, not the sum of both guest author and user posts. 

Because of the way our block code is searching for WP users using `has_published_posts` as a `WP_User_Query` arg, then combining those results with a guest author query using `CoAuthors_Plus::get_author_post_count`, this bug results in the guest author getting dropped when "exclude authors with 0 posts" is on if either the WP user OR the guest author has 0 posts. 

This should be fixed in b48c67d, which foregoes the use of `CoAuthors_Plus::get_author_post_count` and just manually adds the post count of the guest author and the WP user to get the total post count.

This does bring up another potentially confusing edge case, where if a WP user with 0 posts is linked to a guest author with many posts, and the Author List block is set to display only WP users. In this case, displaying only WP users will display the WP user, not the linked guest author, and since the WP user has 0 posts, it won't be displayed if "exclude authors with 0 posts" is on. This, to me, is expected behavior even if it sounds confusing.

2021-12-17 21:37 UTC, dkoo commented on src/blocks/author-list/view.php
> +			$first_letter = strtoupper( substr( $author['last_name'], 0, 1 ) );
Ah, this is because I was assuming all users would have at least a display name, which isn't always the case. 48e5e7d adds another fallback to alphabetize by user login if there's no last name or display name.

2021-12-17 21:51 UTC, dkoo commented on src/templates/author-profile-card.php
> +						<?php echo wp_kses_post( $author['avatar'] ); ?>
This is happening on `master`, too. Seems to be a bug with the CSS for the avatars. I'll see if I can fix on this branch.

2021-12-18 03:51 UTC, dkoo commented on src/blocks/author-profile/view.php
> +	);
Good catch! 4c58457 should fix this.

2021-12-18 03:59 UTC, dkoo commented on src/templates/author-profile-card.php
> +						<?php echo wp_kses_post( $author['avatar'] ); ?>
d498c8f should fix this. The aspect ratio of the `figure` should be fixed to 1:1 with the image inside set to `object-fit: cover`, but I forgot to set both the height and the width (only the width was set, so height was defaulting to `auto`).

2022-01-05 15:13 UTC, adekbadek commented on src/blocks/author-list/edit.js
> +							label={ __( 'Exclude authors with 0 posts', 'newspack-blocks' ) }
This makes sense, thank you for the detailed response!

2022-01-05 15:25 UTC, adekbadek commented on src/blocks/author-list/edit.js
> +								label={ __( 'Hide default avatar', 'newspack-blocks' ) }
This seems to handle Guest Authors only – after toggling this option, WP users are still listed with the default avatars.

2022-01-05 15:25 UTC, adekbadek commented on src/blocks/author-list/view.php
> +			$first_letter = strtoupper( substr( $author['last_name'], 0, 1 ) );
The issue is still happening. In the examples below, `Robers Wpuser` & `admin` are both WP users:

1. If set to display all authors, `admin` is at the end, without a letter "A" preceding (there's a guest user already in an "A" section:

<img width="414" alt="image" src="https://user-images.githubusercontent.com/7383192/148242859-c51b5149-5d1c-4881-915b-261c2bd0aee3.png">

2. If set to display WP users only, `admin` is again at the end, but in an "A" section (there are no other WP users with names starting on "a"):

<img width="406" alt="image" src="https://user-images.githubusercontent.com/7383192/148243069-4a1d9692-f59d-47be-9c39-f1a1ff0599ba.png">

2022-01-06 18:49 UTC, dkoo commented on src/blocks/author-list/edit.js
> +								label={ __( 'Hide default avatar', 'newspack-blocks' ) }
Hmm, the logic applies to both author types, but it seems like the `avatar-default` class isn't always added to default avatars for some reason. b98c749 adds a bit of extra logic which should hopefully catch those instances.

2022-01-06 19:02 UTC, dkoo commented on src/blocks/author-list/view.php
> +			$first_letter = strtoupper( substr( $author['last_name'], 0, 1 ) );
f8532a6 fixes this. The issue was happening because we weren't standardizing the case of the letters, so `A` and `a` were sorted differently.

2022-01-07 09:54 UTC, adekbadek approved these changes
All good now 👌

2022-01-07 17:17 UTC, merged