fix: view scripts in AMP Plus mode
Automattic/newspack-blocks pull request #954
Opened 2021-12-03 12:43 UTC by adekbadek

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #953

Not all view scripts (JS loaded on the frontend) were handled in AMP Plus mode. This PR fixes that, so that the blocks' interactions in AMP Plus mode are as they do with AMP disabled.

### How to test the changes in this Pull Request:

1. Observe that #953 is not reproducible
2. Confirm that Carousel block's frontend JS-reliant interactions work as expected with AMP Plus mode on, and exactly as with AMP disabled 

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2021-12-03 18:48 UTC, dkoo requested changes
A couple of issues:

1. When in AMP Plus mode, images in posts loaded after clicking "load more" are rendered with incorrect sizing. This doesn't happen when AMP is turned off for the same page. We may have to add code in the non-AMP JS to manually size the images to get around AMP's image sizing behavior.

<img width="821" alt="Screen Shot 2021-12-03 at 11 39 26 AM" src="https://user-images.githubusercontent.com/2230142/144655659-014b3beb-781c-4f1e-a42d-e64cbf849b75.png">

2. Also when in AMP Plus mode, after clicking "Load more" the "loading" visual state is not shown. There's no indication of any action occurring after clicking the button, until the new posts appear.

[Example page](https://thin-marlin.jurassic.ninja/) where this is happening.

2021-12-03 18:55 UTC, dkoo commented
Another issue with the Post Carousel block: in AMP Plus mode, the images are not visible at all because the post-page-load resizing doesn't seem to be working. Maybe due to similar reasons as the sizing issue in Homepage Posts described above.

2021-12-06 12:40 UTC, adekbadek commented
I've changed the approach here – see updated PR description.

2021-12-07 00:01 UTC, dkoo approved these changes
This works with the reduced scope! However, sooner or later we'll have to figure out how to run non-AMP JS scripts on AMP pages in an AMP Plus environment, to really take advantage of AMP Plus.

2021-12-07 08:13 UTC, merged