feat(donate-stripe): hide fee checkbox if fees are zero
Automattic/newspack-blocks pull request #985
Opened 2021-12-16 15:04 UTC by adekbadek

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Allows hiding of cover-fees checkbox (#928) if the fees amount to 0.

### How to test the changes in this Pull Request:

1. Set Stripe as the Reader Revenue platform
1. Verify that the cover-fees checkbox is still there on this branch
2. Set `newspack_blocks_donate_fee_multiplier` to 0, verify the checkbox is still there
3. Set `newspack_blocks_donate_fee_static` to 0 – observe the checkbox is not there anymore

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2022-01-03 20:19 UTC, dkoo requested changes
As I was testing this I think I caught a math error in the function computing the fee amount. Also have a suggestion on rendering the fee on the front-end as a formatted currency string instead of as a float.

2022-01-03 20:19 UTC, dkoo commented on src/blocks/donate/streamlined.js
> +	return parseFloat(
We're using `toFixed( 2 )` to control the number of digits that appear in the fee amount, but `parseFloat` will subsequently drop trailing zeroes anyway, so a number like `5.30` will get printed as `5.3` on the front-end:

<img width="617" alt="Screen Shot 2022-01-03 at 1 07 13 PM" src="https://user-images.githubusercontent.com/2230142/147975136-e95970e0-effb-45dc-abab-8261163ba85a.png">

This could be solved by using `toString()` on the return value instead, which will ensure that the amount will always get printed with two decimals.

But even better, would it be possible to use the site's active currency plus [`toLocaleString()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString) to render the amount in the proper currency format? This might be overkill but it would ensure that the formatting always matches the active currency.

2022-01-03 20:19 UTC, dkoo commented on src/blocks/donate/streamlined.js
> +		( ( ( amount + feeStatic ) / ( 100 - feeMultiplier ) ) * 100 - amount ).toFixed( 2 )
I think this math is slightly off, if I'm not mistaken. Are the default values (`2.9` and `0.3`) coming from Stripe's [integrated pricing](https://stripe.com/pricing)? If so, shouldn't this calculation be:

```suggestion
		( amount * ( feeMultiplier / 100 ) + feeStatic ).toFixed( 2 )
```

Given a donation amount of $100, the fee should be:

Multiplier: 2.9% of $100 = $2.90
Static: $0.30
Total fee: $3.20

Right?

2022-01-03 20:19 UTC, dkoo commented on src/blocks/donate/streamlined.test.js
> +		expect( computeFeeAmount( 1, 2.9, 0.3 ) ).toBe( 0.34 );
These test values will need to be updated along with the `computeFeeAmount` function.

2022-01-04 09:19 UTC, adekbadek commented on src/blocks/donate/streamlined.js
> +	return parseFloat(
Fixed in 57aabfcba58e83de5bffafa0ad07e3b77eb7a019. I think using `toLocaleString` is an overkill – and also on the PHP side the currency symbol is used, so that's more coherent.

2022-01-04 16:17 UTC, dkoo commented on src/blocks/donate/streamlined.js
> +		( ( ( amount + feeStatic ) / ( 100 - feeMultiplier ) ) * 100 - amount ).toFixed( 2 )
Aha, that makes sense. Thanks for explaining.

2022-01-04 17:15 UTC, dkoo approved these changes
Changes look good 👍

2022-01-05 10:13 UTC, merged